// =====================================================================
//  STDBITCRUSHER — Bit depth and sample-rate reduction
//  A digital degrader. Bits quantises the signal to between 1 and 16 bits (the fewer, the grittier and more noise-like), Rate resamples it at anything from 200 Hz up to the full sample rate with no anti-aliasing (the reflections are the point), and Dither adds a touch of noise before quantising to soften the stair-steps or, at high settings, to give lo-fi hiss. Tone smooths the result with a low-pass and Mix blends it with the clean signal for parallel crushing. A live picture shows the staircase the signal is being forced onto.
//  (generated by factory/std/build.mjs from factory/std/fx-*.mjs — edit the definition, not this file)
// =====================================================================
// ---- Std prelude: shared helpers (pasted into every Std* effect by factory/std/build.mjs) ----
const MAX_FRAMES: i32 = 8192;
const MAX_CHANNELS: i32 = 2;
const MAX_PARAMS: i32 = 64;
const TWO_PI: f32 = 6.28318530717959;
const PI: f32 = 3.14159265358979;

const inBuf:  StaticArray<f32> = new StaticArray<f32>(MAX_FRAMES * MAX_CHANNELS);
const outBuf: StaticArray<f32> = new StaticArray<f32>(MAX_FRAMES * MAX_CHANNELS);
const params: StaticArray<f32> = new StaticArray<f32>(MAX_PARAMS);
const display: StaticArray<f32> = new StaticArray<f32>(16);

let sampleRate: f32 = 48000.0;
let hostPlaying: bool = false;
let hostBpm: f32 = 120.0;
let beatPos: f64 = 0.0;
let seed: u32 = 12345;

@inline function clampf(x: f32, lo: f32, hi: f32): f32 { return x < lo ? lo : (x > hi ? hi : x); }
@inline function minf(a: f32, b: f32): f32 { return a < b ? a : b; }
@inline function maxf(a: f32, b: f32): f32 { return a > b ? a : b; }
@inline function absf(x: f32): f32 { return x < 0.0 ? -x : x; }
@inline function rnd(): f32 { seed = seed * 1664525 + 1013904223; return f32(seed >> 8) * (1.0 / 8388608.0) - 1.0; }
// flush denormals out of feedback paths
@inline function fz(x: f32): f32 { return (x > -1.0e-18 && x < 1.0e-18) ? 0.0 : x; }
// exponential map: v in 0..1 -> lo..hi
@inline function expMap(v: f32, lo: f32, hi: f32): f32 { return lo * f32(Mathf.pow(hi / lo, v)); }
@inline function dbLin(db: f32): f32 { return f32(Mathf.pow(10.0, db * 0.05)); }
@inline function linDb(x: f32): f32 { return 20.0 * f32(Mathf.log10(x + 1.0e-9)); }
@inline function tanhf(x: f32): f32 { return f32(Mathf.tanh(x)); }
// one-pole smoothing coefficient for a cutoff in Hz
@inline function opK(hz: f32): f32 { return 1.0 - f32(Mathf.exp(-TWO_PI * clampf(hz, 1.0, sampleRate * 0.45) / sampleRate)); }
// smoothing coefficient for a time constant in seconds
@inline function tcK(sec: f32): f32 { return 1.0 - f32(Mathf.exp(-1.0 / (maxf(sec, 0.00002) * sampleRate))); }
// soft output limiter: transparent below 0.8, rounds smoothly to 1.0
@inline function softLim(x: f32): f32 {
  const a: f32 = absf(x);
  if (a < 0.8) return x;
  const y: f32 = 0.8 + 0.2 * f32(Mathf.tanh((a - 0.8) * 5.0));
  return x < 0.0 ? -y : y;
}

// power-of-two delay line with linear interpolation. base = start in buf, mask = len-1, wr = write index
@inline function dlr(buf: StaticArray<f32>, base: i32, mask: i32, wr: i32, d: f32): f32 {
  const p: f32 = f32(wr) - d;
  const fl: f32 = f32(Mathf.floor(p));
  const i0: i32 = i32(fl);
  const fr: f32 = p - fl;
  const a: f32 = buf[base + (i0 & mask)];
  const b: f32 = buf[base + ((i0 + 1) & mask)];
  return a + (b - a) * fr;
}

// RBJ biquad. coefficients stored normalised at cf[o..o+4] = b0 b1 b2 a1 a2
// t: 0 LP, 1 HP, 2 BP (0 dB peak), 3 notch, 4 peaking, 5 low shelf, 6 high shelf, 7 allpass
function bqSetSr(cf: StaticArray<f32>, o: i32, t: i32, f0: f32, q: f32, g: f32, sr: f32): void {
  const fc: f32 = clampf(f0, 5.0, sr * 0.45);
  const w0: f32 = TWO_PI * fc / sr;
  const c: f32 = f32(Mathf.cos(w0));
  const s: f32 = f32(Mathf.sin(w0));
  const al: f32 = s / (2.0 * maxf(q, 0.05));
  const A: f32 = f32(Mathf.pow(10.0, g / 40.0));
  let b0: f32 = 1.0; let b1: f32 = 0.0; let b2: f32 = 0.0;
  let a0: f32 = 1.0; let a1: f32 = 0.0; let a2: f32 = 0.0;
  if (t == 0) { b0 = (1.0 - c) * 0.5; b1 = 1.0 - c; b2 = b0; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  else if (t == 1) { b0 = (1.0 + c) * 0.5; b1 = -(1.0 + c); b2 = b0; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  else if (t == 2) { b0 = al; b1 = 0.0; b2 = -al; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  else if (t == 3) { b0 = 1.0; b1 = -2.0 * c; b2 = 1.0; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  else if (t == 4) { b0 = 1.0 + al * A; b1 = -2.0 * c; b2 = 1.0 - al * A; a0 = 1.0 + al / A; a1 = -2.0 * c; a2 = 1.0 - al / A; }
  else if (t == 5) {
    const sa: f32 = 2.0 * f32(Mathf.sqrt(A)) * al;
    b0 = A * ((A + 1.0) - (A - 1.0) * c + sa); b1 = 2.0 * A * ((A - 1.0) - (A + 1.0) * c); b2 = A * ((A + 1.0) - (A - 1.0) * c - sa);
    a0 = (A + 1.0) + (A - 1.0) * c + sa; a1 = -2.0 * ((A - 1.0) + (A + 1.0) * c); a2 = (A + 1.0) + (A - 1.0) * c - sa;
  } else if (t == 6) {
    const sb: f32 = 2.0 * f32(Mathf.sqrt(A)) * al;
    b0 = A * ((A + 1.0) + (A - 1.0) * c + sb); b1 = -2.0 * A * ((A - 1.0) + (A + 1.0) * c); b2 = A * ((A + 1.0) + (A - 1.0) * c - sb);
    a0 = (A + 1.0) - (A - 1.0) * c + sb; a1 = 2.0 * ((A - 1.0) - (A + 1.0) * c); a2 = (A + 1.0) - (A - 1.0) * c - sb;
  } else { b0 = 1.0 - al; b1 = -2.0 * c; b2 = 1.0 + al; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  const ia: f32 = 1.0 / a0;
  cf[o] = b0 * ia; cf[o + 1] = b1 * ia; cf[o + 2] = b2 * ia; cf[o + 3] = a1 * ia; cf[o + 4] = a2 * ia;
}
@inline function bqSet(cf: StaticArray<f32>, o: i32, t: i32, f0: f32, q: f32, g: f32): void { bqSetSr(cf, o, t, f0, q, g, sampleRate); }
// transposed direct form II; state z[s], z[s+1]
@inline function bq(cf: StaticArray<f32>, o: i32, z: StaticArray<f32>, s: i32, x: f32): f32 {
  const y: f32 = cf[o] * x + z[s];
  z[s] = fz(cf[o + 1] * x - cf[o + 3] * y + z[s + 1]);
  z[s + 1] = fz(cf[o + 2] * x - cf[o + 4] * y);
  return y;
}

const NUM_PARAMS: i32 = 6;
const P_BITS: i32 = 0;
const P_RATE: i32 = 1;
const P_DITHER: i32 = 2;
const P_TONE: i32 = 3;
const P_MIX: i32 = 4;
const P_OUTPUT: i32 = 5;
function setDefaults(): void {
  params[0] = 8.0;   // Bits
  params[1] = 0.7;   // Rate
  params[2] = 0.2;   // Dither
  params[3] = 1.0;   // Tone
  params[4] = 1.0;   // Mix
  params[5] = 0.0;   // Output
}


const bph: StaticArray<f32> = new StaticArray<f32>(2); const bhold: StaticArray<f32> = new StaticArray<f32>(2);
const blp: StaticArray<f32> = new StaticArray<f32>(2);

export function getInputPtr(): usize  { return changetype<usize>(inBuf); }
export function getOutputPtr(): usize { return changetype<usize>(outBuf); }
export function getParamsPtr(): usize { return changetype<usize>(params); }
export function getNumParams(): i32   { return NUM_PARAMS; }
export function getDisplayPtr(): usize { return changetype<usize>(display); }
export function transport(playing: i32, ppq: f64, bpm: f32): void {
  hostPlaying = playing != 0; if (bpm > 20.0) hostBpm = bpm;
  if (hostPlaying) beatPos = ppq;
}

export function init(sr: f32, maxFrames: i32, numChannels: i32): void {
  sampleRate = sr > 0.0 ? sr : 48000.0;
  hostPlaying = false; hostBpm = 120.0; beatPos = 0.0; seed = 12345;
  setDefaults();
  for (let i = 0; i < 16; i++) display[i] = 0.0;
  for (let i = 0; i < 2; i++) { bph[i] = 1.0; bhold[i] = 0.0; blp[i] = 0.0; }
}

export function process(n: i32): void {
  const sr: f32 = sampleRate;
  let pkIn: f32 = 0.0; let pkOut: f32 = 0.0;
  
  const step: f32 = 2.0 / f32(Mathf.pow(2.0, f32(i32(params[P_BITS] + 0.5))));
  const ratio: f32 = minf(1.0, expMap(params[P_RATE], 200.0, 48000.0) / sr);
  const dith: f32 = params[P_DITHER] * step;
  const lpK: f32 = opK(expMap(params[P_TONE], 500.0, 20000.0));
  const mix: f32 = params[P_MIX]; const outG: f32 = dbLin(params[P_OUTPUT]);
  for (let f = 0; f < n; f++) {
    
    for (let c: i32 = 0; c < 2; c++) {
      const x: f32 = inBuf[c * MAX_FRAMES + f];
      let y: f32 = x;
      
  bph[c] += ratio;
  if (bph[c] >= 1.0) {
    bph[c] -= 1.0;
    const d: f32 = (rnd() + rnd()) * 0.5 * dith;
    bhold[c] = clampf(f32(Mathf.floor((x + d) / step + 0.5)) * step, -1.0, 1.0);
  }
  blp[c] += lpK * (bhold[c] - blp[c]);
  y = softLim((x * (1.0 - mix) + blp[c] * mix) * outG);
      if (!(y == y)) y = 0.0;
      outBuf[c * MAX_FRAMES + f] = y;
      pkIn = maxf(pkIn, absf(x)); pkOut = maxf(pkOut, absf(y));
    }
    
  }
  display[0] = maxf(display[0] * 0.8, clampf(pkOut, 0.0, 1.0));
  display[1] = maxf(display[1] * 0.8, clampf(pkIn, 0.0, 1.0));
  
}
