// =====================================================================
//  KGrbdPa — GENERATED by factory/kgrbdpa/build.mjs. Edit the sources:
//    factory/kgrbdpa/params.mjs   (parameter table, patch-bay jacks, packing)
//    factory/kgrbdpa/seqs.mjs     (default sequences)
//    factory/kgrbdpa/dsp/core.ts
//    factory/kgrbdpa/dsp/osc.ts
//    factory/kgrbdpa/dsp/mods.ts
//    factory/kgrbdpa/dsp/keys.ts
//    factory/kgrbdpa/dsp/main.ts
// =====================================================================

const NP: i32 = 78;
const NUM_PARAMS: i32 = 34;
const P_PITCHW: i32 = 0;
const P_MODW: i32 = 1;
const P_GLIDE: i32 = 2;
const P_PLAY: i32 = 3;
const P_HOLD: i32 = 4;
const P_GL_TYPE: i32 = 5;
const P_GL_LEGATO: i32 = 6;
const P_GL_GATED: i32 = 7;
const P_KB_OCT: i32 = 8;
const P_KB_TRANS: i32 = 9;
const P_ARP_RATE: i32 = 10;
const P_ARP_MODE: i32 = 11;
const P_ARP_DIR: i32 = 12;
const P_OCT_SEQ: i32 = 13;
const P_TAP_BPM: i32 = 14;
const P_CLK_SRC: i32 = 15;
const P_EXT_MODE: i32 = 16;
const P_EXT_PPQN: i32 = 17;
const P_OUT_PPQN: i32 = 18;
const P_MOD_RATE: i32 = 19;
const P_MOD_FINE: i32 = 20;
const P_MOD_WAVE: i32 = 21;
const P_MOD_PITCH: i32 = 22;
const P_MOD_CUT: i32 = 23;
const P_MOD_PW: i32 = 24;
const P_O1_OCT: i32 = 25;
const P_O1_WAVE: i32 = 26;
const P_SYNC: i32 = 27;
const P_O2_OCT: i32 = 28;
const P_O2_FREQ: i32 = 29;
const P_O2_WAVE: i32 = 30;
const P_MIX_O1: i32 = 31;
const P_MIX_O2: i32 = 32;
const P_MIX_NZ: i32 = 33;
const P_HP_CUT: i32 = 34;
const P_ATT: i32 = 35;
const P_CUTOFF: i32 = 36;
const P_RESO: i32 = 37;
const P_ENV_AMT: i32 = 38;
const P_KBD_TRK: i32 = 39;
const P_ATK: i32 = 40;
const P_DEC: i32 = 41;
const P_SUS: i32 = 42;
const P_REL: i32 = 43;
const P_VOLUME: i32 = 44;
const P_VCA_MODE: i32 = 45;
const P_REV_MIX: i32 = 46;
const P_FINE: i32 = 47;
const P_INST_LVL: i32 = 48;
const P_DRIFT: i32 = 49;
const P_NOTE_PRI: i32 = 50;
const P_BEND_UP: i32 = 51;
const P_BEND_DN: i32 = 52;
const P_KB_RANGE: i32 = 53;
const P_LOCAL: i32 = 54;
const P_PB_O1_PITCH: i32 = 55;
const P_PB_O1_PWM: i32 = 56;
const P_PB_O2_PITCH: i32 = 57;
const P_PB_O2_FM: i32 = 58;
const P_PB_LFO_RATE: i32 = 59;
const P_PB_LFO_SYNC: i32 = 60;
const P_PB_MX_O1: i32 = 61;
const P_PB_MX_O2: i32 = 62;
const P_PB_MX_NZ: i32 = 63;
const P_PB_MULT_A: i32 = 64;
const P_PB_MULT_B: i32 = 65;
const P_PB_HP_IN: i32 = 66;
const P_PB_ATT_IN: i32 = 67;
const P_PB_F_IN: i32 = 68;
const P_PB_F_ENVAMT: i32 = 69;
const P_PB_F_CUT: i32 = 70;
const P_PB_E_TRIG: i32 = 71;
const P_PB_V_AMT: i32 = 72;
const P_PB_V_IN: i32 = 73;
const P_PB_R_IN: i32 = 74;
const P_PB_CLK_IN: i32 = 75;
const P_PB_ONOFF_IN: i32 = 76;
const P_PB_RESET_IN: i32 = 77;
const PSLOT: StaticArray<i32> = [0, 1, 2, 33, 33, 27, 33, 33, 28, 27, 3, 32, 33, 33, 27, 33, 33, 32, 32, 4, 5, 29, 6, 7, 8, 30, 31, 33, 32, 9, 33, 10, 11, 12, 13, 14, 15, 16, 17, 33, 18, 19, 20, 21, 22, 33, 23, 24, 25, 26, 33, 27, 27, 33, 33, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 32, 32, 32];
const PMULT: StaticArray<i32> = [1, 1, 1, 972, 1944, 4390625, 3888, 7776, 2476099, 281, 1, 5377456, 4, 12, 1, 15552, 31104, 6859, 96026, 1, 1, 2476099, 1, 1, 1, 2476099, 2476099, 62208, 1344364, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 36, 1, 1, 1, 1, 1, 108, 1, 1, 1, 1, 324, 7025, 175625, 124416, 248832, 1, 19, 361, 6859, 130321, 1, 19, 361, 6859, 130321, 1, 19, 361, 6859, 130321, 1, 19, 361, 6859, 130321, 1, 19, 361];
const PSTEPS: StaticArray<i32> = [0, 0, 0, 2, 2, 3, 2, 2, 5, 25, 0, 3, 3, 3, 281, 2, 2, 14, 14, 0, 0, 4, 0, 0, 0, 4, 4, 2, 4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 25, 25, 2, 2, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19];
const PDIRECT: StaticArray<i32> = [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
const PMIN: StaticArray<f32> = [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.0, -12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
const PMAX: StaticArray<f32> = [1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 12.0, 1.0, 2.0, 2.0, 2.0, 280.0, 1.0, 1.0, 13.0, 13.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 3.0, 3.0, 1.0, 3.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 24.0, 24.0, 1.0, 1.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0, 18.0];
const NSRC: i32 = 18;
const NDST: i32 = 23;
const S_GATE: i32 = 1;
const S_KB: i32 = 2;
const S_VEL: i32 = 3;
const S_LFO: i32 = 4;
const S_SH: i32 = 5;
const S_O1: i32 = 6;
const S_O2: i32 = 7;
const S_MIX: i32 = 8;
const S_HP: i32 = 9;
const S_ATT: i32 = 10;
const S_MULT: i32 = 11;
const S_FIL: i32 = 12;
const S_ENVP: i32 = 13;
const S_ENVN: i32 = 14;
const S_REV: i32 = 15;
const S_EURO: i32 = 16;
const S_CLK: i32 = 17;
const S_EXT: i32 = 18;
const D_O1_PITCH: i32 = 0;
const D_O1_PWM: i32 = 1;
const D_O2_PITCH: i32 = 2;
const D_O2_FM: i32 = 3;
const D_LFO_RATE: i32 = 4;
const D_LFO_SYNC: i32 = 5;
const D_MX_O1: i32 = 6;
const D_MX_O2: i32 = 7;
const D_MX_NZ: i32 = 8;
const D_MULT_A: i32 = 9;
const D_MULT_B: i32 = 10;
const D_HP_IN: i32 = 11;
const D_ATT_IN: i32 = 12;
const D_F_IN: i32 = 13;
const D_F_ENVAMT: i32 = 14;
const D_F_CUT: i32 = 15;
const D_E_TRIG: i32 = 16;
const D_V_AMT: i32 = 17;
const D_V_IN: i32 = 18;
const D_R_IN: i32 = 19;
const D_CLK_IN: i32 = 20;
const D_ONOFF_IN: i32 = 21;
const D_RESET_IN: i32 = 22;
const CLOCK_DIV: StaticArray<f32> = [16.0, 12.0, 8.0, 6.0, 4.0, 3.0, 2.6666666666666665, 2.0, 1.5, 1.3333333333333333, 1.0, 0.75, 0.6666666666666666, 0.5, 0.375, 0.3333333333333333, 0.25, 0.1875, 0.16666666666666666, 0.125, 0.09375, 0.08333333333333333, 0.0625, 0.041666666666666664];
const CC90_V: StaticArray<i32> = [0, 5, 11, 16, 21, 27, 32, 37, 43, 48, 53, 59, 64, 69, 75, 80, 85, 91, 96, 101, 107, 112, 117, 123];
const PPQN_V: StaticArray<i32> = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 24, 48];
function setDefaults(): void {
  params[0] = 0.0;
  params[1] = 0.0;
  params[2] = 0.0;
  params[3] = 0.45;
  params[4] = 0.4;
  params[5] = 0.0;
  params[6] = 0.0;
  params[7] = 0.0;
  params[8] = 0.0;
  params[9] = 0.0;
  params[10] = 0.6;
  params[11] = 0.6;
  params[12] = 0.0;
  params[13] = 0.3;
  params[14] = 0.0;
  params[15] = 0.7;
  params[16] = 0.15;
  params[17] = 0.25;
  params[18] = 0.1;
  params[19] = 0.45;
  params[20] = 0.55;
  params[21] = 0.3;
  params[22] = 0.7;
  params[23] = 0.0;
  params[24] = 0.0;
  params[25] = 1.0;
  params[26] = 0.25;
  params[27] = 9149922.0;
  params[28] = 4952198.0;
  params[29] = 0.0;
  params[30] = 4952198.0;
  params[31] = 2476099.0;
  params[32] = 1447249.0;
  params[33] = 249481.0;
}
function SEQ_DEFAULTS(): void {
  seqLen[0] = 16;
  seqNote[0] = 45; seqFlag[0] = 0;
  seqNote[1] = 45; seqFlag[1] = 0;
  seqNote[2] = -1; seqFlag[2] = 0;
  seqNote[3] = 57; seqFlag[3] = 2;
  seqNote[4] = 45; seqFlag[4] = 0;
  seqNote[5] = 55; seqFlag[5] = 1;
  seqNote[6] = -1; seqFlag[6] = 0;
  seqNote[7] = 45; seqFlag[7] = 2;
  seqNote[8] = 48; seqFlag[8] = 1;
  seqNote[9] = -1; seqFlag[9] = 0;
  seqNote[10] = 45; seqFlag[10] = 0;
  seqNote[11] = 52; seqFlag[11] = 2;
  seqNote[12] = -1; seqFlag[12] = 0;
  seqNote[13] = 43; seqFlag[13] = 0;
  seqNote[14] = 45; seqFlag[14] = 0;
  seqNote[15] = -1; seqFlag[15] = 0;
  seqLen[1] = 16;
  seqNote[256] = 48; seqFlag[256] = 0;
  seqNote[257] = 52; seqFlag[257] = 0;
  seqNote[258] = 55; seqFlag[258] = 0;
  seqNote[259] = 59; seqFlag[259] = 0;
  seqNote[260] = 60; seqFlag[260] = 0;
  seqNote[261] = 59; seqFlag[261] = 0;
  seqNote[262] = 55; seqFlag[262] = 0;
  seqNote[263] = 52; seqFlag[263] = 0;
  seqNote[264] = 50; seqFlag[264] = 0;
  seqNote[265] = 53; seqFlag[265] = 0;
  seqNote[266] = 57; seqFlag[266] = 0;
  seqNote[267] = 60; seqFlag[267] = 0;
  seqNote[268] = 62; seqFlag[268] = 0;
  seqNote[269] = 60; seqFlag[269] = 0;
  seqNote[270] = 57; seqFlag[270] = 0;
  seqNote[271] = 53; seqFlag[271] = 0;
  seqLen[2] = 8;
  seqNote[512] = 36; seqFlag[512] = 0;
  seqNote[513] = -1; seqFlag[513] = 0;
  seqNote[514] = 36; seqFlag[514] = 0;
  seqNote[515] = 39; seqFlag[515] = 1;
  seqNote[516] = 43; seqFlag[516] = 2;
  seqNote[517] = -1; seqFlag[517] = 0;
  seqNote[518] = 41; seqFlag[518] = 0;
  seqNote[519] = 43; seqFlag[519] = 1;
}

// =====================================================================
//  core.ts — shared primitives for KGrbdPa: ABI buffers, packed-parameter
//  decoding (with MIDI-CC overrides), noise, saturators, one-pole filters.
//  Pasted after the generated tables. Everything is f32 and allocation-free
//  after init().
//
//  VOLTAGE MODEL: every jack of the patch bay carries volts, like the hardware:
//  audio ±5 V (10 Vpp), pitch CV 1 V/oct, gate 0/+8 V, envelope 0…+8 V,
//  KB VEL 0…+5 V. The host sees ±1 = ±8 V.
// =====================================================================

const MAX_FRAMES: i32 = 8192;
const MAX_PARAMS: i32 = 64;
const PI: f32 = 3.14159265358979;
const TWO_PI: f32 = 6.28318530717959;
const C4_HZ: f32 = 261.6255653;           // 8' at MIDI note 60 (concert pitch)

const inBuf  = new StaticArray<f32>(MAX_FRAMES * 2);
const outBuf = new StaticArray<f32>(MAX_FRAMES * 2);
const params = new StaticArray<f32>(MAX_PARAMS);
const display = new StaticArray<f32>(16);

let SR: f32 = 48000.0;
let invSR: f32 = 1.0 / 48000.0;

@inline function clampf(x: f32, lo: f32, hi: f32): f32 { return x < lo ? lo : (x > hi ? hi : x); }
@inline function minf(a: f32, b: f32): f32 { return a < b ? a : b; }
@inline function maxf(a: f32, b: f32): f32 { return a > b ? a : b; }
@inline function absf(x: f32): f32 { return x < 0.0 ? -x : x; }
@inline function exp2f(x: f32): f32 { return Mathf.exp(x * <f32>0.6931472); }
@inline function finite(x: f32): f32 { return (x > -1.0e6 && x < 1.0e6) ? x : <f32>0.0; }
@inline function denorm(x: f32): f32 { return (x > 1.0e-18 || x < -1.0e-18) ? x : <f32>0.0; }

// ---- noise -------------------------------------------------------------
let rng: u32 = 0x9e3779b9;
@inline function white(): f32 {
  rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5;
  return f32(rng) * <f32>4.656612873e-10 - <f32>1.0;      // [-1, 1)
}
@inline function rand01(): f32 { return (white() + <f32>1.0) * <f32>0.5; }

// ---- saturators ----------------------------------------------------------
// identity near 0, saturates at ±1
@inline function softclip(x: f32): f32 {
  if (x > 3.0) return 1.0;
  if (x < -3.0) return -1.0;
  const x2 = x * x;
  return x * (27.0 + x2) / (27.0 + 9.0 * x2);
}
// transparent below `knee`, smooth tanh knee up to `ceil` (both in the signal's units)
@inline function kneeClip(x: f32, knee: f32, ceil: f32): f32 {
  const a = x < 0.0 ? -x : x;
  if (a <= knee) return x;
  const w = ceil - knee;
  const m: f32 = knee + w * Mathf.tanh((a - knee) / w);
  return x < 0.0 ? -m : m;
}

// ---- packed parameters -------------------------------------------------------
// params[] holds the host slots. Every logical parameter lives in one slot as a
// mixed-radix digit (factory/kgrbdpa/params.mjs). A[] = decoded actual values,
// An[] = the same normalised 0..1, AI[] = integer value (for int/sel params).
// MIDI CCs write A/An/AI directly; the value stays until the HOST changes that
// parameter again (RH/AH remember the last host-side value per parameter).
const A = new StaticArray<f32>(NP);
const An = new StaticArray<f32>(NP);
const AI = new StaticArray<i32>(NP);
const RH = new StaticArray<i32>(NP);      // last host raw digit (packed params)
const AH = new StaticArray<f32>(NP);      // last host value (direct params)
const slotCache = new StaticArray<f32>(MAX_PARAMS);
let paramsDirty: bool = true;             // set whenever any parameter changed (host or CC)

function decodeSlot(s: i32, v: f32): void {
  let k: i32 = i32(nearest<f32>(v));
  if (k < 0) k = 0;
  if (k > 16777215) k = 16777215;
  for (let i = 0; i < NP; i++) {
    if (unchecked(PSLOT[i]) != s) continue;
    const lo = unchecked(PMIN[i]);
    const hi = unchecked(PMAX[i]);
    if (unchecked(PDIRECT[i]) != 0) {
      const a = clampf(v, lo, hi);
      if (a == unchecked(AH[i])) continue;
      unchecked(AH[i] = a);
      unchecked(A[i] = a);
      unchecked(An[i] = (a - lo) / (hi - lo));
      unchecked(AI[i] = 0);
    } else {
      const steps = unchecked(PSTEPS[i]);
      const raw = (k / unchecked(PMULT[i])) % steps;
      if (raw == unchecked(RH[i])) continue;
      unchecked(RH[i] = raw);
      const n: f32 = steps > 1 ? f32(raw) / f32(steps - 1) : <f32>0.0;
      unchecked(An[i] = n);
      unchecked(A[i] = lo + f32(raw));
      unchecked(AI[i] = i32(lo) + raw);
    }
    paramsDirty = true;
  }
}
// Returns true when any slot changed since the last call.
function refreshParams(): bool {
  let changed = false;
  for (let s = 0; s < NUM_PARAMS; s++) {
    const v = unchecked(params[s]);
    if (v != unchecked(slotCache[s])) { unchecked(slotCache[s] = v); decodeSlot(s, v); changed = true; }
  }
  return changed;
}
// MIDI CC → parameter, n = 0..1 across the control's whole range
function setParamN(i: i32, n: f32): void {
  const nn = clampf(n, 0.0, 1.0);
  const lo = unchecked(PMIN[i]);
  const hi = unchecked(PMAX[i]);
  if (unchecked(PDIRECT[i]) != 0) {
    unchecked(A[i] = lo + nn * (hi - lo));
    unchecked(An[i] = nn);
  } else {
    const steps = unchecked(PSTEPS[i]);
    let raw: i32 = i32(nearest<f32>(nn * f32(steps - 1)));
    if (raw < 0) raw = 0; if (raw > steps - 1) raw = steps - 1;
    unchecked(An[i] = steps > 1 ? f32(raw) / f32(steps - 1) : <f32>0.0);
    unchecked(A[i] = lo + f32(raw));
    unchecked(AI[i] = i32(lo) + raw);
  }
  paramsDirty = true;
}
function setParamI(i: i32, v: i32): void {
  const lo = i32(unchecked(PMIN[i]));
  const steps = unchecked(PSTEPS[i]);
  let raw = v - lo;
  if (raw < 0) raw = 0; if (raw > steps - 1) raw = steps - 1;
  unchecked(An[i] = steps > 1 ? f32(raw) / f32(steps - 1) : <f32>0.0);
  unchecked(A[i] = f32(lo + raw));
  unchecked(AI[i] = lo + raw);
  paramsDirty = true;
}
@inline function pv(i: i32): f32 { return unchecked(A[i]); }       // actual value
@inline function pn(i: i32): f32 { return unchecked(An[i]); }      // 0..1
@inline function pi(i: i32): i32 { return unchecked(AI[i]); }      // integer / list index

// ---- host transport / tempo ------------------------------------------------
let hostBpm: f32 = 0.0;
let hostPlaying: i32 = 0;
let hostPpq: f64 = 0.0;
let hostPpqFresh: bool = false;
function setHostTransport(playing: i32, ppq: f64, bpm: f32): void {
  hostBpm = bpm; hostPlaying = playing; hostPpq = ppq; hostPpqFresh = true;
}
@inline function hostTempo(): f32 {
  const t = unchecked(params[63]);
  return t > 1.0 ? t : (hostBpm > 1.0 ? hostBpm : <f32>0.0);
}

// ---- one-pole filters -------------------------------------------------------
class OnePole {
  z: f32 = 0;
  lp(x: f32, a: f32): f32 { this.z = denorm(this.z + a * (x - this.z)); return this.z; }
  hp(x: f32, a: f32): f32 { this.z = denorm(this.z + a * (x - this.z)); return x - this.z; }
}
@inline function onePoleA(fc: f32): f32 { return <f32>1.0 - Mathf.exp(-TWO_PI * clampf(fc, 0.01, SR * 0.45) * invSR); }
// zero-delay (trapezoidal) one-pole high-pass: exact at fc, used by the HIGH PASS filter
class Hp1 {
  s: f32 = 0;
  tick(x: f32, g: f32): f32 {
    const G = g / (<f32>1.0 + g);
    const v = (x - this.s) * G;
    const lp = v + this.s;
    this.s = denorm(lp + v);
    return x - lp;
  }
}


// =====================================================================
//  osc.ts — the two VCOs and the modulation oscillator.
//
//  GOsc renders triangle / saw / square / narrow-pulse in VOLTS (±5 V, AC
//  coupled like the hardware's WAVE OUT jacks). Every discontinuity — a natural
//  wrap, the pulse's falling edge, the triangle's corners and the hard-sync
//  reset of Oscillator 2 — is band-limited with a two-sample polyBLEP /
//  polyBLAMP residual applied to the current sample and the (delayed) previous
//  one, so nothing is double counted and sync stays alias-free. Output latency
//  is exactly one sample on both oscillators.
// =====================================================================

// ---- table sine ------------------------------------------------------------
const SIN_N: i32 = 4096;
const sinT = new StaticArray<f32>(SIN_N + 2);
function initSin(): void { for (let i = 0; i < SIN_N + 2; i++) sinT[i] = Mathf.sin(TWO_PI * f32(i) / f32(SIN_N)); }
@inline function fsin(ph: f32): f32 {           // ph in cycles, any value
  const p = ph - Mathf.floor(ph);
  const x = p * f32(SIN_N);
  const i = i32(x);
  const f = x - f32(i);
  const a = unchecked(sinT[i]);
  return a + (unchecked(sinT[i + 1]) - a) * f;
}

// polyBLEP residual for a unit-amplitude saw (t = phase 0..1, dt = phase increment)
@inline function polyblep(t: f32, dt: f32): f32 {
  if (t < dt) { const u = t / dt; return u + u - u * u - 1.0; }
  if (t > 1.0 - dt) { const u = (t - 1.0) / dt; return u * u + u + u + 1.0; }
  return 0.0;
}

const W_TRI: i32 = 0;
const W_SAW: i32 = 1;
const W_SQR: i32 = 2;
const W_NAR: i32 = 3;

// ---- band-limited step / ramp residual tables -----------------------------------------------------
//  A discontinuity of height J at time te adds J·STEP_RES(n - te) to every sample n within ±16 samples;
//  a slope change dS adds dS·RAMP_RES(n - te). STEP_RES / RAMP_RES are (band-limited step/ramp) minus
//  (ideal step/ramp): exactly what turns the naive waveform into the band-limited one. The band-limiting
//  kernel is a 32-tap Kaiser-windowed sinc (β = 7.5) with its cutoff at 0.43·fs: everything that could
//  fold back into the audible band is > 70 dB down. Tables: 32 taps × BL_P sub-sample phases, built once at init.
const BL_H: i32 = 16;                           // half width (samples)
const BL_T: i32 = 32;                           // taps per phase
const BL_P: i32 = 128;
const BL_LAT: i32 = 16;                         // output latency of the oscillators (samples)
const BL_RING: i32 = 64;
const blStep = new StaticArray<f32>((BL_P + 1) * BL_T);
const blRamp = new StaticArray<f32>((BL_P + 1) * BL_T);
function besselI0(x: f64): f64 {
  let sum: f64 = 1.0; let term: f64 = 1.0; const q: f64 = x * x * 0.25;
  for (let k = 1; k < 40; k++) { term = term * q / (<f64>k * <f64>k); sum += term; if (term < 1.0e-14 * sum) break; }
  return sum;
}
function initBlep(): void {
  const F: i32 = 128;                           // fine steps per sample
  const n: i32 = 2 * BL_H * F;                  // τ from -H .. +H
  const ws = new StaticArray<f64>(n + 1);
  const fcn: f64 = 0.43;                        // cutoff, cycles per sample
  const beta: f64 = 7.5;
  const i0b: f64 = besselI0(beta);
  let tot: f64 = 0.0;
  for (let i = 0; i <= n; i++) {
    const t: f64 = (<f64>i - <f64>(n / 2)) / <f64>F;
    const x: f64 = 2.0 * Math.PI * fcn * t;
    const sinc: f64 = t == 0.0 ? 1.0 : Math.sin(x) / x;
    let r: f64 = t / <f64>BL_H; r = 1.0 - r * r; if (r < 0.0) r = 0.0;
    const w: f64 = besselI0(beta * Math.sqrt(r)) / i0b;
    unchecked(ws[i] = sinc * w);
    tot += sinc * w;
  }
  tot = tot / <f64>F;                           // ∫ kernel (so the step ends at exactly 1)
  const st = new StaticArray<f64>(n + 1);       // band-limited step
  const rp = new StaticArray<f64>(n + 1);       // band-limited ramp
  let acc: f64 = 0.0; let acc2: f64 = 0.0;
  for (let i = 0; i <= n; i++) {
    if (i > 0) acc += 0.5 * (unchecked(ws[i]) + unchecked(ws[i - 1])) / (<f64>F * tot);
    unchecked(st[i] = acc);
    if (i > 0) acc2 += 0.5 * (unchecked(st[i]) + unchecked(st[i - 1])) / <f64>F;
    unchecked(rp[i] = acc2);
  }
  for (let ph = 0; ph <= BL_P; ph++) {
    const alpha: f64 = <f64>ph / <f64>BL_P;
    for (let j = 0; j < BL_T; j++) {
      const tau: f64 = alpha + <f64>(j - (BL_H - 1));        // sample offset from the edge
      let fi = (tau + <f64>BL_H) * <f64>F;
      let beyond: f64 = 0.0;                                   // past the kernel's support the ramp continues linearly
      if (fi < 0.0) fi = 0.0;
      if (fi > <f64>n) { beyond = (fi - <f64>n) / <f64>F; fi = <f64>n; }
      const i0: i32 = i32(fi); const fr: f64 = fi - <f64>i0;
      const i1: i32 = i0 < n ? i0 + 1 : i0;
      const sv: f64 = unchecked(st[i0]) * (1.0 - fr) + unchecked(st[i1]) * fr;
      const rv: f64 = unchecked(rp[i0]) * (1.0 - fr) + unchecked(rp[i1]) * fr + beyond;
      const hv: f64 = tau >= 0.0 ? 1.0 : 0.0;
      unchecked(blStep[ph * BL_T + j] = <f32>(sv - hv));
      unchecked(blRamp[ph * BL_T + j] = <f32>(rv - (tau >= 0.0 ? tau : 0.0)));
    }
  }
}

class GOsc {
  ph: f32 = 0;
  n: i32 = 0;                                   // running sample counter (ring index)
  hist: StaticArray<f32> = new StaticArray<f32>(BL_RING);
  acc: StaticArray<f32> = new StaticArray<f32>(BL_RING);
  wrapAlpha: f32 = -1;         // >=0 when the phase wrapped in the last sample (fraction elapsed since the wrap)

  // naive waveform in volts at phase p (pulse width / duty = d)
  naive(p: f32, wave: i32, d: f32): f32 {
    if (wave == W_TRI) return p < 0.5 ? <f32>20.0 * p - <f32>5.0 : <f32>15.0 - <f32>20.0 * p;
    if (wave == W_SAW) return <f32>10.0 * p - <f32>5.0;
    return p < d ? <f32>10.0 * (<f32>1.0 - d) : <f32>-10.0 * d;      // AC-coupled pulse
  }
  // add a band-limited step (J) or kink (dS per sample) whose edge occurred `alpha` of a sample before now
  @inline step(J: f32, alpha: f32): void { this.addTab(J, alpha, blStep); }
  @inline kink(dS: f32, inc: f32, alpha: f32): void { this.addTab(dS * inc, alpha, blRamp); }
  addTab(amp: f32, alpha: f32, tab: StaticArray<f32>): void {
    const x = alpha * <f32>BL_P;
    let i = i32(x);
    if (i >= BL_P) i = BL_P - 1;
    const fr = x - f32(i);
    const o0 = i * BL_T;
    const o1 = o0 + BL_T;
    const base = this.n - (BL_H - 1);
    for (let j = 0; j < BL_T; j++) {
      const r = unchecked(tab[o0 + j]) * (<f32>1.0 - fr) + unchecked(tab[o1 + j]) * fr;
      const idx = (base + j) & (BL_RING - 1);
      unchecked(this.acc[idx] = this.acc[idx] + amp * r);
    }
  }
  // syncAlpha < 0: free running. >= 0: the master wrapped in this sample and
  // `syncAlpha` is the fraction of the sample elapsed since that reset.
  sample(inc0: f32, wave: i32, d: f32, syncAlpha: f32): f32 {
    const inc = clampf(inc0, 1.0e-7, 0.45);
    const oldPh = this.ph;
    const pu = oldPh + inc;
    const sy = syncAlpha >= 0.0;
    let alphaW: f32 = -1.0;
    let wrapped = false;
    if (pu >= 1.0) { wrapped = true; alphaW = (pu - <f32>1.0) / inc; }
    // natural events on [oldPh, pu] — only those that precede the sync reset survive
    if (wave == W_SAW) {
      if (wrapped && (!sy || alphaW > syncAlpha)) this.step(-10.0, alphaW);
    } else if (wave == W_TRI) {
      if (wrapped && (!sy || alphaW > syncAlpha)) this.kink(40.0, inc, alphaW);
      if (oldPh < 0.5 && pu >= 0.5 && pu < 1.0) { const aH = (pu - <f32>0.5) / inc; if (!sy || aH > syncAlpha) this.kink(-40.0, inc, aH); }
    } else {
      if (wrapped && (!sy || alphaW > syncAlpha)) this.step(10.0, alphaW);
      if (oldPh < d && pu >= d && pu < 1.0) { const aP = (pu - d) / inc; if (!sy || aP > syncAlpha) this.step(-10.0, aP); }
    }
    let p = wrapped ? pu - <f32>1.0 : pu;
    if (sy) {
      let pr = oldPh + inc * (<f32>1.0 - syncAlpha);
      if (pr >= 1.0) pr -= 1.0;
      this.step(this.naive(0.0, wave, d) - this.naive(pr, wave, d), syncAlpha);
      if (wave == W_TRI) { const sb: f32 = pr < 0.5 ? <f32>20.0 : <f32>-20.0; this.kink(<f32>20.0 - sb, inc, syncAlpha); }
      p = inc * syncAlpha;
    }
    if (p >= 1.0) p -= 1.0;
    this.ph = p;
    this.wrapAlpha = (wrapped && !sy) ? alphaW : <f32>-1.0;
    // store the naive sample, emit the sample from BL_LAT samples ago with all its corrections applied
    unchecked(this.hist[this.n & (BL_RING - 1)] = this.naive(p, wave, d));
    const oi = (this.n - BL_LAT) & (BL_RING - 1);
    const emit = unchecked(this.hist[oi]) + unchecked(this.acc[oi]);
    unchecked(this.acc[oi] = 0.0);
    this.n = this.n + 1;
    return emit;
  }
  reset(): void {
    this.ph = 0; this.n = 0; this.wrapAlpha = -1;
    for (let i = 0; i < BL_RING; i++) { this.hist[i] = 0.0; this.acc[i] = 0.0; }
  }
}

// ---- the modulation oscillator -------------------------------------------------------
// WAVE OUT = ±5 V (DC coupled). Sine / sawtooth (rising) / ramp (falling) / square.
// S/H OUT samples the noise generator at the start of every wave cycle. The saw / ramp / square use
// the same band-limited core as the VCOs (the manual plays this oscillator at audio rate too).
class Lfo {
  o: GOsc = new GOsc();
  sh: f32 = 0;
  wrapped: bool = false;
  tick(inc0: f32, wave: i32): f32 {
    const inc = clampf(inc0, 1.0e-7, 0.45);
    const y = this.o.sample(inc, wave == 3 ? W_SQR : W_SAW, 0.5, -1.0);
    this.wrapped = this.o.wrapAlpha >= 0.0;
    if (this.wrapped) this.sh = white() * <f32>5.0;
    if (wave == 0) return <f32>5.0 * fsin(this.o.ph);
    if (wave == 2) return -y;
    return y;
  }
  get ph(): f32 { return this.o.ph; }
  syncReset(): void { this.o.ph = 0.0; this.sh = white() * <f32>5.0; }
  reset(): void { this.o.reset(); this.sh = 0; this.wrapped = false; }
}


// =====================================================================
//  mods.ts — the Moog ladder filter, the ADSR envelope, the VCA modes and the
//  spring reverb tank.
// =====================================================================

// ---- 4-pole Moog ladder (zero-delay feedback, saturating input stage) ------------------
//  Four trapezoidal one-pole low-passes in series with global resonance feedback.
//  The feedback loop is solved algebraically (no unit delay) so the cutoff — and the
//  self-oscillation pitch — is exact at every frequency; the transistor-pair
//  nonlinearity is a soft clip on the stage-1 input. Works in volts (±5 V nominal).
const FB_CLIP: f32 = 0.7;
class Ladder {
  s1: f32 = 0; s2: f32 = 0; s3: f32 = 0; s4: f32 = 0;
  y: f32 = 0;
  // g = tan(pi*fc/sr), k = resonance feedback 0..4.5 (self-oscillation from k = 4)
  tick(xv: f32, g: f32, k: f32): f32 {
    const G = g / (<f32>1.0 + g);
    const G2 = G * G;
    const Gm = <f32>1.0 - G;
    const S = Gm * (G2 * G * this.s1 + G2 * this.s2 + G * this.s3 + this.s4);
    // input stage: soft clip (slope 1 at the origin, ~1.15 ceiling) — the audio overdrive of the ladder
    const x = <f32>1.15 * softclip((xv * <f32>0.2 + white() * <f32>0.00002) * <f32>0.87);   // ±5 V → ±1, plus a trace of noise to start oscillation
    let u = (x - k * S) / (<f32>1.0 + k * G2 * G2);
    // the feedback path saturates like the transistor ladder's stages: re-evaluate the loop with the
    // linear prediction of the output clipped to ±FB_CLIP (transparent for small signals); this is what
    // sets the self-oscillation amplitude
    const y4p = G2 * G2 * u + S;
    if (y4p > FB_CLIP * <f32>0.6 || y4p < -FB_CLIP * <f32>0.6) u = x - k * FB_CLIP * softclip(y4p / FB_CLIP);
    const us = u;
    const v1 = G * (us - this.s1); const y1 = v1 + this.s1; this.s1 = denorm(y1 + v1);
    const v2 = G * (y1 - this.s2); const y2 = v2 + this.s2; this.s2 = denorm(y2 + v2);
    const v3 = G * (y2 - this.s3); const y3 = v3 + this.s3; this.s3 = denorm(y3 + v3);
    const v4 = G * (y3 - this.s4); const y4 = v4 + this.s4; this.s4 = denorm(y4 + v4);
    this.y = y4;
    return y4 * <f32>5.0;
  }
  reset(): void { this.s1 = 0; this.s2 = 0; this.s3 = 0; this.s4 = 0; this.y = 0; }
}

// ---- the ADSR ------------------------------------------------------------------------
//  Analog-style exponential segments (RC charge/discharge). Output level 0..1 (×8 V).
//  The attack aims at 1.2 so it reaches the top in the set time and then hands over to
//  the decay, like a real ADSR chip; it always starts from the CURRENT level.
const E_IDLE: i32 = 0;
const E_ATK: i32 = 1;
const E_DEC: i32 = 2;
const E_SUS: i32 = 3;
const E_REL: i32 = 4;
class Env {
  lvl: f32 = 0;
  stage: i32 = 0;
  gate: bool = false;
  // times in seconds, s = sustain level 0..1
  tick(g: bool, aT: f32, dT: f32, s: f32, rT: f32): f32 {
    if (g && !this.gate) this.stage = E_ATK;
    if (!g && this.gate && this.stage != E_IDLE) this.stage = E_REL;
    this.gate = g;
    const st = this.stage;
    if (st == E_ATK) {
      this.lvl += (<f32>1.2 - this.lvl) * (<f32>1.0 - Mathf.exp(-<f32>1.7917595 * invSR / aT));
      if (this.lvl >= 1.0) { this.lvl = 1.0; this.stage = E_DEC; }
    } else if (st == E_DEC) {
      this.lvl += (s - <f32>0.002 - this.lvl) * (<f32>1.0 - Mathf.exp(-<f32>4.6 * invSR / dT));
      if (this.lvl <= s + <f32>0.0005) { this.lvl = s; this.stage = E_SUS; }
    } else if (st == E_SUS) {
      this.lvl += (s - this.lvl) * <f32>0.01;                   // follows the SUSTAIN slider smoothly
    } else if (st == E_REL) {
      this.lvl += (<f32>-0.002 - this.lvl) * (<f32>1.0 - Mathf.exp(-<f32>4.6 * invSR / rT));
      if (this.lvl <= 0.0) { this.lvl = 0.0; this.stage = E_IDLE; }
    }
    this.lvl = denorm(this.lvl);
    return this.lvl;
  }
  reset(): void { this.lvl = 0; this.stage = E_IDLE; this.gate = false; }
}

// ---- the spring reverb tank ---------------------------------------------------------
//  Two parallel springs. Each is a feedback loop of: delay (the round trip of the spring)
//  → a long cascade of first-order all-pass sections with a NEGATIVE coefficient
//  (low frequencies are held back longer than highs — the dispersion that makes a spring
//  "boing" and chirp) → loss low-pass → loop gain. Input and output are band-limited like
//  a real tank transducer pair (~120 Hz … 5 kHz).
const SPR_BUF: i32 = 16384;
const SPR_STAGES_MAX: i32 = 256;
class Ap1 {
  z: f32 = 0;
  @inline tick(x: f32, a: f32): f32 { const y = a * x + this.z; this.z = x - a * y; return y; }
}
class Spring {
  buf: StaticArray<f32> = new StaticArray<f32>(SPR_BUF);
  ap: StaticArray<f32> = new StaticArray<f32>(SPR_STAGES_MAX);
  w: i32 = 0;
  d: i32 = 1000;
  nst: i32 = 32;
  g: f32 = 0.88;
  a: f32 = -0.65;
  lp: f32 = 0;
  lpA: f32 = 0.5;
  dc: f32 = 0;
  setup(delaySec: f32, t60: f32, stages: f32, ap: f32, lossHz: f32): void {
    this.d = clampi(i32(delaySec * SR), 16, SPR_BUF - 2);
    this.nst = clampi(i32(stages * SR / <f32>48000.0 + <f32>0.5), 8, SPR_STAGES_MAX);
    this.g = Mathf.pow(<f32>10.0, -<f32>3.0 * delaySec / t60);
    this.a = ap;
    this.lpA = onePoleA(lossHz);
  }
  @inline tick(x: f32): f32 {
    const rd = (this.w - this.d) & (SPR_BUF - 1);
    const yd = unchecked(this.buf[rd]);
    let v = yd;
    const a = this.a;
    for (let i = 0; i < this.nst; i++) {
      const z = unchecked(this.ap[i]);
      const y = a * v + z;
      unchecked(this.ap[i] = denorm(v - a * y));
      v = y;
    }
    this.lp = denorm(this.lp + this.lpA * (v - this.lp));
    // remove DC from the loop so offsets can't pile up
    this.dc = denorm(this.dc + <f32>0.0006 * (this.lp - this.dc));
    unchecked(this.buf[this.w] = x + this.g * (this.lp - this.dc));
    this.w = (this.w + 1) & (SPR_BUF - 1);
    return yd;
  }
  reset(): void {
    for (let i = 0; i < SPR_BUF; i++) unchecked(this.buf[i] = 0.0);
    for (let i = 0; i < SPR_STAGES_MAX; i++) unchecked(this.ap[i] = 0.0);
    this.w = 0; this.lp = 0; this.dc = 0;
  }
}
@inline function clampi(x: i32, lo: i32, hi: i32): i32 { return x < lo ? lo : (x > hi ? hi : x); }

class SpringTank {
  s1: Spring = new Spring();
  s2: Spring = new Spring();
  inHp: OnePole = new OnePole(); inLp: OnePole = new OnePole();
  outHp: OnePole = new OnePole(); outLp: OnePole = new OnePole();
  aInHp: f32 = 0.01; aInLp: f32 = 0.4; aOutHp: f32 = 0.02; aOutLp: f32 = 0.4;
  setup(): void {
    this.s1.setup(0.0416, 2.3, 60.0, -0.80, 3400.0);
    this.s2.setup(0.0567, 2.0, 48.0, -0.78, 3000.0);
    this.aInHp = onePoleA(110.0); this.aInLp = onePoleA(5200.0);
    this.aOutHp = onePoleA(90.0); this.aOutLp = onePoleA(4800.0);
  }
  // x: audio in volts/5 (±1 nominal) → wet out (±1 nominal)
  tick(x: f32): f32 {
    let v = this.inHp.hp(x, this.aInHp);
    v = this.inLp.lp(v, this.aInLp);
    v = softclip(v * <f32>0.9) * <f32>1.05;                    // transducer overload
    const o = (this.s1.tick(v * <f32>0.5) + this.s2.tick(v * <f32>0.5)) * <f32>1.9;
    return this.outLp.lp(this.outHp.hp(o, this.aOutHp), this.aOutLp);
  }
  reset(): void { this.s1.reset(); this.s2.reset(); this.inHp.z = 0; this.inLp.z = 0; this.outHp.z = 0; this.outLp.z = 0; }
}

// ---- 2x oversampling for the nonlinear stages (mixer overdrive + ladder) ------------------------------
//  47-tap Kaiser half-band filters (β = 7): the upsampler interpolates the odd phase, the decimator
//  low-passes the 2x signal before dropping every other sample. Latency: HB_M samples each way.
const HB_M: i32 = 12;
const hbH = new StaticArray<f32>(HB_M);          // h[2k+1], k = 0 .. HB_M-1 (centre tap h[0] = 0.5)
function initHalfband(): void {
  const beta: f64 = 7.0; const i0b: f64 = besselI0(beta);
  let sum: f64 = 0.5;
  const tmp = new StaticArray<f64>(HB_M);
  for (let k = 0; k < HB_M; k++) {
    const j: f64 = <f64>(2 * k + 1);
    const sgn: f64 = (k & 1) == 0 ? 1.0 : -1.0;
    let r: f64 = j / <f64>(2 * HB_M); r = 1.0 - r * r; if (r < 0.0) r = 0.0;
    const w: f64 = besselI0(beta * Math.sqrt(r)) / i0b;
    tmp[k] = sgn / (Math.PI * j) * w;
    sum += 2.0 * tmp[k];
  }
  for (let k = 0; k < HB_M; k++) hbH[k] = <f32>(tmp[k] / sum);          // unity DC gain
}
class HbUp {
  buf: StaticArray<f32> = new StaticArray<f32>(64);
  n: i32 = 0;
  e: f32 = 0; o: f32 = 0;                         // the two 2x samples that belong to the base sample delayed by HB_M
  push(x: f32): void {
    unchecked(this.buf[this.n & 63] = x); this.n++;
    const c = this.n - 1 - HB_M;
    let acc: f32 = 0.0;
    for (let k = 0; k < HB_M; k++) acc += unchecked(hbH[k]) * (unchecked(this.buf[(c - k) & 63]) + unchecked(this.buf[(c + 1 + k) & 63]));
    this.o = <f32>2.0 * acc;
    this.e = unchecked(this.buf[c & 63]);
  }
  reset(): void { for (let i = 0; i < 64; i++) this.buf[i] = 0.0; this.n = 0; this.e = 0.0; this.o = 0.0; }
}
class HbDown {
  buf: StaticArray<f32> = new StaticArray<f32>(128);
  n: i32 = 0;
  y: f32 = 0;
  // a = first (even-phase) 2x sample, b = second (odd-phase) 2x sample of the same base-rate frame → one output sample
  push(a: f32, b: f32): f32 {
    unchecked(this.buf[this.n & 127] = a); unchecked(this.buf[(this.n + 1) & 127] = b); this.n += 2;
    const c = this.n - 2 * HB_M;
    let acc: f32 = <f32>0.5 * unchecked(this.buf[c & 127]);
    for (let k = 0; k < HB_M; k++) acc += unchecked(hbH[k]) * (unchecked(this.buf[(c - 1 - 2 * k) & 127]) + unchecked(this.buf[(c + 1 + 2 * k) & 127]));
    this.y = acc; return acc;
  }
  reset(): void { for (let i = 0; i < 128; i++) this.buf[i] = 0.0; this.n = 0; this.y = 0.0; }
}


// =====================================================================
//  keys.ts — the monophonic keyboard (LOW / HIGH / LAST priority, single trigger
//  legato), glide (LCR / LCT / exponential, legato + gated), the arpeggiator
//  (ORDR / FWD-BKWD / RNDM, 1-3 octaves, HOLD latch), the 3 × 256-step sequencer
//  (REC with REST / TIE / ACCENT, live overwrite, key transposition), and the
//  clock (internal BPM / tap tempo / host tempo with the 24 note divisions /
//  external CLOCK IN in Clock or Step-Advance mode, RESET IN, ON/OFF IN, CLOCK OUT).
// =====================================================================

const HMAX: i32 = 64;
const SEQ_N: i32 = 256;
const F_TIE: i32 = 1;
const F_ACC: i32 = 2;

// ---- held-key list (press order) ---------------------------------------------------------
const hId = new StaticArray<i32>(HMAX);
const hNote = new StaticArray<i32>(HMAX);
const hVel = new StaticArray<f32>(HMAX);
const hDown = new StaticArray<i32>(HMAX);
let hN: i32 = 0;

// ---- sequencer memory --------------------------------------------------------------------
const seqNote = new StaticArray<i32>(3 * SEQ_N);   // MIDI note, -1 = rest
const seqFlag = new StaticArray<i32>(3 * SEQ_N);
const seqLen = new StaticArray<i32>(3);
let recArmed: bool = true;
let recPendingTie: bool = false;
let recLast: i32 = -1;
let lastMode: i32 = 0;
let lastSeqSel: i32 = 0;

// ---- keyboard / output state --------------------------------------------------------------
let kTarget: f32 = 60.0;           // note the pitch glides toward (semitones, MIDI)
let kCur: f32 = 60.0;              // glided pitch
let kGlideOk: bool = true;
let kLctRate: f32 = 0.0;
let kVel: f32 = 0.8;
let kGateWant: bool = false;
let kGateOut: bool = false;
let kLowT: f32 = 1.0;              // seconds the gate has been low (guarantees a re-trigger gap)
let kAccent: f32 = 0.0;            // accent envelope 0..1
let kAccentSeq: bool = false;      // true while the sequencer drives KB VEL OUT

// ---- run / clock state -------------------------------------------------------------------
let kRunArp: bool = false;
let kRunSeq: bool = false;
let kPhase: f32 = 1.0;
let kGateOffT: f32 = 0.0;
let kGateOffArm: bool = false;
let kArpPos: i32 = 0;
let kSeqPos: i32 = 0;
let kSeqCur: i32 = 0;              // step index currently sounding
let kSeqKey: i32 = -1;             // note of the transposing key
let kStepCount: i32 = 0;
let kStepSec: f32 = 0.25;
let kPulseCnt: i32 = 0;
let kLastClkPrev: f32 = 0.0;
let kClkTimer: f32 = 0.0;
let kClkPeriod: f32 = 0.0;
let kOnoffPrev: bool = false;
let kResetPrev: bool = false;
let kHostIdx: i64 = -1;
let kPpqAcc: f64 = 0.0;
let kClkOutPh: f32 = 0.0;
let kClkOut: f32 = 0.0;
let kStepFlash: f32 = 0.0;
let kLastBend: f32 = 0.0;

function clearKeys(): void { hN = 0; }
function hFind(id: i32): i32 { for (let i = 0; i < hN; i++) if (hId[i] == id) return i; return -1; }
function hRemoveAt(i: i32): void {
  for (let j = i; j < hN - 1; j++) { hId[j] = hId[j + 1]; hNote[j] = hNote[j + 1]; hVel[j] = hVel[j + 1]; hDown[j] = hDown[j + 1]; }
  hN--;
}
function physDown(): i32 { let c = 0; for (let i = 0; i < hN; i++) if (hDown[i] != 0) c++; return c; }
@inline function sel(d: i32): i32 { return unchecked(SEL[d]); }
@inline function patched(d: i32): bool { return unchecked(SEL[d]) != 0; }

function playOn(): bool {
  if (patched(D_ONOFF_IN)) return unchecked(S[unchecked(SEL[D_ONOFF_IN])]) > 2.5;
  return pi(P_PLAY) != 0;
}
function holdOn(): bool { return pi(P_HOLD) != 0; }

// ---- sequencer helpers ---------------------------------------------------------------------
function seqSel(): i32 { return pi(P_OCT_SEQ); }
function seqRoot(s: i32): i32 {
  for (let i = 0; i < seqLen[s]; i++) if (seqNote[s * SEQ_N + i] >= 0) return seqNote[s * SEQ_N + i];
  return 60;
}
function seqClear(s: i32): void { seqLen[s] = 0; }

// ---- pitch target / gate --------------------------------------------------------------------
function setTarget(note: i32, vel: f32, legatoHint: bool): void {
  const legatoOnly = pi(P_GL_LEGATO) != 0;
  kGlideOk = !legatoOnly || (kGateOut && legatoHint);
  kTarget = f32(note);
  if (pi(P_GL_TYPE) == 1) {
    const gx = pv(P_GLIDE);
    const t: f32 = <f32>0.01 * Mathf.pow(<f32>600.0, clampf((gx - <f32>0.01) * <f32>1.0101, 0.0, 1.0));
    kLctRate = absf(kTarget - kCur) / t;
  }
  kVel = vel;
}
function dropGate(): void { kGateWant = false; kGateOffArm = false; }

// resolve what the plain keyboard is playing (no arp / seq running)
function keyboardUpdate(newKey: bool): void {
  const pri = pi(P_NOTE_PRI);
  let best: i32 = -1;
  for (let i = 0; i < hN; i++) {
    if (hDown[i] == 0) continue;
    if (best < 0) { best = i; continue; }
    if (pri == 0) { if (hNote[i] < hNote[best]) best = i; }
    else if (pri == 1) { if (hNote[i] > hNote[best]) best = i; }
    else best = i;                        // LAST: the most recent entry wins
  }
  if (best < 0) { dropGate(); return; }
  const wasHigh = kGateWant || kGateOut;
  if (newKey || hNote[best] != i32(kTarget) || !wasHigh) setTarget(hNote[best], hVel[best], wasHigh);
  kGateWant = true; kGateOffArm = false;
}

// ---- arpeggiator step ------------------------------------------------------------------------
function arpPick(): i32 {
  const cnt = hN;
  if (cnt <= 0) return 60;
  const oct = pi(P_OCT_SEQ) + 1;
  const n = cnt * oct;
  const dir = pi(P_ARP_DIR);
  let idx: i32 = 0;
  if (dir == 0) { idx = kArpPos % n; }
  else if (dir == 1) {
    if (n <= 1) idx = 0;
    else { const per = 2 * n - 2; const p = kArpPos % per; idx = p < n ? p : per - p; }
  } else { idx = i32(rand01() * f32(n)); if (idx >= n) idx = n - 1; }
  kArpPos++;
  const ni = idx % cnt;
  kVel = hVel[ni];
  return hNote[ni] + 12 * (idx / cnt);
}

// next sequence position (peek or commit) ---------------------------------------------------------
function seqAdvance(s: i32, pos: i32): i32 {          // returns the step index for counter value `pos`
  const len = seqLen[s];
  if (len <= 0) return 0;
  const dir = pi(P_ARP_DIR);
  if (dir == 0) return pos % len;
  if (dir == 1) { if (len <= 1) return 0; const per = 2 * len - 2; const p = pos % per; return p < len ? p : per - p; }
  return -1;                                             // random: decided at the step
}

function doStep(dt: f32): void {
  kStepFlash = 1.0;
  const gl: f32 = kStepSec * <f32>0.5;
  if (kRunArp) {
    const note = arpPick();
    setTarget(note, kVel, kGateOut);
    kAccentSeq = false;
    kGateWant = true; kGateOffArm = true; kGateOffT = gl;
    return;
  }
  if (!kRunSeq) return;
  const s = seqSel();
  const len = seqLen[s];
  if (len <= 0) { dropGate(); return; }
  let idx = seqAdvance(s, kSeqPos);
  if (idx < 0) { idx = i32(rand01() * f32(len)); if (idx >= len) idx = len - 1; }
  kSeqPos++;
  kSeqCur = idx;
  const note = seqNote[s * SEQ_N + idx];
  const fl = seqFlag[s * SEQ_N + idx];
  kAccentSeq = true;
  if (note < 0) { dropGate(); return; }                 // REST
  const tr = pi(P_ARP_MODE) == 2 ? 0 : (kSeqKey >= 0 ? kSeqKey - seqRoot(s) : 0);
  const legato = (fl & F_TIE) != 0 && kGateWant;
  setTarget(note + tr, 0.8, legato);
  kGateWant = true;
  if ((fl & F_ACC) != 0) kAccent = 1.0;
  // does the next step continue this gate (tie)?
  let tied = false;
  const nxt = seqAdvance(s, kSeqPos);
  if (nxt >= 0 && nxt < len) { if ((seqFlag[s * SEQ_N + nxt] & F_TIE) != 0 && seqNote[s * SEQ_N + nxt] >= 0) tied = true; }
  if (tied) kGateOffArm = false; else { kGateOffArm = true; kGateOffT = gl; }
}

// ---- run-state management -----------------------------------------------------------------------
function startRun(): void {
  kPhase = 1.0; kArpPos = 0; kSeqPos = 0; kPulseCnt = 0; kStepCount = 0; kHostIdx = -1;
}
function updateRun(newKey: bool): void {
  const mode = pi(P_ARP_MODE);
  const po = playOn();
  const oo = patched(D_ONOFF_IN);
  const wantArp = mode == 0 && po && hN > 0;
  const wantSeq = po && ((mode == 1 && (hN > 0 || oo)) || (mode == 2 && kRunSeq));
  if (wantArp && !kRunArp) startRun();
  if (wantSeq && !kRunSeq) startRun();
  if ((kRunArp && !wantArp) || (kRunSeq && !wantSeq)) {
    kGateWant = false; kGateOffArm = false; kAccentSeq = false;
    kRunArp = false; kRunSeq = false;
  }
  kRunArp = wantArp; kRunSeq = wantSeq;
  if (wantSeq && hN > 0) kSeqKey = hNote[hN - 1];
  if (!wantArp && !wantSeq) keyboardUpdate(newKey);
}

function modeWatch(): void {
  const mode = pi(P_ARP_MODE);
  const s = seqSel();
  if (mode != lastMode || s != lastSeqSel) {
    if (mode == 2 && (lastMode != 2 || s != lastSeqSel)) { recArmed = true; recPendingTie = false; recLast = -1; }
    lastMode = mode; lastSeqSel = s;
  }
}

// ---- key events -----------------------------------------------------------------------------------
function recordKey(note: i32, vel: f32, legato: bool): void {
  const s = seqSel();
  if (kRunSeq) {                                          // live overwrite of the step that is sounding
    const i = kSeqCur;
    if (i >= 0 && i < seqLen[s]) { seqNote[s * SEQ_N + i] = note; seqFlag[s * SEQ_N + i] = recPendingTie ? F_TIE : 0; }
    recPendingTie = false;
    return;
  }
  if (recArmed) { seqClear(s); recArmed = false; }
  if (seqLen[s] < SEQ_N) {
    const i = seqLen[s];
    seqNote[s * SEQ_N + i] = note;
    seqFlag[s * SEQ_N + i] = (recPendingTie || legato) ? F_TIE : 0;
    seqLen[s] = i + 1; recLast = i;
  }
  recPendingTie = false;
}
function recordMarker(kind: i32): void {                  // 0 rest, 1 tie, 2 accent
  const s = seqSel();
  if (kind == 1) {
    if (kRunSeq) { const i = kSeqCur; if (i >= 0 && i < seqLen[s]) seqFlag[s * SEQ_N + i] |= F_TIE; }
    else recPendingTie = true;
    return;
  }
  if (kind == 2) {
    const i = kRunSeq ? kSeqCur : recLast;
    if (i >= 0 && i < seqLen[s]) seqFlag[s * SEQ_N + i] |= F_ACC;
    return;
  }
  if (kRunSeq) { const i = kSeqCur; if (i >= 0 && i < seqLen[s]) { seqNote[s * SEQ_N + i] = -1; seqFlag[s * SEQ_N + i] = 0; } return; }
  if (recArmed) { seqClear(s); recArmed = false; }
  if (seqLen[s] < SEQ_N) {
    const i = seqLen[s];
    seqNote[s * SEQ_N + i] = -1; seqFlag[s * SEQ_N + i] = 0; seqLen[s] = i + 1; recLast = i;
  }
  recPendingTie = false;
}

function keyOn(id: i32, note: i32, vel: f32): void {
  modeWatch();
  const mode = pi(P_ARP_MODE);
  const po = playOn();
  const wasDown = physDown();
  // a new pattern starts when every finger was up and the old notes were only latched
  if (wasDown == 0 && holdOn() && po) hN = 0;
  const f = hFind(id);
  if (f >= 0) hRemoveAt(f);
  if (hN >= HMAX) hRemoveAt(0);
  hId[hN] = id; hNote[hN] = note; hVel[hN] = vel; hDown[hN] = 1; hN++;
  if (mode == 2) recordKey(note, vel, wasDown > 0);
  updateRun(true);
  if (kRunSeq && hN > 0) kSeqKey = note;
}
function keyOff(id: i32): void {
  const f = hFind(id);
  if (f < 0) return;
  if (holdOn() && playOn()) hDown[f] = 0; else hRemoveAt(f);
  updateRun(false);
}
function allNotesOff(): void {
  hN = 0; kGateWant = false; kGateOffArm = false; kRunArp = false; kRunSeq = false; kAccentSeq = false;
}

// ---- the clock ---------------------------------------------------------------------------------------
@inline function divQ(i: i32): f32 { return unchecked(CLOCK_DIV[i]); }
function bpmNow(): f32 {
  const tap = pi(P_TAP_BPM);
  if (tap > 0) return f32(clampi(tap, 20, 280));
  return <f32>20.0 + <f32>260.0 * pv(P_ARP_RATE);
}
function stepSeconds(): f32 {
  if (pi(P_CLK_SRC) == 1) {
    const hb = hostTempo();
    if (hb > 1.0) {
      let idx = i32(pn(P_ARP_RATE) * <f32>23.999);
      if (idx > 23) idx = 23;
      return divQ(idx) * <f32>60.0 / hb;
    }
  }
  return <f32>30.0 / bpmNow();              // one step = an eighth note at the BPM
}
@inline function ppqnVal(i: i32): i32 { return unchecked(PPQN_V[i]); }

// advance the clock by one sample; returns true on a step event
function clockTick(dt: f32): bool {
  let ev = false;
  const run = kRunArp || kRunSeq;
  // CLOCK IN edge (pulse > 2.5 V)
  const ci = patched(D_CLK_IN);
  let clkNow: f32 = 0.0;
  if (ci) clkNow = unchecked(S[unchecked(SEL[D_CLK_IN])]);
  const rise = ci && clkNow > 2.5 && kLastClkPrev <= 2.5;
  kLastClkPrev = clkNow;
  kClkTimer += dt;
  if (ci) {
    if (rise) {
      if (kClkTimer > 0.0005) kClkPeriod = kClkTimer;
      kClkTimer = 0.0;
      if (run) {
        const stepMode = pi(P_EXT_MODE) == 1;
        let per = stepMode ? 1 : ppqnVal(pi(P_EXT_PPQN)) / 2;
        if (per < 1) per = 1;
        kPulseCnt++;
        if (kPulseCnt >= per) { kPulseCnt = 0; ev = true; }
        kStepSec = (stepMode ? kClkPeriod : kClkPeriod * f32(per));
        if (kStepSec < 0.001) kStepSec = 0.001;
      }
    }
    kPhase = 0.0;
  } else {
    kStepSec = stepSeconds();
    const host = pi(P_CLK_SRC) == 1 && hostTempo() > 1.0 && hostPlaying != 0;
    if (host) {
      if (run) {
        let idx2 = i32(pn(P_ARP_RATE) * <f32>23.999); if (idx2 > 23) idx2 = 23;
        const q = <f64>divQ(idx2);
        const hi: i64 = i64(Math.floor(kPpqAcc / q));
        if (kHostIdx < 0) kHostIdx = hi;                 // first step lands on the next grid line
        else if (hi != kHostIdx) { kHostIdx = hi; ev = true; }
      } else kHostIdx = -1;
      kPhase = 0.0;
    } else {
      kHostIdx = -1;
      if (run) { kPhase += dt / kStepSec; if (kPhase >= 1.0) { kPhase -= 1.0; if (kPhase > 1.0) kPhase = 0.0; ev = true; } }
    }
  }
  return ev;
}

// ---- per-sample tick ------------------------------------------------------------------------------------
function keysTick(dt: f32): void {
  modeWatch();
  // external play / reset jacks
  const oo = patched(D_ONOFF_IN);
  if (oo) {
    const on = unchecked(S[unchecked(SEL[D_ONOFF_IN])]) > 2.5;
    if (on != kOnoffPrev) { kOnoffPrev = on; updateRun(false); }
  } else kOnoffPrev = false;
  if (patched(D_RESET_IN)) {
    const r = unchecked(S[unchecked(SEL[D_RESET_IN])]) > 2.5;
    if (r && !kResetPrev) { kArpPos = 0; kSeqPos = 0; kPulseCnt = 0; kPhase = 1.0; }
    kResetPrev = r;
  } else kResetPrev = false;

  if (clockTick(dt)) doStep(dt);
  if (kHostIdx == -1 && !(kRunArp || kRunSeq)) kPhase = 1.0;

  // gate-length timer
  if (kGateOffArm) { kGateOffT -= dt; if (kGateOffT <= 0.0) { kGateWant = false; kGateOffArm = false; } }
  // gate output with a 1 ms re-trigger gap
  if (kGateWant) {
    if (!kGateOut) { if (kLowT >= 0.001) { kGateOut = true; } else kLowT += dt; }
  } else { if (kGateOut) kLowT = 0.0; else if (kLowT < 1.0) kLowT += dt; kGateOut = false; }

  // accent envelope (fast attack, short release) — drives KB VEL OUT during sequencer playback
  if (kAccent > 0.0) { kAccent -= dt / <f32>0.12; if (kAccent < 0.0) kAccent = 0.0; }
  if (kStepFlash > 0.0) { kStepFlash -= dt * 12.0; if (kStepFlash < 0.0) kStepFlash = 0.0; }

  // glide
  const gx = pv(P_GLIDE);
  const diff = kTarget - kCur;
  if (gx < 0.01 || !kGlideOk || (pi(P_GL_GATED) != 0 && !kGateOut)) kCur = kTarget;
  else {
    const t: f32 = <f32>0.01 * Mathf.pow(<f32>600.0, clampf((gx - <f32>0.01) * <f32>1.0101, 0.0, 1.0));
    const ty = pi(P_GL_TYPE);
    if (ty == 0) { const st = <f32>12.0 * dt / t; kCur = absf(diff) <= st ? kTarget : kCur + (diff > 0.0 ? st : -st); }
    else if (ty == 1) { const st = kLctRate * dt; kCur = absf(diff) <= st ? kTarget : kCur + (diff > 0.0 ? st : -st); }
    else kCur += diff * (<f32>1.0 - Mathf.exp(-<f32>4.6 * dt / t));
  }

  // CLOCK OUT: pulse train at the output PPQN while the arp / sequencer runs
  if (kRunArp || kRunSeq) {
    const stepPer = patched(D_CLK_IN) ? kStepSec : kStepSec;
    const pps = f32(ppqnVal(pi(P_OUT_PPQN))) * <f32>0.5;          // pulses per step (a step is an eighth note)
    kClkOutPh += dt * pps / stepPer;
    if (kClkOutPh >= 1.0) kClkOutPh -= Mathf.floor(kClkOutPh);
    kClkOut = kClkOutPh < 0.5 ? <f32>5.0 : <f32>0.0;
  } else { kClkOutPh = 0.0; kClkOut = 0.0; }
}


// =====================================================================
//  main.ts — KGrbdPa engine glue: the patch-bay evaluator (every jack carries
//  volts; each input jack reads the output cabled to it, or its normalled
//  connection), the per-sample signal chain
//      keyboard / arp / seq → mod LFO → envelope → VCO 1 / VCO 2 (sync, lin FM)
//      → mixer → ladder → VCA → spring reverb → volume
//  plus utilities (HP filter, bipolar attenuator, mult), MIDI CC map and the ABI
//  exports (see src/WasmAbi.h).
//
//  Evaluation order is fixed; an input that is cabled to a module evaluated LATER
//  in the same sample sees that module's previous sample (one-sample delay), so any
//  feedback patch is stable and deterministic.
// =====================================================================

const S = new StaticArray<f32>(NSRC + 1);
const SEL = new StaticArray<i32>(NDST);
@inline function inp(d: i32, dflt: f32): f32 {
  const s = unchecked(SEL[d]);
  return s == 0 ? dflt : unchecked(S[s]);
}

const osc1 = new GOsc();
const osc2 = new GOsc();
const lfo = new Lfo();
const env = new Env();
const lad = new Ladder();
const hpf = new Hp1();
const dcF = new Hp1();                      // the FILTER OUT / EURORACK OUT jacks are AC coupled (manual p.40-42)
const dcE = new Hp1();
let dcG: f32 = 0.0005;
const tank = new SpringTank();
const upA = new HbUp(); const upB = new HbUp(); const upX = new HbUp(); const upN = new HbUp(); const upF = new HbUp();
const dnM = new HbDown(); const dnF = new HbDown();

// derived / smoothed controls ---------------------------------------------------------------
let smCut: f32 = 5.0; let tCut: f32 = 5.0;
let smRes: f32 = 0.0; let tRes: f32 = 0.0;
let smO1: f32 = 0.0; let tO1: f32 = 0.0;
let smO2: f32 = 0.0; let tO2: f32 = 0.0;
let smNz: f32 = 0.0; let tNz: f32 = 0.0;
let smVol: f32 = 0.0; let tVol: f32 = 0.0;
let smRev: f32 = 0.0; let tRev: f32 = 0.0;
let smO2F: f32 = 0.0; let tO2F: f32 = 0.0;
let smEnvAmt: f32 = 0.0; let tEnvAmt: f32 = 0.0;
let smAtt: f32 = 0.0; let tAtt: f32 = 0.0;
let smCoef: f32 = 0.01;
let envA: f32 = 0.01; let envD: f32 = 0.1; let envS: f32 = 0.5; let envR: f32 = 0.1;
let lfoBaseOct: f32 = 0.0;
let hpG: f32 = 0.01;
let kbrGain: f32 = 0.0;
let kbrCoef: f32 = 0.999;
let drift1: f32 = 0.0; let drift2: f32 = 0.0;
let driftA: f32 = 0.0; let driftScale: f32 = 0.0;
let lfoSyncPrev: bool = false;
let ccBend: f32 = 0.0;
let glideEnabled: bool = true;
let rpnSel: i32 = 16383;
let rpnMsb: i32 = 127; let rpnLsb: i32 = 127;
const ccMsb = new StaticArray<i32>(128);
let peakOut: f32 = 0.0;
let lastEnv: f32 = 0.0;
let lastCutHz: f32 = 0.0;
const ENV_OCT: f32 = 7.0;                  // full ENVELOPE AMT sweeps 7 octaves of cutoff
const FM_HZ_PER_V: f32 = 120.0;            // OSC 2 LIN FM IN sensitivity

export function transport(playing: i32, ppq: f64, bpm: f32): void { setHostTransport(playing, ppq, bpm); kPpqAcc = ppq; }
export function getInputPtr(): usize  { return changetype<usize>(inBuf); }
export function getOutputPtr(): usize { return changetype<usize>(outBuf); }
export function getParamsPtr(): usize { return changetype<usize>(params); }
export function getNumParams(): i32   { return NUM_PARAMS; }
export function getDisplayPtr(): usize { return changetype<usize>(display); }
// test/diagnostic: decoded actual value of logical parameter i
export function paramValue(i: i32): f32 { return i >= 0 && i < NP ? A[i] : <f32>0.0; }
// test/diagnostic: sequencer memory + a few internals
export function dbgSeqLen(s: i32): i32 { return seqLen[s]; }
export function dbgSeqNote(s: i32, i: i32): i32 { return seqNote[s * SEQ_N + i]; }
export function dbgSeqFlag(s: i32, i: i32): i32 { return seqFlag[s * SEQ_N + i]; }
export function dbgSrc(i: i32): f32 { return S[i]; }
export function dbgState(i: i32): f32 {
  if (i == 0) return kRunArp ? <f32>1.0 : <f32>0.0;
  if (i == 1) return kRunSeq ? <f32>1.0 : <f32>0.0;
  if (i == 2) return f32(kSeqCur);
  if (i == 3) return kCur;
  if (i == 4) return f32(hN);
  if (i == 5) return kStepSec;
  if (i == 6) return kGateOut ? <f32>1.0 : <f32>0.0;
  if (i == 7) return lastCutHz;
  if (i == 8) return recArmed ? <f32>1.0 : <f32>0.0;
  return 0.0;
}

// ---------------------------------------------------------------------------- init
export function init(sr: f32, maxFrames: i32, numChannels: i32): void {
  SR = sr > 0.0 ? sr : <f32>48000.0; invSR = <f32>1.0 / SR;
  rng = 0x9e3779b9;
  initSin(); initBlep(); initHalfband();
  for (let i = 0; i < MAX_PARAMS; i++) { params[i] = 0.0; slotCache[i] = -1.0; }
  for (let i = 0; i < NP; i++) { A[i] = 0.0; An[i] = 0.0; AI[i] = 0; RH[i] = -1; AH[i] = -1.0e9; }
  setDefaults();
  refreshParams();
  for (let i = 0; i < NSRC + 1; i++) S[i] = 0.0;
  for (let i = 0; i < MAX_FRAMES * 2; i++) inBuf[i] = 0.0;
  for (let i = 0; i < 128; i++) ccMsb[i] = 0;
  osc1.reset(); osc2.reset(); lfo.reset(); env.reset(); lad.reset(); hpf.s = 0.0; dcF.s = 0.0; dcE.s = 0.0;
  upA.reset(); upB.reset(); upX.reset(); upN.reset(); upF.reset(); dnM.reset(); dnF.reset();
  tank.setup(); tank.reset();
  osc1.ph = 0.0; osc2.ph = 0.37;
  smCoef = <f32>1.0 - Mathf.exp(-<f32>1.0 * invSR / <f32>0.004);
  driftA = onePoleA(0.35);
  driftScale = Mathf.sqrt(<f32>6.0 / driftA);
  drift1 = 0.0; drift2 = 0.0;
  // keyboard / sequencer
  hN = 0; kTarget = 60.0; kCur = 60.0; kGateWant = false; kGateOut = false; kLowT = 1.0; kAccent = 0.0;
  kRunArp = false; kRunSeq = false; kPhase = 1.0; kGateOffArm = false; kArpPos = 0; kSeqPos = 0; kSeqCur = 0; kSeqKey = -1;
  kClkOutPh = 0.0; kClkOut = 0.0; kPpqAcc = 0.0; kHostIdx = -1; kStepFlash = 0.0; kAccentSeq = false;
  recArmed = true; recPendingTie = false; recLast = -1; lastMode = pi(P_ARP_MODE); lastSeqSel = pi(P_OCT_SEQ);
  for (let i = 0; i < 3; i++) seqLen[i] = 0;
  loadDefaultSeqs();
  ccBend = 0.0; glideEnabled = true; rpnSel = 16383; kbrGain = 0.0;
  hostBpm = 0.0; hostPlaying = 0; peakOut = 0.0; lfoSyncPrev = false;
  for (let i = 0; i < 16; i++) display[i] = 0.0;
  paramsDirty = true;
  onParams();
  smCut = tCut; smRes = tRes; smO1 = tO1; smO2 = tO2; smNz = tNz; smVol = tVol; smRev = tRev; smO2F = tO2F; smEnvAmt = tEnvAmt; smAtt = tAtt;
}

// ---------------------------------------------------------------------------- parameter-derived values
function onParams(): void {
  paramsDirty = false;
  for (let d = 0; d < NDST; d++) unchecked(SEL[d] = pi(P_PB_O1_PITCH + d));
  tCut = <f32>9.965784 * pv(P_CUTOFF);                   // octaves above 20 Hz: the panel scale is 20 Hz … 20 kHz, three decades
  tRes = <f32>4.5 * pv(P_RESO);
  tO1 = pv(P_MIX_O1) * <f32>1.6667;
  tO2 = pv(P_MIX_O2) * <f32>1.6667;
  tNz = pv(P_MIX_NZ) * <f32>1.6667;
  const v = pv(P_VOLUME);
  tVol = <f32>1.5 * v * v;
  tRev = pv(P_REV_MIX);
  tO2F = pv(P_O2_FREQ);
  tEnvAmt = pv(P_ENV_AMT);
  tAtt = pv(P_ATT);
  envA = <f32>0.0008 * Mathf.pow(<f32>10000.0, pv(P_ATK));      // 0.8 ms … 8 s
  envD = <f32>0.002 * Mathf.pow(<f32>6000.0, pv(P_DEC));        // 2 ms … 12 s
  envS = pv(P_SUS);
  envR = <f32>0.002 * Mathf.pow(<f32>6000.0, pv(P_REL));        // 2 ms … 12 s
  kbrCoef = Mathf.exp(-<f32>4.6 * invSR / envR);
  // LFO: 0.07 Hz … 1.3 kHz = 14.18 octaves
  lfoBaseOct = Mathf.log2(<f32>0.07) + <f32>14.18 * pv(P_MOD_RATE) + pv(P_MOD_FINE) * <f32>0.0833333;
  // HIGH PASS: 10 Hz … 10 kHz
  const hpHz = clampf(<f32>10.0 * exp2f(<f32>10.0 * pv(P_HP_CUT)), 5.0, SR * <f32>0.45);
  hpG = Mathf.tan(PI * hpHz * invSR);
  dcG = Mathf.tan(PI * <f32>4.0 * invSR);
  modeWatch();
  updateRun(false);
}

function loadDefaultSeqs(): void {
  SEQ_DEFAULTS();
}

// ---------------------------------------------------------------------------- MIDI in
function noteFromFreq(freq: f32): i32 {
  const m = i32(nearest<f32>(<f32>69.0 + <f32>12.0 * Mathf.log2(freq / <f32>440.0)));
  return m < 0 ? 0 : (m > 127 ? 127 : m);
}
export function noteOn(id: i32, freq: f32, vel: f32): void {
  refreshParams();
  if (paramsDirty) onParams();
  if (id == -2) { if (pi(P_ARP_MODE) == 2) recordMarker(0); return; }          // REST (HOLD button while recording)
  if (id == -3) { if (pi(P_ARP_MODE) == 2) recordMarker(1); return; }          // TIE  (PLAY button while recording)
  if (id == -4) { if (pi(P_ARP_MODE) == 2) recordMarker(2); return; }          // ACCENT (TAP button while recording)
  if (id == -5) { allNotesOff(); return; }                                      // all three LHC buttons: clear the note stack
  if (id < 0) return;
  let n = noteFromFreq(freq) + pi(P_KB_OCT) * 12 + pi(P_KB_TRANS);
  n = n < 0 ? 0 : (n > 127 ? 127 : n);
  keyOn(id, n, vel);
}
export function noteOff(id: i32): void {
  refreshParams();
  if (paramsDirty) onParams();
  if (id < 0) return;
  keyOff(id);
}
function ccSetN(p: i32, v: f32): void { setParamN(p, v); }
function applyCc(num: i32, value: f32): void {
  const v127: i32 = i32(nearest<f32>(value * <f32>127.0));
  if (num == 1) ccSetN(P_MODW, value);
  else if (num == 3) ccSetN(P_MOD_RATE, value);
  else if (num == 5) ccSetN(P_GLIDE, value);
  else if (num == 8) ccSetN(P_ARP_RATE, value);
  else if (num == 12) ccSetN(P_O2_FREQ, value);
  else if (num == 65) glideEnabled = value >= 0.5;
  else if (num == 69) setParamI(P_HOLD, value >= 0.5 ? 1 : 0);
  else if (num == 73) setParamI(P_PLAY, value >= 0.5 ? 1 : 0);
  else if (num == 74) setParamI(P_O1_OCT, v127 / 32);
  else if (num == 75) setParamI(P_O2_OCT, v127 / 32);
  else if (num == 77) setParamI(P_SYNC, value >= 0.5 ? 1 : 0);
  else if (num == 85) setParamI(P_GL_TYPE, i32(nearest<f32>(f32(v127) / <f32>42.5)));
  else if (num == 89) setParamI(P_KB_OCT, i32(nearest<f32>(f32(v127) / <f32>25.5)) - 2);
  else if (num == 90) {
    let idx = 0;
    for (let i = 0; i < 24; i++) if (v127 >= unchecked(CC90_V[i])) idx = i;
    ccSetN(P_ARP_RATE, (f32(idx) + <f32>0.5) / <f32>24.0);
  }
  else if (num == 91) setParamI(P_ARP_MODE, i32(nearest<f32>(f32(v127) / <f32>42.5)));
  else if (num == 92) setParamI(P_ARP_DIR, i32(nearest<f32>(f32(v127) / <f32>42.5)));
  else if (num == 93) setParamI(P_OCT_SEQ, i32(nearest<f32>(f32(v127) / <f32>42.5)));
  else if (num == 94) setParamI(P_GL_LEGATO, value >= 0.5 ? 1 : 0);
  else if (num == 103) setParamI(P_GL_GATED, value >= 0.5 ? 1 : 0);
  else if (num == 107) setParamI(P_BEND_UP, i32(nearest<f32>(f32(v127) * <f32>24.0 / <f32>123.0)));
  else if (num == 108) setParamI(P_BEND_DN, i32(nearest<f32>(f32(v127) * <f32>24.0 / <f32>123.0)));
  else if (num == 119) setParamI(P_KB_TRANS, i32(nearest<f32>(f32(v127) * <f32>24.0 / <f32>123.0)) - 12);
  else if (num == 122) setParamI(P_LOCAL, value >= 0.5 ? 1 : 0);
  else if (num == 101) { rpnMsb = v127; rpnSel = rpnMsb * 128 + rpnLsb; }
  else if (num == 100) { rpnLsb = v127; rpnSel = rpnMsb * 128 + rpnLsb; }
  else if (num == 6) {
    if (rpnSel == 0) { const b = v127 > 24 ? 24 : v127; setParamI(P_BEND_UP, b); setParamI(P_BEND_DN, b); }
    else if (rpnSel == 1) setParamN(P_FINE, value);
    else if (rpnSel == 2) setParamI(P_KB_TRANS, v127 - 64);
  }
}
export function controlChange(num: i32, value: f32): void {
  refreshParams();
  if (num == 128) { ccBend = value; return; }
  if (num == 129) return;
  if (num == 120 || num == 123) { allNotesOff(); return; }
  // 14-bit pairs: MSB 1/3/5/8/12 with LSB 33/35/37/40/44
  let msbNum = -1;
  if (num == 33) msbNum = 1; else if (num == 35) msbNum = 3; else if (num == 37) msbNum = 5; else if (num == 40) msbNum = 8; else if (num == 44) msbNum = 12;
  if (msbNum >= 0) {
    const lsb: i32 = i32(nearest<f32>(value * <f32>127.0));
    applyCc(msbNum, f32(ccMsb[msbNum] * 128 + lsb) / <f32>16383.0);
  } else {
    if (num < 128) ccMsb[num] = i32(nearest<f32>(value * <f32>127.0));
    applyCc(num, value);
  }
  if (paramsDirty) onParams();
}

// ---------------------------------------------------------------------------- one sample of the instrument
@inline function slew(c: f32, t: f32): f32 { return c + (t - c) * smCoef; }

function renderSample(inL: f32, inR: f32): f32 {
  const local = pi(P_LOCAL) != 0;
  // smoothed knob values
  smCut = slew(smCut, tCut); smRes = slew(smRes, tRes);
  smO1 = slew(smO1, tO1); smO2 = slew(smO2, tO2); smNz = slew(smNz, tNz);
  smVol = slew(smVol, tVol); smRev = slew(smRev, tRev); smO2F = slew(smO2F, tO2F);
  smEnvAmt = slew(smEnvAmt, tEnvAmt); smAtt = slew(smAtt, tAtt);

  // ---- ARP/SEQ module -----------------------------------------------------------------------
  keysTick(invSR);
  if (!glideEnabled) kCur = kTarget;
  const bn = clampf(pv(P_PITCHW) + ccBend, -1.0, 1.0);
  const bendSemi: f32 = bn >= 0.0 ? bn * f32(pi(P_BEND_UP)) : bn * f32(pi(P_BEND_DN));
  const kbV: f32 = (kCur + bendSemi - <f32>60.0) * <f32>0.0833333;
  const kbInt: f32 = local ? kbV : <f32>0.0;
  let kbOut = clampf(kbV, -5.0, 5.0);
  if (pi(P_KB_RANGE) == 1) kbOut = clampf(kbV + <f32>5.0, 0.0, 10.0);
  unchecked(S[S_GATE] = kGateOut ? <f32>8.0 : <f32>0.0);
  unchecked(S[S_KB] = kbOut);
  unchecked(S[S_VEL] = kAccentSeq ? kAccent * <f32>5.0 : kVel * <f32>5.0);
  unchecked(S[S_CLK] = kClkOut);
  unchecked(S[S_EXT] = (inL + inR) * <f32>0.5 * <f32>5.0 * pv(P_INST_LVL));

  // ---- MODULATION oscillator ------------------------------------------------------------------
  const rateCv = inp(D_LFO_RATE, 0.0);
  if (patched(D_LFO_SYNC)) {
    const sv = unchecked(S[unchecked(SEL[D_LFO_SYNC])]) > 1.2;
    if (sv && !lfoSyncPrev) lfo.syncReset();
    lfoSyncPrev = sv;
  } else lfoSyncPrev = false;
  const lfoInc = exp2f(lfoBaseOct + rateCv) * invSR;
  const lfoV = lfo.tick(lfoInc, pi(P_MOD_WAVE));
  unchecked(S[S_LFO] = lfoV);
  unchecked(S[S_SH] = lfo.sh);

  // ---- ENVELOPE ---------------------------------------------------------------------------------------
  const trig = inp(D_E_TRIG, local ? unchecked(S[S_GATE]) : <f32>0.0);
  const gateHi = trig > 1.2;
  const e = env.tick(gateHi, envA, envD, envS, envR);
  lastEnv = e;
  unchecked(S[S_ENVP] = e * <f32>8.0);
  unchecked(S[S_ENVN] = -e * <f32>8.0);

  // ---- OSCILLATORS --------------------------------------------------------------------------------------
  const modW = pv(P_MODW);
  const lfoN = lfoV * <f32>0.2;
  const pitchMod = lfoN * modW * pv(P_MOD_PITCH);
  const dr = pv(P_DRIFT);
  drift1 += (white() - drift1) * driftA; drift2 += (white() - drift2) * driftA;
  const dc1 = drift1 * driftScale * dr * <f32>0.0025;           // ~±3 cents at full DRIFT (octaves)
  const dc2 = drift2 * driftScale * dr * <f32>0.0025;
  const fine = pv(P_FINE) * <f32>0.0833333;
  const pwm = inp(D_O1_PWM, 0.0) * <f32>0.09;
  const pwMod = lfoN * modW * pv(P_MOD_PW) * <f32>0.45 + pwm;
  // oscillator 1
  const w1 = pi(P_O1_WAVE);
  const v1 = kbInt + f32(pi(P_O1_OCT) - 2) + fine + dc1 + pitchMod + inp(D_O1_PITCH, 0.0);
  const f1 = C4_HZ * exp2f(clampf(v1, -9.0, 6.0));
  const d1 = clampf((w1 == W_NAR ? <f32>0.25 : <f32>0.5) + pwMod, 0.04, 0.96);
  const o1 = osc1.sample(f1 * invSR, w1, d1, -1.0);
  const alphaM = osc1.wrapAlpha;
  unchecked(S[S_O1] = o1);
  // oscillator 2
  const w2 = pi(P_O2_WAVE);
  const sync = pi(P_SYNC) != 0;
  const o2semi: f32 = smO2F * (sync ? <f32>36.0 : <f32>7.0);
  const v2 = kbInt + f32(pi(P_O2_OCT) - 1) + fine + o2semi * <f32>0.0833333 + dc2 + pitchMod + inp(D_O2_PITCH, 0.0);
  const f2 = C4_HZ * exp2f(clampf(v2, -9.0, 6.0));
  const fmHz = inp(D_O2_FM, 0.0) * FM_HZ_PER_V;
  const d2 = clampf((w2 == W_NAR ? <f32>0.25 : <f32>0.5) + pwMod, 0.04, 0.96);
  const o2 = osc2.sample(maxf((f2 + fmHz) * invSR, 0.0), w2, d2, sync ? alphaM : <f32>-1.0);
  unchecked(S[S_O2] = o2);

  // ---- MIXER + FILTER at 2x the sample rate -------------------------------------------------------------
  //  The mixer's overdrive and the ladder's saturation are the nonlinear stages; they run on 2x oversampled
  //  copies of their inputs (half-band interpolation) and the result is decimated back. (The noise generator is
  //  wide-band: ±5 V in the audio band means ±7.07 V at 2x, because the decimator discards half the spectrum.)
  const in1 = inp(D_MX_O1, o1), in2 = inp(D_MX_O2, o2), inx = unchecked(S[S_EXT]);
  const fpat = patched(D_F_IN);
  upA.push(in1); upB.push(in2); upX.push(inx);
  if (patched(D_MX_NZ)) upN.push(inp(D_MX_NZ, 0.0));
  if (fpat) upF.push(inp(D_F_IN, 0.0));
  const trkMode = pi(P_KBD_TRK);
  const trk: f32 = (trkMode == 0 ? <f32>0.5 : (trkMode == 2 ? <f32>1.0 : <f32>0.0)) * kbInt;
  const envAmt = clampf(smEnvAmt + inp(D_F_ENVAMT, 0.0) * <f32>0.125, -1.5, 1.5);
  const cutOct = smCut + trk + envAmt * e * ENV_OCT + inp(D_F_CUT, 0.0) + lfoN * modW * pv(P_MOD_CUT) * <f32>5.0;
  const fc = clampf(<f32>20.0 * exp2f(clampf(cutOct, -3.0, 14.0)), 10.0, SR * <f32>0.45);
  lastCutHz = fc;
  const gF = Mathf.tan(PI * fc * invSR * <f32>0.5);                    // the ladder runs at 2·SR
  let mixA: f32 = 0.0; let mixB: f32 = 0.0; let filA: f32 = 0.0; let filB: f32 = 0.0;
  for (let ph = 0; ph < 2; ph++) {
    const a1 = ph == 0 ? upA.e : upA.o, a2 = ph == 0 ? upB.e : upB.o, ax = ph == 0 ? upX.e : upX.o;
    const x1 = kneeClip(a1 * smO1, 3.5, 8.0);
    const x2 = kneeClip(a2 * smO2, 3.5, 8.0);
    const xn = kneeClip(smNz == 0.0 ? <f32>0.0 : (patched(D_MX_NZ) ? (ph == 0 ? upN.e : upN.o) : white() * <f32>7.0710678) * smNz, 3.5, 8.0);
    const mixv = kneeClip(x1 + x2 + xn + ax, 6.0, 10.0);
    const fin = fpat ? (ph == 0 ? upF.e : upF.o) : mixv;
    const y = lad.tick(fin, gF, smRes);
    if (ph == 0) { mixA = mixv; filA = y; } else { mixB = mixv; filB = y; }
  }
  const mix = dnM.push(mixA, mixB);
  unchecked(S[S_MIX] = mix);
  const fil = dcF.tick(dnF.push(filA, filB), dcG);
  unchecked(S[S_FIL] = fil);

  // ---- UTILITIES ------------------------------------------------------------------------------------------------------
  const hpo = hpf.tick(inp(D_HP_IN, 0.0), hpG);
  unchecked(S[S_HP] = hpo);
  unchecked(S[S_ATT] = inp(D_ATT_IN, 8.0) * smAtt);
  unchecked(S[S_MULT] = inp(D_MULT_A, 0.0) + inp(D_MULT_B, 0.0));

  // ---- OUTPUT: VCA --------------------------------------------------------------------------------------------------------
  if (gateHi) kbrGain = 1.0; else kbrGain = denorm(kbrGain * kbrCoef);
  const vm = pi(P_VCA_MODE);
  const vamtPatched = patched(D_V_AMT);
  const vamt = inp(D_V_AMT, 0.0) * <f32>0.125;
  let gain: f32 = 1.0;
  if (vm == 2) gain = vamtPatched ? clampf(vamt, 0.0, 1.0) : <f32>1.0;
  else gain = clampf((vm == 0 ? e : kbrGain) + vamt, 0.0, 1.25);
  const vca = inp(D_V_IN, fil) * gain;

  // ---- spring reverb + mix --------------------------------------------------------------------------------------------------------
  const wet = tank.tick(inp(D_R_IN, vca) * <f32>0.2) * <f32>5.0;
  unchecked(S[S_REV] = wet);
  const euro = kneeClip(dcE.tick(vca * (<f32>1.0 - smRev) + wet * smRev, dcG), 5.0, 8.0);
  unchecked(S[S_EURO] = euro);
  return euro;
}

export function process(n: i32): void {
  refreshParams();
  if (paramsDirty) onParams();
  for (let i = 0; i < n; i++) {
    const inl = unchecked(inBuf[i]);
    const inr = unchecked(inBuf[MAX_FRAMES + i]);
    if (hostPlaying != 0) kPpqAcc += <f64>hostTempo() * <f64>0.0166666667 * <f64>invSR;
    const v = renderSample(inl, inr);
    let o = v * <f32>0.125 * smVol;
    // transparent below 0.85, smooth ceiling at 1.0
    o = kneeClip(finite(o), 0.85, 1.0);
    unchecked(outBuf[i] = o);
    unchecked(outBuf[MAX_FRAMES + i] = o);
    const ao = absf(o);
    peakOut = ao > peakOut ? ao : peakOut * <f32>0.99995;
  }
  // GUI display
  display[0] = lfo.ph < 0.5 ? <f32>1.0 : <f32>0.0;
  display[1] = kStepFlash;
  display[2] = lastEnv;
  display[3] = kGateOut ? <f32>1.0 : <f32>0.0;
  display[4] = (kRunSeq ? f32(kSeqCur + 1) : <f32>0.0) * <f32>0.00390625;
  display[5] = f32(seqLen[pi(P_OCT_SEQ)]) * <f32>0.00390625;
  display[6] = (kRunArp ? <f32>1.0 : <f32>0.0) + (kRunSeq ? <f32>2.0 : <f32>0.0);
  display[7] = recArmed ? <f32>1.0 : <f32>0.0;
  display[8] = peakOut;
  display[9] = kCur;
  display[10] = Mathf.log2(lastCutHz * <f32>0.05) * <f32>0.1003;
  display[11] = kVel;
}
