// =====================================================================
//  Doob — GENERATED by factory/doob/build.mjs. Edit the sources:
//    factory/doob/params.mjs   (parameter table + packing)
//    factory/doob/scales.mjs   (scale / key-error tables)
//    factory/doob/dsp/core.ts
//    factory/doob/dsp/osc.ts
//    factory/doob/dsp/mods.ts
//    factory/doob/dsp/keys.ts
//    factory/doob/dsp/main.ts
// =====================================================================

const NP: i32 = 57;
const NUM_PARAMS: i32 = 27;
const P_TUNE: i32 = 0;
const P_GLIDE: i32 = 1;
const P_MODMIX: i32 = 2;
const P_OSC_MOD: i32 = 3;
const P_FIL_MOD: i32 = 4;
const P_O3_CTRL: i32 = 5;
const P_O1_RANGE: i32 = 6;
const P_O1_WAVE: i32 = 7;
const P_O2_RANGE: i32 = 8;
const P_O2_FREQ: i32 = 9;
const P_O2_WAVE: i32 = 10;
const P_O3_RANGE: i32 = 11;
const P_O3_FREQ: i32 = 12;
const P_O3_WAVE: i32 = 13;
const P_SW_O1: i32 = 14;
const P_VOL1: i32 = 15;
const P_SW_O2: i32 = 16;
const P_VOL2: i32 = 17;
const P_SW_O3: i32 = 18;
const P_VOL3: i32 = 19;
const P_SW_EXT: i32 = 20;
const P_VOLEXT: i32 = 21;
const P_SW_NZ: i32 = 22;
const P_VOLNZ: i32 = 23;
const P_NZ_COLOR: i32 = 24;
const P_CUTOFF: i32 = 25;
const P_EMPH: i32 = 26;
const P_CONTOUR: i32 = 27;
const P_FATK: i32 = 28;
const P_FDEC: i32 = 29;
const P_FSUS: i32 = 30;
const P_KB1: i32 = 31;
const P_KB2: i32 = 32;
const P_LATK: i32 = 33;
const P_LDEC: i32 = 34;
const P_LSUS: i32 = 35;
const P_OUTVOL: i32 = 36;
const P_MAIN_ON: i32 = 37;
const P_A440: i32 = 38;
const P_PITCHW: i32 = 39;
const P_MODW: i32 = 40;
const P_GLIDE_ON: i32 = 41;
const P_DECAY_ON: i32 = 42;
const P_STRIG: i32 = 43;
const P_FEEDBACK: i32 = 44;
const P_DRIFT: i32 = 45;
const P_BLEED: i32 = 46;
const P_KEY_PRI: i32 = 47;
const P_TRIG_MODE: i32 = 48;
const P_BEND: i32 = 49;
const P_SCALE: i32 = 50;
const P_KEY_ERR: i32 = 51;
const P_MOD_A: i32 = 52;
const P_MOD_B: i32 = 53;
const P_LFO_RATE: i32 = 54;
const P_LFO_WAVE: i32 = 55;
const P_LOCAL: i32 = 56;
const PSLOT: StaticArray<i32> = [0, 1, 2, 25, 26, 26, 25, 25, 25, 3, 25, 25, 4, 25, 26, 5, 26, 6, 26, 7, 26, 8, 26, 9, 26, 10, 11, 12, 13, 14, 15, 26, 26, 16, 17, 18, 19, 26, 26, 20, 21, 26, 26, 26, 26, 22, 23, 25, 26, 25, 25, 26, 26, 26, 24, 26, 26];
const PMULT: StaticArray<i32> = [1, 1, 1, 6718464, 1, 2, 12, 72, 432, 1, 2592, 15552, 1, 93312, 4, 1, 8, 1, 16, 1, 32, 1, 64, 1, 128, 1, 1, 1, 1, 1, 1, 256, 512, 1, 1, 1, 1, 1024, 2048, 1, 1, 4096, 8192, 16384, 32768, 1, 1, 2239488, 65536, 1, 559872, 131072, 262144, 524288, 1, 1048576, 2097152];
const PSTEPS: StaticArray<i32> = [0, 0, 0, 2, 2, 2, 6, 6, 6, 0, 6, 6, 0, 6, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 3, 2, 12, 4, 2, 2, 2, 0, 2, 2];
const PDIRECT: StaticArray<i32> = [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0];
const PMIN: StaticArray<f32> = [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
const PMAX: StaticArray<f32> = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 1.0, 5.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 12.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0];
const SCALE_DEV: StaticArray<f32> = [0.0, 0.13685006057711915, 0.039100017307748376, -0.05865002596162355, 0.07820003461549675, -0.019550008653874896, 0.11730005192324597, 0.01955000865387433, 0.1564000692309935, 0.058650025961622984, -0.03910001730774979, 0.0977500432693705, 0.0, 0.049554095004072846, 0.039100017307748376, 0.1564128700055255, -0.13686286135165177, -0.019550008653874896, -0.4868205763524327, 0.01955000865387433, 0.40527661769310613, -0.1564128700055255, -0.31174093530875097, -0.117312852697778];
const PARTCH: StaticArray<f32> = [0.0, 0.21506289596714778, 0.5327294323014412, 0.8446719346967759, 1.1173128526977774, 1.5063705850063058, 1.6500422849992202, 1.8240371213406008, 2.0391000173077485, 2.31174093530875, 2.6687090560373763, 2.9413499740383764, 3.1564128700055254, 3.4740794063398197, 3.8631371386483484, 4.1750796410436815, 4.3508409526165, 4.707809073345124, 4.980449991346125, 5.195512887313275, 5.513179423647568, 5.8251219260429, 6.174878073957099, 6.486820576352434, 6.804487112686725, 7.019550008653875, 7.292190926654875, 7.649159047383502, 7.824920358956317, 8.136862861351652, 8.525920593660182, 8.843587129994475, 9.058650025961622, 9.331290943962625, 9.688259064691248, 9.96089998269225, 10.175962878659401, 10.34995771500078, 10.493629414993693, 10.882687147302223, 11.155328065303225, 11.467270567698558, 11.784937104032851];
const KEYERR: StaticArray<f32> = [0.0, -0.00543, -0.01153, -0.01559, -0.01321, -0.01687, -0.02284, -0.02535, -0.02943, -0.02461, -0.02861, -0.03024, -0.03067, -0.02521, -0.02559, -0.02523, -0.03199, -0.03849, -0.04813, -0.0542, -0.04728, -0.05723, -0.05511, -0.05369, -0.04373, -0.03868, -0.03797, -0.03958, -0.03021, -0.02386, -0.02819, -0.03314, -0.03583, -0.03703, -0.04354, -0.03937, -0.04631, -0.04372, -0.03393, -0.0269, -0.01693, -0.01218, -0.0087, -0.01469];
function setDefaults(): void {
  params[0] = 0.0;
  params[1] = 0.0;
  params[2] = 0.0;
  params[3] = 0.0;
  params[4] = 0.0;
  params[5] = 0.7;
  params[6] = 0.0;
  params[7] = 0.0;
  params[8] = 0.5;
  params[9] = 0.0;
  params[10] = 0.55;
  params[11] = 0.15;
  params[12] = 0.3;
  params[13] = 0.1;
  params[14] = 0.45;
  params[15] = 0.3;
  params[16] = 0.05;
  params[17] = 0.5;
  params[18] = 1.0;
  params[19] = 0.7;
  params[20] = 0.0;
  params[21] = 0.0;
  params[22] = 0.3;
  params[23] = 0.15;
  params[24] = 0.4;
  params[25] = 239946.0;
  params[26] = 2098438.0;
}

// =====================================================================
//  core.ts — shared primitives for KGrbdPa: ABI buffers, packed-parameter
//  decoding (with MIDI-CC overrides), noise, saturators, one-pole filters.
//  Pasted after the generated tables. Everything is f32 and allocation-free
//  after init().
//
//  VOLTAGE MODEL: every jack of the patch bay carries volts, like the hardware:
//  audio ±5 V (10 Vpp), pitch CV 1 V/oct, gate 0/+8 V, envelope 0…+8 V,
//  KB VEL 0…+5 V. The host sees ±1 = ±8 V.
// =====================================================================

const MAX_FRAMES: i32 = 8192;
const MAX_PARAMS: i32 = 64;
const PI: f32 = 3.14159265358979;
const TWO_PI: f32 = 6.28318530717959;
const C4_HZ: f32 = 261.6255653;           // 8' at MIDI note 60 (concert pitch)

const inBuf  = new StaticArray<f32>(MAX_FRAMES * 2);
const outBuf = new StaticArray<f32>(MAX_FRAMES * 2);
const params = new StaticArray<f32>(MAX_PARAMS);
const display = new StaticArray<f32>(16);

let SR: f32 = 48000.0;
let invSR: f32 = 1.0 / 48000.0;

@inline function clampf(x: f32, lo: f32, hi: f32): f32 { return x < lo ? lo : (x > hi ? hi : x); }
@inline function minf(a: f32, b: f32): f32 { return a < b ? a : b; }
@inline function maxf(a: f32, b: f32): f32 { return a > b ? a : b; }
@inline function absf(x: f32): f32 { return x < 0.0 ? -x : x; }
@inline function exp2f(x: f32): f32 { return Mathf.exp(x * <f32>0.6931472); }
@inline function finite(x: f32): f32 { return (x > -1.0e6 && x < 1.0e6) ? x : <f32>0.0; }
@inline function denorm(x: f32): f32 { return (x > 1.0e-18 || x < -1.0e-18) ? x : <f32>0.0; }

// ---- noise -------------------------------------------------------------
let rng: u32 = 0x9e3779b9;
@inline function white(): f32 {
  rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5;
  return f32(rng) * <f32>4.656612873e-10 - <f32>1.0;      // [-1, 1)
}
@inline function rand01(): f32 { return (white() + <f32>1.0) * <f32>0.5; }

// ---- saturators ----------------------------------------------------------
// identity near 0, saturates at ±1
@inline function softclip(x: f32): f32 {
  if (x > 3.0) return 1.0;
  if (x < -3.0) return -1.0;
  const x2 = x * x;
  return x * (27.0 + x2) / (27.0 + 9.0 * x2);
}
// transparent below `knee`, smooth tanh knee up to `ceil` (both in the signal's units)
@inline function kneeClip(x: f32, knee: f32, ceil: f32): f32 {
  const a = x < 0.0 ? -x : x;
  if (a <= knee) return x;
  const w = ceil - knee;
  const m: f32 = knee + w * Mathf.tanh((a - knee) / w);
  return x < 0.0 ? -m : m;
}

// ---- packed parameters -------------------------------------------------------
// params[] holds the host slots. Every logical parameter lives in one slot as a
// mixed-radix digit (factory/kgrbdpa/params.mjs). A[] = decoded actual values,
// An[] = the same normalised 0..1, AI[] = integer value (for int/sel params).
// MIDI CCs write A/An/AI directly; the value stays until the HOST changes that
// parameter again (RH/AH remember the last host-side value per parameter).
const A = new StaticArray<f32>(NP);
const An = new StaticArray<f32>(NP);
const AI = new StaticArray<i32>(NP);
const RH = new StaticArray<i32>(NP);      // last host raw digit (packed params)
const AH = new StaticArray<f32>(NP);      // last host value (direct params)
const slotCache = new StaticArray<f32>(MAX_PARAMS);
let paramsDirty: bool = true;             // set whenever any parameter changed (host or CC)

function decodeSlot(s: i32, v: f32): void {
  let k: i32 = i32(nearest<f32>(v));
  if (k < 0) k = 0;
  if (k > 16777215) k = 16777215;
  for (let i = 0; i < NP; i++) {
    if (unchecked(PSLOT[i]) != s) continue;
    const lo = unchecked(PMIN[i]);
    const hi = unchecked(PMAX[i]);
    if (unchecked(PDIRECT[i]) != 0) {
      const a = clampf(v, lo, hi);
      if (a == unchecked(AH[i])) continue;
      unchecked(AH[i] = a);
      unchecked(A[i] = a);
      unchecked(An[i] = (a - lo) / (hi - lo));
      unchecked(AI[i] = 0);
    } else {
      const steps = unchecked(PSTEPS[i]);
      const raw = (k / unchecked(PMULT[i])) % steps;
      if (raw == unchecked(RH[i])) continue;
      unchecked(RH[i] = raw);
      const n: f32 = steps > 1 ? f32(raw) / f32(steps - 1) : <f32>0.0;
      unchecked(An[i] = n);
      unchecked(A[i] = lo + f32(raw));
      unchecked(AI[i] = i32(lo) + raw);
    }
    paramsDirty = true;
  }
}
// Returns true when any slot changed since the last call.
function refreshParams(): bool {
  let changed = false;
  for (let s = 0; s < NUM_PARAMS; s++) {
    const v = unchecked(params[s]);
    if (v != unchecked(slotCache[s])) { unchecked(slotCache[s] = v); decodeSlot(s, v); changed = true; }
  }
  return changed;
}
// MIDI CC → parameter, n = 0..1 across the control's whole range
function setParamN(i: i32, n: f32): void {
  const nn = clampf(n, 0.0, 1.0);
  const lo = unchecked(PMIN[i]);
  const hi = unchecked(PMAX[i]);
  if (unchecked(PDIRECT[i]) != 0) {
    unchecked(A[i] = lo + nn * (hi - lo));
    unchecked(An[i] = nn);
  } else {
    const steps = unchecked(PSTEPS[i]);
    let raw: i32 = i32(nearest<f32>(nn * f32(steps - 1)));
    if (raw < 0) raw = 0; if (raw > steps - 1) raw = steps - 1;
    unchecked(An[i] = steps > 1 ? f32(raw) / f32(steps - 1) : <f32>0.0);
    unchecked(A[i] = lo + f32(raw));
    unchecked(AI[i] = i32(lo) + raw);
  }
  paramsDirty = true;
}
function setParamI(i: i32, v: i32): void {
  const lo = i32(unchecked(PMIN[i]));
  const steps = unchecked(PSTEPS[i]);
  let raw = v - lo;
  if (raw < 0) raw = 0; if (raw > steps - 1) raw = steps - 1;
  unchecked(An[i] = steps > 1 ? f32(raw) / f32(steps - 1) : <f32>0.0);
  unchecked(A[i] = f32(lo + raw));
  unchecked(AI[i] = lo + raw);
  paramsDirty = true;
}
@inline function pv(i: i32): f32 { return unchecked(A[i]); }       // actual value
@inline function pn(i: i32): f32 { return unchecked(An[i]); }      // 0..1
@inline function pi(i: i32): i32 { return unchecked(AI[i]); }      // integer / list index

// ---- host transport / tempo ------------------------------------------------
let hostBpm: f32 = 0.0;
let hostPlaying: i32 = 0;
let hostPpq: f64 = 0.0;
let hostPpqFresh: bool = false;
function setHostTransport(playing: i32, ppq: f64, bpm: f32): void {
  hostBpm = bpm; hostPlaying = playing; hostPpq = ppq; hostPpqFresh = true;
}
@inline function hostTempo(): f32 {
  const t = unchecked(params[63]);
  return t > 1.0 ? t : (hostBpm > 1.0 ? hostBpm : <f32>0.0);
}

// ---- one-pole filters -------------------------------------------------------
class OnePole {
  z: f32 = 0;
  lp(x: f32, a: f32): f32 { this.z = denorm(this.z + a * (x - this.z)); return this.z; }
  hp(x: f32, a: f32): f32 { this.z = denorm(this.z + a * (x - this.z)); return x - this.z; }
}
@inline function onePoleA(fc: f32): f32 { return <f32>1.0 - Mathf.exp(-TWO_PI * clampf(fc, 0.01, SR * 0.45) * invSR); }
// zero-delay (trapezoidal) one-pole high-pass: exact at fc, used by the HIGH PASS filter
class Hp1 {
  s: f32 = 0;
  tick(x: f32, g: f32): f32 {
    const G = g / (<f32>1.0 + g);
    const v = (x - this.s) * G;
    const lp = v + this.s;
    this.s = denorm(lp + v);
    return x - lp;
  }
}


// =====================================================================
//  osc.ts — the three VCOs (and the LFO).
//
//  GOsc renders the Model D's waveforms in normalised units (±1 ≈ ±1.7 V on the board):
//    kind 0  a·triangle + b·saw       triangle (a=1,b=0) · shark tooth = the saw/triangle
//                                      resistor mix of the waveform switch (R031 10 K triangle,
//                                      R030 47 K saw → 0.824 / 0.176) · saw (0,1) · reverse saw (0,-1)
//    kind 1  pulse of duty d          square 50 %, wide ≈ 33 %, narrow ≈ 17 % (AC coupled)
//  Every discontinuity (saw wrap, pulse edges) and slope change (triangle corners) is
//  band-limited with 32-tap Kaiser-windowed-sinc step / ramp tables (alias floor ≈ -70 dB)
//  applied to a 16-sample delay line, so the oscillators have a fixed 16-sample latency.
// =====================================================================

const SIN_N: i32 = 4096;
const sinT = new StaticArray<f32>(SIN_N + 2);
function initSin(): void { for (let i = 0; i < SIN_N + 2; i++) sinT[i] = Mathf.sin(TWO_PI * f32(i) / f32(SIN_N)); }
@inline function fsin(ph: f32): f32 {
  const p = ph - Mathf.floor(ph);
  const x = p * f32(SIN_N);
  const i = i32(x);
  const f = x - f32(i);
  const a = unchecked(sinT[i]);
  return a + (unchecked(sinT[i + 1]) - a) * f;
}

// ---- band-limited step / ramp residual tables -----------------------------------------------------
//  A discontinuity of height J at time te adds J·STEP_RES(n - te) to every sample n within ±16 samples;
//  a slope change dS adds dS·RAMP_RES(n - te). STEP_RES / RAMP_RES are (band-limited step/ramp) minus
//  (ideal step/ramp): exactly what turns the naive waveform into the band-limited one. The band-limiting
//  kernel is a 32-tap Kaiser-windowed sinc (β = 7.5) with its cutoff at 0.43·fs: everything that could
//  fold back into the audible band is > 70 dB down. Tables: 32 taps × BL_P sub-sample phases, built once at init.
const BL_H: i32 = 16;                           // half width (samples)
const BL_T: i32 = 32;                           // taps per phase
const BL_P: i32 = 128;
const BL_LAT: i32 = 16;                         // output latency of the oscillators (samples)
const BL_RING: i32 = 64;
const blStep = new StaticArray<f32>((BL_P + 1) * BL_T);
const blRamp = new StaticArray<f32>((BL_P + 1) * BL_T);
function besselI0(x: f64): f64 {
  let sum: f64 = 1.0; let term: f64 = 1.0; const q: f64 = x * x * 0.25;
  for (let k = 1; k < 40; k++) { term = term * q / (<f64>k * <f64>k); sum += term; if (term < 1.0e-14 * sum) break; }
  return sum;
}
function initBlep(): void {
  const F: i32 = 128;                           // fine steps per sample
  const n: i32 = 2 * BL_H * F;                  // τ from -H .. +H
  const ws = new StaticArray<f64>(n + 1);
  const fcn: f64 = 0.43;                        // cutoff, cycles per sample
  const beta: f64 = 7.5;
  const i0b: f64 = besselI0(beta);
  let tot: f64 = 0.0;
  for (let i = 0; i <= n; i++) {
    const t: f64 = (<f64>i - <f64>(n / 2)) / <f64>F;
    const x: f64 = 2.0 * Math.PI * fcn * t;
    const sinc: f64 = t == 0.0 ? 1.0 : Math.sin(x) / x;
    let r: f64 = t / <f64>BL_H; r = 1.0 - r * r; if (r < 0.0) r = 0.0;
    const w: f64 = besselI0(beta * Math.sqrt(r)) / i0b;
    unchecked(ws[i] = sinc * w);
    tot += sinc * w;
  }
  tot = tot / <f64>F;                           // ∫ kernel (so the step ends at exactly 1)
  const st = new StaticArray<f64>(n + 1);       // band-limited step
  const rp = new StaticArray<f64>(n + 1);       // band-limited ramp
  let acc: f64 = 0.0; let acc2: f64 = 0.0;
  for (let i = 0; i <= n; i++) {
    if (i > 0) acc += 0.5 * (unchecked(ws[i]) + unchecked(ws[i - 1])) / (<f64>F * tot);
    unchecked(st[i] = acc);
    if (i > 0) acc2 += 0.5 * (unchecked(st[i]) + unchecked(st[i - 1])) / <f64>F;
    unchecked(rp[i] = acc2);
  }
  for (let ph = 0; ph <= BL_P; ph++) {
    const alpha: f64 = <f64>ph / <f64>BL_P;
    for (let j = 0; j < BL_T; j++) {
      const tau: f64 = alpha + <f64>(j - (BL_H - 1));        // sample offset from the edge
      let fi = (tau + <f64>BL_H) * <f64>F;
      let beyond: f64 = 0.0;                                   // past the kernel's support the ramp continues linearly
      if (fi < 0.0) fi = 0.0;
      if (fi > <f64>n) { beyond = (fi - <f64>n) / <f64>F; fi = <f64>n; }
      const i0: i32 = i32(fi); const fr: f64 = fi - <f64>i0;
      const i1: i32 = i0 < n ? i0 + 1 : i0;
      const sv: f64 = unchecked(st[i0]) * (1.0 - fr) + unchecked(st[i1]) * fr;
      const rv: f64 = unchecked(rp[i0]) * (1.0 - fr) + unchecked(rp[i1]) * fr + beyond;
      const hv: f64 = tau >= 0.0 ? 1.0 : 0.0;
      unchecked(blStep[ph * BL_T + j] = <f32>(sv - hv));
      unchecked(blRamp[ph * BL_T + j] = <f32>(rv - (tau >= 0.0 ? tau : 0.0)));
    }
  }
}

class GOsc {
  ph: f32 = 0;
  n: i32 = 0;
  hist: StaticArray<f32> = new StaticArray<f32>(BL_RING);
  acc: StaticArray<f32> = new StaticArray<f32>(BL_RING);

  // naive waveform at phase p
  naive(p: f32, kind: i32, a: f32, b: f32, d: f32): f32 {
    if (kind == 0) {
      const tri: f32 = p < 0.5 ? <f32>4.0 * p - <f32>1.0 : <f32>3.0 - <f32>4.0 * p;
      return a * tri + b * (<f32>2.0 * p - <f32>1.0);
    }
    return p < d ? <f32>2.0 * (<f32>1.0 - d) : <f32>-2.0 * d;           // AC-coupled pulse, 2 units peak-to-peak
  }
  @inline step(J: f32, alpha: f32): void { this.addTab(J, alpha, blStep); }
  @inline kink(dS: f32, inc: f32, alpha: f32): void { this.addTab(dS * inc, alpha, blRamp); }
  addTab(amp: f32, alpha: f32, tab: StaticArray<f32>): void {
    const x = alpha * <f32>BL_P;
    let i = i32(x);
    if (i >= BL_P) i = BL_P - 1;
    const fr = x - f32(i);
    const o0 = i * BL_T;
    const o1 = o0 + BL_T;
    const base = this.n - (BL_H - 1);
    for (let j = 0; j < BL_T; j++) {
      const r = unchecked(tab[o0 + j]) * (<f32>1.0 - fr) + unchecked(tab[o1 + j]) * fr;
      const idx = (base + j) & (BL_RING - 1);
      unchecked(this.acc[idx] = this.acc[idx] + amp * r);
    }
  }
  sample(inc0: f32, kind: i32, a: f32, b: f32, d: f32): f32 {
    const inc = clampf(inc0, 1.0e-7, 0.45);
    const oldPh = this.ph;
    const pu = oldPh + inc;
    let wrapped = false;
    let alphaW: f32 = 0.0;
    if (pu >= 1.0) { wrapped = true; alphaW = (pu - <f32>1.0) / inc; }
    if (kind == 0) {
      if (wrapped) {
        if (b != 0.0) this.step(<f32>-2.0 * b, alphaW);
        if (a != 0.0) this.kink(<f32>8.0 * a, inc, alphaW);
      }
      if (a != 0.0 && oldPh < 0.5 && pu >= 0.5 && pu < 1.0) this.kink(<f32>-8.0 * a, inc, (pu - <f32>0.5) / inc);
    } else {
      if (wrapped) this.step(2.0, alphaW);
      if (oldPh < d && pu >= d && pu < 1.0) this.step(-2.0, (pu - d) / inc);
    }
    let p = wrapped ? pu - <f32>1.0 : pu;
    if (p >= 1.0) p -= 1.0;
    this.ph = p;
    unchecked(this.hist[this.n & (BL_RING - 1)] = this.naive(p, kind, a, b, d));
    const oi = (this.n - BL_LAT) & (BL_RING - 1);
    const emit = unchecked(this.hist[oi]) + unchecked(this.acc[oi]);
    unchecked(this.acc[oi] = 0.0);
    this.n = this.n + 1;
    return emit;
  }
  reset(): void {
    this.ph = 0; this.n = 0;
    for (let i = 0; i < BL_RING; i++) { this.hist[i] = 0.0; this.acc[i] = 0.0; }
  }
}


// =====================================================================
//  mods.ts — the Moog ladder filter, the two contour generators, the noise
//  generator (white / pink / red) and the 2x oversampling half-band filters.
// =====================================================================

// ---- 4-pole Moog ladder (zero-delay feedback, saturating input + feedback) ----------------------
//  Normalised signal (±1). g = tan(pi·fc/fs), k = regeneration (self-oscillation from k = 4).
//  The input stage soft-clips (slope 1, ceiling ~1.15 — the overload that fattens the mixer);
//  the feedback path saturates like the transistor ladder's stages, which sets the amplitude of
//  the sine produced at EMPHASIS 10.
const FB_CLIP: f32 = 0.7;
class Ladder {
  s1: f32 = 0; s2: f32 = 0; s3: f32 = 0; s4: f32 = 0;
  tick(xin: f32, g: f32, k: f32): f32 {
    const G = g / (<f32>1.0 + g);
    const G2 = G * G;
    const Gm = <f32>1.0 - G;
    const S = Gm * (G2 * G * this.s1 + G2 * this.s2 + G * this.s3 + this.s4);
    const x = <f32>1.15 * softclip((xin + white() * <f32>0.00002) * <f32>0.87);
    let u = (x - k * S) / (<f32>1.0 + k * G2 * G2);
    const y4p = G2 * G2 * u + S;
    if (y4p > FB_CLIP * <f32>0.6 || y4p < -FB_CLIP * <f32>0.6) u = x - k * FB_CLIP * softclip(y4p / FB_CLIP);
    const v1 = G * (u - this.s1); const y1 = v1 + this.s1; this.s1 = denorm(y1 + v1);
    const v2 = G * (y1 - this.s2); const y2 = v2 + this.s2; this.s2 = denorm(y2 + v2);
    const v3 = G * (y2 - this.s3); const y3 = v3 + this.s3; this.s3 = denorm(y3 + v3);
    const v4 = G * (y3 - this.s4); const y4 = v4 + this.s4; this.s4 = denorm(y4 + v4);
    return y4;
  }
  reset(): void { this.s1 = 0; this.s2 = 0; this.s3 = 0; this.s4 = 0; }
}

// ---- contour generator (the 93-114 board) -----------------------------------------------------------
//  Attack: a 10 µF timing capacitor charges through the ATTACK pot toward +9.3 V and a flip-flop
//  fires when the output reaches its peak (+4.0 V filter / +4.5 V loudness from a +0.1 / -0.3 V
//  rest level): v rises as kA·(1 - e^(-t/τ)) up to 1, kA = 2.36 (filter) or 2.0 (loudness).
//  Decay / release: the capacitor discharges through the DECAY pot toward about -2.5 (in peak
//  units: -10 V against a +4 V peak) and the SUSTAIN level clamps the fall. The DECAY switch off
//  releases through a 1.5 K resistor (15 ms). Re-triggering attacks from the CURRENT level, and
//  the peak creeps up a little when played rapidly (documented on the originals).
const C_IDLE: i32 = 0;
const C_ATK: i32 = 1;
const C_DEC: i32 = 2;
const C_SUS: i32 = 3;
const C_REL: i32 = 4;
const C_TARGET: f32 = 2.5;                         // discharge target, in peak units
const C_LN: f32 = 0.33647224;                      // ln((1 + 2.5) / 2.5): 1 → 0 takes T = τ · C_LN
class Contour {
  v: f32 = 0;
  peak: f32 = 1;
  stage: i32 = 0;
  gate: bool = false;
  kA: f32 = 2.0;
  creep: f32 = 0.1;
  // aT: attack time rest→peak (s); dT: decay time peak→0 (s); relT: release time (s) or <0 for the fast 1.5 K release
  tick(g: bool, aT: f32, dT: f32, s: f32, relT: f32): f32 {
    if (g && !this.gate) { this.stage = C_ATK; this.peak = <f32>1.0 + this.creep * this.v; }
    if (!g && this.gate && this.stage != C_IDLE) this.stage = C_REL;
    this.gate = g;
    const st = this.stage;
    if (st == C_ATK) {
      const tau = aT / Mathf.log(this.kA / (this.kA - <f32>1.0));
      this.v += (this.kA * this.peak - this.v) * (<f32>1.0 - Mathf.exp(-invSR / tau));
      if (this.v >= this.peak) { this.v = this.peak; this.stage = C_DEC; }
    } else if (st == C_DEC) {
      const tau = dT / C_LN;
      this.v += (-C_TARGET - this.v) * (<f32>1.0 - Mathf.exp(-invSR / tau));
      if (this.v <= s) { this.v = s; this.stage = C_SUS; }
    } else if (st == C_SUS) {
      this.v += (s - this.v) * <f32>0.004;
    } else if (st == C_REL) {
      const tau = relT < 0.0 ? <f32>0.015 : relT / C_LN;
      this.v += (-C_TARGET - this.v) * (<f32>1.0 - Mathf.exp(-invSR / tau));
      if (this.v <= 0.0) { this.v = 0.0; this.stage = C_IDLE; }
    }
    this.v = denorm(this.v);
    return this.v;
  }
  reset(): void { this.v = 0; this.stage = C_IDLE; this.gate = false; this.peak = 1; }
}

// ---- noise generator (board 3: white, pink = -3 dB/oct, red = 100 Hz low-pass) --------------------------
class Noise {
  b0: f32 = 0; b1: f32 = 0; b2: f32 = 0; b3: f32 = 0; b4: f32 = 0; b5: f32 = 0; b6: f32 = 0;
  r1: f32 = 0; r2: f32 = 0;
  rA: f32 = 0.013;
  setup(): void { this.rA = onePoleA(100.0); }
  // returns white; pink / red are produced from the same white sample
  pink(w: f32): f32 {                              // Paul Kellet's refined pink filter, normalised to ~±1 peak
    this.b0 = <f32>0.99886 * this.b0 + w * <f32>0.0555179;
    this.b1 = <f32>0.99332 * this.b1 + w * <f32>0.0750759;
    this.b2 = <f32>0.96900 * this.b2 + w * <f32>0.1538520;
    this.b3 = <f32>0.86650 * this.b3 + w * <f32>0.3104856;
    this.b4 = <f32>0.55000 * this.b4 + w * <f32>0.5329522;
    this.b5 = <f32>-0.7616 * this.b5 - w * <f32>0.0168980;
    const p = this.b0 + this.b1 + this.b2 + this.b3 + this.b4 + this.b5 + this.b6 + w * <f32>0.5362;
    this.b6 = w * <f32>0.115926;
    return p * <f32>0.28;
  }
  red(w: f32): f32 {                               // two-pole 100 Hz low-pass (R914/R915/R916 with C908/C915)
    this.r1 += this.rA * (w - this.r1);
    this.r2 += this.rA * (this.r1 - this.r2);
    return this.r2 * <f32>4.2;
  }
  reset(): void { this.b0 = 0; this.b1 = 0; this.b2 = 0; this.b3 = 0; this.b4 = 0; this.b5 = 0; this.b6 = 0; this.r1 = 0; this.r2 = 0; }
}

// ---- 2x oversampling for the nonlinear stages (mixer overload + ladder) ------------------------------------
//  47-tap Kaiser half-band filters (β = 7): the upsampler interpolates the odd phase, the decimator
//  low-passes the 2x signal before dropping every other sample. Latency: HB_M samples each way.
const HB_M: i32 = 12;
const hbH = new StaticArray<f32>(HB_M);          // h[2k+1], k = 0 .. HB_M-1 (centre tap h[0] = 0.5)
function initHalfband(): void {
  const beta: f64 = 7.0; const i0b: f64 = besselI0(beta);
  let sum: f64 = 0.5;
  const tmp = new StaticArray<f64>(HB_M);
  for (let k = 0; k < HB_M; k++) {
    const j: f64 = <f64>(2 * k + 1);
    const sgn: f64 = (k & 1) == 0 ? 1.0 : -1.0;
    let r: f64 = j / <f64>(2 * HB_M); r = 1.0 - r * r; if (r < 0.0) r = 0.0;
    const w: f64 = besselI0(beta * Math.sqrt(r)) / i0b;
    tmp[k] = sgn / (Math.PI * j) * w;
    sum += 2.0 * tmp[k];
  }
  for (let k = 0; k < HB_M; k++) hbH[k] = <f32>(tmp[k] / sum);
}
class HbUp {
  buf: StaticArray<f32> = new StaticArray<f32>(64);
  n: i32 = 0;
  e: f32 = 0; o: f32 = 0;
  push(x: f32): void {
    unchecked(this.buf[this.n & 63] = x); this.n++;
    const c = this.n - 1 - HB_M;
    let acc: f32 = 0.0;
    for (let k = 0; k < HB_M; k++) acc += unchecked(hbH[k]) * (unchecked(this.buf[(c - k) & 63]) + unchecked(this.buf[(c + 1 + k) & 63]));
    this.o = <f32>2.0 * acc;
    this.e = unchecked(this.buf[c & 63]);
  }
  reset(): void { for (let i = 0; i < 64; i++) this.buf[i] = 0.0; this.n = 0; this.e = 0.0; this.o = 0.0; }
}
class HbDown {
  buf: StaticArray<f32> = new StaticArray<f32>(128);
  n: i32 = 0;
  push(a: f32, b: f32): f32 {
    unchecked(this.buf[this.n & 127] = a); unchecked(this.buf[(this.n + 1) & 127] = b); this.n += 2;
    const c = this.n - 2 * HB_M;
    let acc: f32 = <f32>0.5 * unchecked(this.buf[c & 127]);
    for (let k = 0; k < HB_M; k++) acc += unchecked(hbH[k]) * (unchecked(this.buf[(c - 1 - 2 * k) & 127]) + unchecked(this.buf[(c + 1 + 2 * k) & 127]));
    return acc;
  }
  reset(): void { for (let i = 0; i < 128; i++) this.buf[i] = 0.0; this.n = 0; }
}


// =====================================================================
//  keys.ts — the 44-key keyboard (F … C), its sample-and-hold pitch CV and the glide.
//
//  The hardware: a constant-current source feeds a string of 43 × 10 Ω 1 % resistors, so each key
//  taps ~84 mV (1 V/oct) above the bottom F (0 V). The lowest key held wins (reissue: HIGH / LAST
//  too). A sample-and-hold keeps the pitch after the last key is released (so the release tail sounds
//  at the last pitch); GLIDE is the S/H capacitor charging through a 5 MΩ audio pot — an exponential
//  approach in pitch. The trigger bus is high while ANY key is down: overlapped keys do not
//  re-trigger the contours (single trigger); the reissue's MULTI mode does.
// =====================================================================

const HMAX: i32 = 64;
const hId = new StaticArray<i32>(HMAX);
const hKey = new StaticArray<i32>(HMAX);           // key index: 0 = bottom F (MIDI 41)
let hN: i32 = 0;

let kTarget: f32 = 0.0;           // pitch the S/H follows (semitones above the bottom F)
let kCur: f32 = 0.0;              // glided pitch
let kHeldKey: i32 = -1000;        // key currently selected
let kGateWant: bool = false;
let kGateOut: bool = false;
let kLowT: f32 = 1.0;
let glideTau: f32 = 0.0;          // seconds (0 = no glide)

function hFind(id: i32): i32 { for (let i = 0; i < hN; i++) if (hId[i] == id) return i; return -1; }
function hRemoveAt(i: i32): void {
  for (let j = i; j < hN - 1; j++) { hId[j] = hId[j + 1]; hKey[j] = hKey[j + 1]; }
  hN--;
}

// key index → pitch in semitones above the bottom F, through the selected scale (+ vintage resistor error)
function keyPitch(idx: i32): f32 {
  const sc = pi(P_SCALE);
  let st: f32 = f32(idx);
  if (sc == 1 || sc == 2) {
    const m = 41 + idx;                                       // MIDI note of this key
    const pc = ((m % 12) + 12) % 12;
    st += unchecked(SCALE_DEV[(sc - 1) * 12 + pc]);
  } else if (sc == 3) {
    const oct = idx >= 0 ? idx / 43 : -((-idx + 42) / 43);
    const r = idx - oct * 43;
    st = f32(oct * 12) + unchecked(PARTCH[r]);
  }
  if (pi(P_KEY_ERR) != 0 && idx >= 0 && idx < 44) st += unchecked(KEYERR[idx]);
  return st;
}

function keyboardUpdate(newKey: bool): void {
  if (hN == 0 || pi(P_LOCAL) == 0) { kGateWant = false; return; }
  const pri = pi(P_KEY_PRI);
  let best: i32 = 0;
  for (let i = 1; i < hN; i++) {
    if (pri == 0) { if (hKey[i] < hKey[best]) best = i; }
    else if (pri == 1) { if (hKey[i] > hKey[best]) best = i; }
    else best = i;                                            // LAST
  }
  const k = hKey[best];
  const wasHigh = kGateWant || kGateOut;
  if (k != kHeldKey) {
    kHeldKey = k;
    kTarget = keyPitch(k);
    if (glideTau <= 0.0 || pi(P_GLIDE_ON) == 0) kCur = kTarget;
  }
  // multi-trigger: ANY new key while the gate is high drops the gate for a moment (even if the lower key keeps the pitch)
  if (newKey && wasHigh && pi(P_TRIG_MODE) == 1) { kGateOut = false; kLowT = 0.0; }
  kGateWant = true;
}

function keyOn(id: i32, key: i32): void {
  const f = hFind(id);
  if (f >= 0) hRemoveAt(f);
  if (hN >= HMAX) hRemoveAt(0);
  hId[hN] = id; hKey[hN] = key; hN++;
  keyboardUpdate(true);
}
function keyOff(id: i32): void {
  const f = hFind(id);
  if (f < 0) return;
  hRemoveAt(f);
  keyboardUpdate(false);
}
function allNotesOff(): void { hN = 0; kGateWant = false; }

function keysTick(dt: f32): void {
  if (kGateWant) {
    if (!kGateOut) { if (kLowT >= 0.0015) kGateOut = true; else kLowT += dt; }
  } else { if (kGateOut) kLowT = 0.0; else if (kLowT < 1.0) kLowT += dt; kGateOut = false; }
  const diff = kTarget - kCur;
  if (pi(P_GLIDE_ON) == 0 || glideTau <= 0.0) kCur = kTarget;
  else kCur += diff * (<f32>1.0 - Mathf.exp(-dt / glideTau));
}


// =====================================================================
//  main.ts — Doob engine glue: the signal path of the Minimoog Model D
//
//    keyboard S/H + glide ─┬→ OSC 1 ─┐
//    TUNE / pitch wheel ───┤ OSC 2 ──┤  mixer (5 sources, overloads) → ladder filter → VCA 1 → VCA 2 / volume
//    modulation bus ───────┤ OSC 3 ──┘                 ↑ filter contour + keyboard 1/3, 2/3 + modulation
//    noise / ext preamp ───┘                           loudness contour → VCA 1
//
//  plus the modulation mix amp (OSC 3 ⇄ noise through the MOD wheel), the two contour generators,
//  the A-440 reference, the external-input preamp with its overload lamp, the MIDI map and the ABI
//  exports (see src/WasmAbi.h).
// =====================================================================

const osc1 = new GOsc(); const osc2 = new GOsc(); const osc3 = new GOsc();
const lfo = new GOsc();
const cF = new Contour(); const cL = new Contour();
const nz = new Noise();                            // audio noise (2x rate)
const nzM = new Noise();                           // modulation noise (base rate)
const lad = new Ladder();
const dcO = new Hp1();
const upA = new HbUp(); const upB = new HbUp(); const upC = new HbUp(); const upE = new HbUp();
const dnF = new HbDown();

// derived controls -------------------------------------------------------------------------
let tCut: f32 = 0.0; let smCut: f32 = 0.0;
let tEmph: f32 = 0.0; let smEmph: f32 = 0.0;
let tV1: f32 = 0.0; let tV2: f32 = 0.0; let tV3: f32 = 0.0; let tVE: f32 = 0.0; let tVN: f32 = 0.0;
let sV1: f32 = 0.0; let sV2: f32 = 0.0; let sV3: f32 = 0.0; let sVE: f32 = 0.0; let sVN: f32 = 0.0;
let tVol: f32 = 0.0; let sVol: f32 = 0.0;
let smCoef: f32 = 0.01;
let aF: f32 = 0.01; let dF: f32 = 0.1; let sF: f32 = 0.3;
let aL: f32 = 0.01; let dL: f32 = 0.1; let sL: f32 = 1.0;
let g3n: f32 = 1.0; let gNn: f32 = 0.0;           // modulation-mix gains (osc 3 side / noise side), 1.0 = full
let hiBend: f32 = 0.0;
let lfoHz: f32 = 4.0;
let drift1: f32 = 0.0; let drift2: f32 = 0.0; let drift3: f32 = 0.0;
let driftA: f32 = 0.0; let driftScale: f32 = 0.0;
let ccBend: f32 = 0.0;
let rpnSel: i32 = 16383; let rpnMsb: i32 = 127; let rpnLsb: i32 = 127;
let a440Ph: f32 = 0.0;
let lampT: f32 = 0.0;
let lastOut: f32 = 0.0;
let peakOut: f32 = 0.0;
let lastCutHz: f32 = 440.0; let lastK: f32 = 0.0;
let nO1: f32 = 0.0; let nO2: f32 = 0.0; let nO3: f32 = 0.0;
let nMix: f32 = 0.0; let nFil: f32 = 0.0; let nVca: f32 = 0.0; let nNoise: f32 = 0.0; let nBus: f32 = 0.0;
let nF1: f32 = 0.0; let nF2: f32 = 0.0; let nF3: f32 = 0.0; let nLfo: f32 = 0.0;
const F2_HZ: f32 = 87.30706;                       // bottom F at 8'
const ENV_OCT: f32 = 8.5;                          // full AMOUNT OF CONTOUR sweeps the cutoff 8.5 octaves
const MOD_OCT: f32 = 1.0;                          // full modulation = ±1 octave on pitch / filter

export function transport(playing: i32, ppq: f64, bpm: f32): void { setHostTransport(playing, ppq, bpm); }
export function getInputPtr(): usize  { return changetype<usize>(inBuf); }
export function getOutputPtr(): usize { return changetype<usize>(outBuf); }
export function getParamsPtr(): usize { return changetype<usize>(params); }
export function getNumParams(): i32   { return NUM_PARAMS; }
export function getDisplayPtr(): usize { return changetype<usize>(display); }
export function paramValue(i: i32): f32 { return i >= 0 && i < NP ? A[i] : <f32>0.0; }
// test / diagnostic probes of internal nodes (value after the last processed sample)
export function dbgNode(i: i32): f32 {
  if (i == 0) return nO1; if (i == 1) return nO2; if (i == 2) return nO3; if (i == 3) return nMix; if (i == 4) return nFil;
  if (i == 5) return nVca; if (i == 6) return nNoise; if (i == 7) return nBus; if (i == 8) return nF1; if (i == 9) return nF2;
  if (i == 10) return nF3; if (i == 11) return nLfo; if (i == 12) return lastOut; if (i == 13) return lastCutHz; if (i == 14) return lastK;
  if (i == 15) return cF.v; if (i == 16) return cL.v; if (i == 17) return kCur; if (i == 18) return kGateOut ? <f32>1.0 : <f32>0.0;
  if (i == 19) return f32(hN); if (i == 20) return lampT;
  return 0.0;
}

@inline function taper(x: f32): f32 { return (Mathf.exp(<f32>4.39 * x) - <f32>1.0) * <f32>0.012658; }   // audio taper: 10 % at mid-travel
@inline function rangeOct(r: i32): f32 { return r == 0 ? <f32>-5.0 : f32(r - 3); }                       // LO, 32', 16', 8', 4', 2'

// ---------------------------------------------------------------------------- init
export function init(sr: f32, maxFrames: i32, numChannels: i32): void {
  SR = sr > 0.0 ? sr : <f32>48000.0; invSR = <f32>1.0 / SR;
  rng = 0x9e3779b9;
  initSin(); initBlep(); initHalfband();
  for (let i = 0; i < MAX_PARAMS; i++) { params[i] = 0.0; slotCache[i] = -1.0; }
  for (let i = 0; i < NP; i++) { A[i] = 0.0; An[i] = 0.0; AI[i] = 0; RH[i] = -1; AH[i] = -1.0e9; }
  setDefaults();
  refreshParams();
  for (let i = 0; i < MAX_FRAMES * 2; i++) inBuf[i] = 0.0;
  osc1.reset(); osc2.reset(); osc3.reset(); lfo.reset(); osc2.ph = 0.31; osc3.ph = 0.67;
  cF.reset(); cL.reset(); cF.kA = 2.36; cL.kA = 2.0;
  nz.reset(); nz.setup(); nzM.reset(); nzM.setup(); lad.reset(); dcO.s = 0.0;
  upA.reset(); upB.reset(); upC.reset(); upE.reset(); dnF.reset();
  smCoef = <f32>1.0 - Mathf.exp(-<f32>1.0 * invSR / <f32>0.004);
  driftA = onePoleA(0.3); driftScale = Mathf.sqrt(<f32>6.0 / driftA);
  drift1 = 0.0; drift2 = 0.0; drift3 = 0.0;
  hN = 0; kTarget = 0.0; kCur = 0.0; kHeldKey = -1000; kGateWant = false; kGateOut = false; kLowT = 1.0;
  ccBend = 0.0; rpnSel = 16383; a440Ph = 0.0; lampT = 0.0; lastOut = 0.0; peakOut = 0.0;
  for (let i = 0; i < 128; i++) ccMsb[i] = 0;
  for (let i = 0; i < 16; i++) display[i] = 0.0;
  paramsDirty = true; onParams();
  smCut = tCut; smEmph = tEmph; sV1 = tV1; sV2 = tV2; sV3 = tV3; sVE = tVE; sVN = tVN; sVol = tVol;
}
const ccMsb = new StaticArray<i32>(128);

// ---------------------------------------------------------------------------- parameter-derived values
function onParams(): void {
  paramsDirty = false;
  tCut = <f32>-5.0 + <f32>10.0 * pv(P_CUTOFF);                       // panel scale -5 … +5 (octaves; 440 Hz at -1)
  const x = pv(P_EMPH);
  tEmph = x;
  tV1 = pi(P_SW_O1) != 0 ? pv(P_VOL1) : <f32>0.0; tV2 = pi(P_SW_O2) != 0 ? pv(P_VOL2) : <f32>0.0; tV3 = pi(P_SW_O3) != 0 ? pv(P_VOL3) : <f32>0.0;
  tVE = pi(P_SW_EXT) != 0 ? pv(P_VOLEXT) : <f32>0.0; tVN = pi(P_SW_NZ) != 0 ? pv(P_VOLNZ) : <f32>0.0;
  const v = pv(P_OUTVOL);
  tVol = pi(P_MAIN_ON) != 0 ? <f32>2.0 * v * v : <f32>0.0;
  const ms: f32 = 0.001;
  aF = ms + (<f32>9.0 - ms) * taper(pv(P_FATK));  dF = ms + (<f32>30.0 - ms) * taper(pv(P_FDEC)); sF = pv(P_FSUS);
  aL = ms + (<f32>14.0 - ms) * taper(pv(P_LATK)); dL = ms + (<f32>30.0 - ms) * taper(pv(P_LDEC)); sL = pv(P_LSUS);
  glideTau = <f32>0.00033 + <f32>2.2 * taper(pv(P_GLIDE));
  // modulation-mix pan pot (25 K, wiper to ground) with the 24 K input resistors: the side the wiper leaves un-shorted passes
  const p = pv(P_MODMIX);
  const ro: f32 = <f32>25.0 * (<f32>1.0 - p); const rn: f32 = <f32>25.0 * p;
  g3n = (ro / (<f32>24.0 + ro)) * <f32>1.96; gNn = (rn / (<f32>24.0 + rn)) * <f32>1.96;
  lfoHz = <f32>0.1 * Mathf.pow(<f32>300.0, pv(P_LFO_RATE));
  keyboardUpdate(false);
}

// ---------------------------------------------------------------------------- MIDI in
function noteFromFreq(freq: f32): i32 {
  const m = i32(nearest<f32>(<f32>69.0 + <f32>12.0 * Mathf.log2(freq / <f32>440.0)));
  return m < 0 ? 0 : (m > 127 ? 127 : m);
}
export function noteOn(id: i32, freq: f32, vel: f32): void {
  refreshParams(); if (paramsDirty) onParams();
  if (id == -5) { allNotesOff(); return; }
  if (id < 0) return;
  keyOn(id, noteFromFreq(freq) - 41);
}
export function noteOff(id: i32): void {
  refreshParams(); if (paramsDirty) onParams();
  if (id < 0) return;
  keyOff(id);
}
export function controlChange(num: i32, value: f32): void {
  refreshParams();
  const v127: i32 = i32(nearest<f32>(value * <f32>127.0));
  if (num == 128) { ccBend = value; return; }
  if (num == 129) return;
  if (num == 120 || num == 123) { allNotesOff(); return; }
  if (num == 1) setParamN(P_MODW, value);
  else if (num == 33) setParamN(P_MODW, f32(ccMsb[1] * 128 + v127) / <f32>16383.0);
  else if (num == 122) setParamI(P_LOCAL, value >= 0.5 ? 1 : 0);
  else if (num == 101) { rpnMsb = v127; rpnSel = rpnMsb * 128 + rpnLsb; }
  else if (num == 100) { rpnLsb = v127; rpnSel = rpnMsb * 128 + rpnLsb; }
  else if (num == 6) { if (rpnSel == 0) setParamI(P_BEND, v127 < 1 ? 1 : (v127 > 12 ? 12 : v127)); }
  if (num < 128) ccMsb[num] = v127;
  if (paramsDirty) onParams();
}

// ---------------------------------------------------------------------------- one sample of the instrument
@inline function slew(c: f32, t: f32): f32 { return c + (t - c) * smCoef; }
@inline function waveA(w: i32, o3: bool): f32 { return w == 0 ? <f32>1.0 : (w == 1 ? (o3 ? <f32>0.0 : <f32>0.824) : <f32>0.0); }
@inline function waveB(w: i32, o3: bool): f32 { return w == 1 ? (o3 ? <f32>-1.0 : <f32>0.176) : (w == 2 ? <f32>1.0 : <f32>0.0); }
@inline function waveD(w: i32): f32 { return w == 3 ? <f32>0.5 : (w == 4 ? <f32>0.3333 : <f32>0.16667); }

function renderSample(inL: f32, inR: f32): f32 {
  smCut = slew(smCut, tCut); smEmph = slew(smEmph, tEmph);
  sV1 = slew(sV1, tV1); sV2 = slew(sV2, tV2); sV3 = slew(sV3, tV3); sVE = slew(sVE, tVE); sVN = slew(sVN, tVN); sVol = slew(sVol, tVol);

  // ---- keyboard / S&H / glide ----------------------------------------------------------------
  keysTick(invSR);
  const gate = (pi(P_STRIG) != 0) ? true : kGateOut;

  // ---- contours ---------------------------------------------------------------------------------
  const decOn = pi(P_DECAY_ON) != 0;
  const cf = cF.tick(gate, aF, dF, sF, decOn ? dF : <f32>-1.0);
  const cl = cL.tick(gate, aL, dL, sL, decOn ? dL : <f32>-1.0);

  // ---- modulation mix -> wheel ------------------------------------------------------------------------
  const wf = pv(P_MODW);
  const wheel = taper(wf);
  const lfoV = lfo.sample(lfoHz * invSR, pi(P_LFO_WAVE) == 0 ? 0 : 1, 1.0, 0.0, 0.5);
  nLfo = lfoV;
  const wn = white();
  const nModColor = pi(P_NZ_COLOR) == 0 ? nzM.pink(wn) : nzM.red(wn);          // WHITE position → pink mod noise; PINK → red
  const srcA: f32 = pi(P_MOD_A) == 0 ? nO3 : cf;
  const srcB: f32 = pi(P_MOD_B) == 0 ? nModColor : lfoV;
  const bus: f32 = wheel * (g3n * srcA + gNn * srcB) * MOD_OCT;                // octaves
  nBus = bus;

  // ---- oscillators -----------------------------------------------------------------------------------------
  const local = pi(P_LOCAL) != 0;
  const bn = clampf(pv(P_PITCHW) + ccBend, -1.0, 1.0);
  const bendOct: f32 = bn * f32(pi(P_BEND)) * <f32>0.0833333;
  const tuneOct: f32 = pv(P_TUNE) * <f32>0.3333333;
  const kbOct: f32 = local ? kCur * <f32>0.0833333 : <f32>0.0;
  const modOct: f32 = pi(P_OSC_MOD) != 0 ? bus : <f32>0.0;
  const dr = pv(P_DRIFT);
  drift1 += (white() - drift1) * driftA; drift2 += (white() - drift2) * driftA; drift3 += (white() - drift3) * driftA;
  const dk = driftScale * dr * <f32>0.0022;                                   // ~±2.6 cents at full DRIFT (octaves)
  const bl = pv(P_BLEED) * <f32>0.002;
  const o3ctl = pi(P_O3_CTRL) != 0;
  const base: f32 = tuneOct + bendOct + modOct;
  const cv1 = rangeOct(pi(P_O1_RANGE)) + kbOct + base + drift1 * dk + bl * nO2;
  const cv2 = rangeOct(pi(P_O2_RANGE)) + kbOct + base + drift2 * dk + pv(P_O2_FREQ) * <f32>0.5833333 + bl * nO1;
  const cv3 = rangeOct(pi(P_O3_RANGE)) + (o3ctl ? kbOct : <f32>0.0) + base + drift3 * dk + (o3ctl ? pv(P_O3_FREQ) * <f32>0.5833333 : pv(P_O3_FREQ) * <f32>3.0) + bl * nO2;
  nF1 = F2_HZ * exp2f(clampf(cv1, -9.0, 7.0)); nF2 = F2_HZ * exp2f(clampf(cv2, -9.0, 7.0)); nF3 = F2_HZ * exp2f(clampf(cv3, -9.0, 7.0));
  const w1 = pi(P_O1_WAVE), w2 = pi(P_O2_WAVE), w3 = pi(P_O3_WAVE);
  const k1: i32 = w1 >= 3 ? 1 : 0, k2: i32 = w2 >= 3 ? 1 : 0, k3: i32 = w3 >= 3 ? 1 : 0;
  nO1 = osc1.sample(nF1 * invSR, k1, waveA(w1, false), waveB(w1, false), waveD(w1));
  nO2 = osc2.sample(nF2 * invSR, k2, waveA(w2, false), waveB(w2, false), waveD(w2));
  nO3 = osc3.sample(nF3 * invSR, k3, waveA(w3, true), waveB(w3, true), waveD(w3));

  // ---- external input preamp + overload lamp ----------------------------------------------------------------
  const fbOn = pi(P_FEEDBACK) != 0;
  const extRaw = (inL + inR) * <f32>0.5 + (fbOn ? lastOut * <f32>0.9 : <f32>0.0);
  const pre = extRaw * pv(P_VOLEXT) * <f32>8.0;
  if (absf(pre) > 1.0) lampT = 0.06; else if (lampT > 0.0) lampT -= invSR;
  const extN = softclip(pre * <f32>0.8) * <f32>1.25;

  // ---- MIXER + FILTER at 2x the sample rate ---------------------------------------------------------------------
  upA.push(nO1); upB.push(nO2); upC.push(nO3); upE.push(extN);
  const trkMode = (pi(P_KB1) != 0 ? <f32>0.3333 : <f32>0.0) + (pi(P_KB2) != 0 ? <f32>0.6667 : <f32>0.0);
  const filModOct: f32 = pi(P_FIL_MOD) != 0 ? bus : <f32>0.0;
  const cutOct = smCut + <f32>1.0 + trkMode * (local ? kCur * <f32>0.0833333 : <f32>0.0) + ENV_OCT * pv(P_CONTOUR) * cf + filModOct;
  const fc = clampf(<f32>440.0 * exp2f(clampf(cutOct, -7.0, 9.0)), 10.0, SR * <f32>0.8);
  lastCutHz = fc;
  const gF = Mathf.tan(PI * fc * invSR * <f32>0.5);                              // the ladder runs at 2·SR
  // EMPHASIS: audio-taper pot. Regeneration starts at 7.5 (k = 4); the loop gain droops at low cutoff frequencies
  const kRaw: f32 = <f32>4.0 * taper(smEmph) / <f32>0.3278;
  const kDroop: f32 = clampf(<f32>0.62 + <f32>0.38 * Mathf.log2(fc * <f32>0.0125) * <f32>0.4, 0.62, 1.0);
  const kk = minf(kRaw, <f32>7.0) * kDroop;
  lastK = kk;
  const col = pi(P_NZ_COLOR);
  let sumA: f32 = 0.0; let sumB: f32 = 0.0; let filA: f32 = 0.0; let filB: f32 = 0.0;
  for (let ph = 0; ph < 2; ph++) {
    const a1 = ph == 0 ? upA.e : upA.o, a2 = ph == 0 ? upB.e : upB.o, a3 = ph == 0 ? upC.e : upC.o, ae = ph == 0 ? upE.e : upE.o;
    const w = white();
    const nzv: f32 = col == 0 ? w : nz.pink(w) * <f32>3.2;
    const sm: f32 = a1 * sV1 + a2 * sV2 + a3 * sV3 + ae * sVE + nzv * sVN;
    const y = lad.tick(sm, gF, kk);
    if (ph == 0) { sumA = sm; filA = y; } else { sumB = sm; filB = y; }
  }
  nMix = <f32>0.5 * (sumA + sumB);
  nNoise = wn;
  const fil = dnF.push(filA, filB);
  nFil = fil;

  // ---- loudness: VCA 1 (contour), A-440 into VCA 2, volume ---------------------------------------------------------
  const vca = fil * cl;
  nVca = vca;
  a440Ph += <f32>440.0 * invSR; if (a440Ph >= 1.0) a440Ph -= 1.0;
  const ref: f32 = pi(P_A440) != 0 ? (fsin(a440Ph) + <f32>0.035 * fsin(a440Ph * <f32>2.0) + <f32>0.012 * fsin(a440Ph * <f32>3.0)) * <f32>0.28 : <f32>0.0;
  const out = dcO.tick((vca + ref) * <f32>0.8 * sVol, <f32>0.0005);
  lastOut = out;
  return out;
}

export function process(n: i32): void {
  refreshParams();
  if (paramsDirty) onParams();
  for (let i = 0; i < n; i++) {
    const inl = unchecked(inBuf[i]);
    const inr = unchecked(inBuf[MAX_FRAMES + i]);
    let o = kneeClip(finite(renderSample(inl, inr)), 0.85, 1.0);
    unchecked(outBuf[i] = o);
    unchecked(outBuf[MAX_FRAMES + i] = o);
    const ao = absf(o);
    peakOut = ao > peakOut ? ao : peakOut * <f32>0.99995;
  }
  display[0] = lampT > 0.0 ? <f32>1.0 : <f32>0.0;
  display[1] = kGateOut ? <f32>1.0 : <f32>0.0;
  display[2] = cF.v; display[3] = cL.v;
  display[4] = lfo.ph < 0.5 ? <f32>1.0 : <f32>0.0;
  display[5] = peakOut;
  display[6] = kCur;
}
