#!/usr/bin/env node
// =====================================================================
//  cataclysm/build.mjs — assemble the CATACLYSM plugin.
//    node factory/cataclysm/build.mjs [--pack] [--no-gui]
//  → factory/plugins/cataclysm/{assembly.ts, gui.html, spec.json}
//    (a .vstai carries ONE source file and ONE gui.html, so sources are
//     pasted together: generated tables + dsp/core + voice + fx + main)
// =====================================================================
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { P, SLOT_MAX, MOD_DESTS, TABS } from "./params.mjs";
import { L, assertFits, slotDefaults } from "./pack.mjs";
import { PRESETS } from "./presets.mjs";
import { EXPLANATION } from "./explanation.mjs";
import { MAT_R, MET_R } from "./tables.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const out = join(root, "factory/plugins/cataclysm");
const rd = (p) => readFileSync(join(here, p), "utf8");
assertFits();

const FX_TABS = new Set(["drive", "filter", "eqdyn", "space"]);
const f32 = (v) => { const s = String(Number(v)); return /[.e]/i.test(s) ? s : s + ".0"; };

// ---------- generated DSP tables ----------
function generated() {
  const idx = P.map((p, i) => `const P_${p.key}: i32 = ${i};`);
  const arr = (name, type, fn) => `const ${name}: StaticArray<${type}> = [${P.map(fn).join(", ")}];`;
  const dests = [-1, ...MOD_DESTS.map((d) => P.indexOf(d))];
  while (dests.length < 64) dests.push(-1);
  const defs = slotDefaults();
  return [
    `const NP: i32 = ${P.length};`,
    `const NUM_PARAMS: i32 = ${L.slots};`,
    ...idx,
    arr("PSLOT", "i32", (p) => p.slot),
    arr("PMULT", "i32", (p) => p.mult),
    arr("PSTEPS", "i32", (p) => p.steps),
    arr("PCURVE", "i32", (p) => (p.curve === "exp" ? 1 : p.curve === "int" ? 2 : 0)),
    arr("PDIRECT", "i32", (p) => (p.direct ? 1 : 0)),
    arr("PIS_FX", "i32", (p) => (FX_TABS.has(p.tab) ? 1 : 0)),
    arr("PMIN", "f32", (p) => f32(p.min)),
    arr("PMAX", "f32", (p) => f32(p.max)),
    arr("PLNR", "f32", (p) => (p.curve === "exp" ? f32(Math.log(p.max / p.min)) : "0.0")),
    `const MAT_R: StaticArray<f32> = [${MAT_R.flat().map(f32).join(", ")}];`,
    `const MET_R: StaticArray<f32> = [${MET_R.flat().map(f32).join(", ")}];`,
    `const MOD_DEST_PARAM: StaticArray<i32> = [${dests.join(", ")}];`,
    "function setDefaults(): void {",
    ...defs.map((v, s) => `  params[${s}] = ${f32(v)};`),
    "}",
  ].join("\n");
}

function buildDsp() {
  const files = ["dsp/core.ts", "dsp/voice.ts", "dsp/fx.ts", "dsp/main.ts"];
  const header = [
    "// =====================================================================",
    "//  CATACLYSM — GENERATED by factory/cataclysm/build.mjs. Edit the sources:",
    "//    factory/cataclysm/params.mjs   (parameter table + packing)",
    ...files.map((f) => `//    factory/cataclysm/${f}`),
    "// =====================================================================",
  ].join("\n");
  const core = rd(files[0]);
  // the generated tables must precede core.ts (it declares arrays sized NP)
  return [header, generated(), core, ...files.slice(1).map(rd)].join("\n\n");
}

// ---------- spec.json ----------
function buildSpec() {
  const slots = [];
  for (let s = 0; s < L.slots; s++) {
    const members = P.filter((p) => p.slot === s);
    const d = members.find((p) => p.direct);
    const dv = slotDefaults();
    slots.push(d
      ? { name: d.name, index: s, min: d.min, max: d.max, default: d.def }
      : { name: `Pack ${String(s).padStart(2, "0")}`, index: s, min: 0, max: SLOT_MAX, default: dv[s] });
  }
  return {
    name: "Cataclysm",
    isInstrument: true,
    explanation: EXPLANATION.replace(/256/g, String(P.length)),
    assembly: "factory/plugins/cataclysm/assembly.ts",
    out: "factory/plugins/cataclysm/x.vstai",
    guiFile: "factory/plugins/cataclysm/gui.html",
    publishedAt: Date.now(),
    theme: { accent: "#ff4a3d", accent2: "#ffb347" },
    params: slots,
  };
}

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "assembly.ts"), buildDsp());
writeFileSync(join(out, "spec.json"), JSON.stringify(buildSpec(), null, 2) + "\n");
console.log(`assembly.ts + spec.json written  (${P.length} controls in ${L.slots} host slots)`);

if (!process.argv.includes("--no-gui") && existsSync(join(here, "gui/build-gui.mjs"))) {
  const { buildGui } = await import("./gui/build-gui.mjs");
  writeFileSync(join(out, "gui.html"), buildGui());
  console.log("gui.html written");
}
if (process.argv.includes("--pack")) {
  execFileSync("node", [join(root, "factory/tools/pack-vstai.mjs"), join(out, "spec.json")], { stdio: "inherit" });
}
