// =====================================================================

//  Tessitura — GENERATED by factory/drums/build.mjs. Edit the sources:

//    factory/drums/../strings/core.ts

//    factory/drums/../strings/section.ts

//    factory/drums/../strings/tessitura.ts

// =====================================================================

// =====================================================================
//  strings/core.ts — shared engine for the string instruments.
//  Pasted into each plugin's assembly.ts by strings/build.mjs (a .vstai
//  carries one source file). Allocation-free after init, all f32.
//
//  The bowed string follows the digital-waveguide model of McIntyre,
//  Schumacher & Woodhouse as implemented in Perry Cook & Gary Scavone's
//  Synthesis ToolKit ("Bowed"): two delay lines either side of the bow
//  contact point, an inverting nut, a lossy low-passed bridge, and a
//  nonlinear bow-friction table — the stick-slip interaction that makes a
//  bowed string speak. Bow force shapes the friction table, bow velocity
//  drives the string, bow position splits the delay lines.
// =====================================================================

const MAX_FRAMES: i32 = 8192;
const MAX_CHANNELS: i32 = 2;
const MAX_PARAMS: i32 = 64;
const PI: f32 = 3.14159265358979;
const TWO_PI: f32 = 6.28318530717959;

const inBuf  = new StaticArray<f32>(MAX_FRAMES * MAX_CHANNELS);
const outBuf = new StaticArray<f32>(MAX_FRAMES * MAX_CHANNELS);
const params = new StaticArray<f32>(MAX_PARAMS);
const display = new StaticArray<f32>(16);

let SR: f32 = 48000.0;
let invSR: f32 = 1.0 / 48000.0;

@inline function clampf(x: f32, lo: f32, hi: f32): f32 { return x < lo ? lo : (x > hi ? hi : x); }
@inline function lerpf(a: f32, b: f32, t: f32): f32 { return a + (b - a) * t; }
function decayCoef(tau: f32): f32 { if (tau <= 0.00001) return 0.0; return Mathf.exp(-invSR / tau); }
@inline function smoothCoef(tau: f32): f32 { return 1.0 - decayCoef(tau); }

let rng: u32 = 0x6d2b79f5;
@inline function white(): f32 { rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5; return f32(rng) * 4.656612873e-10 - 1.0; }
@inline function rand01(): f32 { return (white() + 1.0) * 0.5; }
// A smooth sine-shaped LFO for ph in [0,1) (a shaped triangle) — cheap, and plenty for vibrato.
@inline function fastSin01(ph: f32): f32 {
  const x = ph < 0.5 ? ph * 4.0 - 1.0 : 3.0 - ph * 4.0;     // triangle −1..1 (−1 at 0, +1 at 0.5)
  return x * (1.5 - 0.5 * x * x) * 1.0;
}

// ---- delay line with linear interpolation (read at fractional delay) ----
class Delay {
  buf: StaticArray<f32>; size: i32; w: i32 = 0; len: f32 = 1.0; last: f32 = 0;
  constructor(size: i32) { this.size = size; this.buf = new StaticArray<f32>(size); }
  clear(): void { for (let i = 0; i < this.size; i++) unchecked(this.buf[i] = 0); this.w = 0; this.last = 0; }
  setLen(d: f32): void { this.len = clampf(d, 1.0, f32(this.size - 2)); }
  // write x, return the sample from `len` ago
  tick(x: f32): f32 {
    unchecked(this.buf[this.w] = x);
    let rp = f32(this.w) - this.len;
    if (rp < 0.0) rp += f32(this.size);
    const i0 = i32(rp); const fr = rp - f32(i0);
    const i1 = i0 + 1 >= this.size ? 0 : i0 + 1;
    this.last = unchecked(this.buf[i0]) * (1.0 - fr) + unchecked(this.buf[i1]) * fr;
    this.w++; if (this.w >= this.size) this.w = 0;
    return this.last;
  }
  // peek `d` samples back without writing
  read(d: f32): f32 {
    let rp = f32(this.w) - 1.0 - clampf(d, 0.0, f32(this.size - 2));
    if (rp < 0.0) rp += f32(this.size);
    const i0 = i32(rp); const fr = rp - f32(i0);
    const i1 = i0 + 1 >= this.size ? 0 : i0 + 1;
    return unchecked(this.buf[i0]) * (1.0 - fr) + unchecked(this.buf[i1]) * fr;
  }
}

// ---- filters ------------------------------------------------------------
class Svf {
  ic1: f32 = 0; ic2: f32 = 0; a1: f32 = 0; a2: f32 = 0; a3: f32 = 0; k: f32 = 1;
  lp: f32 = 0; bp: f32 = 0; hp: f32 = 0;
  set(fc: f32, q: f32): void {
    const g = Mathf.tan(PI * clampf(fc, 8.0, SR * 0.45) * invSR);
    this.k = 1.0 / (q < 0.05 ? 0.05 : q);
    this.a1 = 1.0 / (1.0 + g * (g + this.k)); this.a2 = g * this.a1; this.a3 = g * this.a2;
  }
  tick(x: f32): void {
    const v3 = x - this.ic2;
    const v1 = this.a1 * this.ic1 + this.a2 * v3;
    const v2 = this.ic2 + this.a2 * this.ic1 + this.a3 * v3;
    this.ic1 = 2.0 * v1 - this.ic1; this.ic2 = 2.0 * v2 - this.ic2;
    this.lp = v2; this.bp = v1; this.hp = x - this.k * v1 - v2;
  }
  reset(): void { this.ic1 = 0; this.ic2 = 0; }
}
class OnePole {
  z: f32 = 0; a: f32 = 1;
  set(fc: f32): void { this.a = 1.0 - Mathf.exp(-TWO_PI * clampf(fc, 1.0, SR * 0.45) * invSR); }
  lp(x: f32): f32 { this.z += this.a * (x - this.z); return this.z; }
  hp(x: f32): f32 { this.z += this.a * (x - this.z); return x - this.z; }
}

// 2^x, fast: polynomial on the fraction, exponent bits for the integer part
// (≈0.2 cent error) — for per-player pitch offsets computed every sample.
@inline function fastExp2(x: f32): f32 {
  const xi = Mathf.floor(x); const f = x - xi;
  const p: f32 = 1.0 + f * (0.6931472 + f * (0.2402265 + f * 0.0555041));
  const e = i32(xi) + 127;
  if (e <= 0) return 0.0;
  return p * reinterpret<f32>((e < 255 ? e : 254) << 23);
}

@inline function softclip(x: f32): f32 {
  if (x > 3.0) return 1.0; if (x < -3.0) return -1.0;
  const x2 = x * x; return x * (27.0 + x2) / (27.0 + 9.0 * x2);
}

// ---- the bowed string ----------------------------------------------------
// STK bow table: friction reflection vs. relative velocity. slope sets how
// "grippy" the bow is (lower = more force = more rasp).
@inline function bowTable(dv: f32, slope: f32): f32 {
  let s = Mathf.abs((dv + 0.001) * slope) + 0.75;
  s = s * s; s = 1.0 / (s * s);                    // s^-4
  return s > 0.98 ? 0.98 : (s < 0.01 ? 0.01 : s);
}

const MAX_STRING_DELAY: i32 = 2600;                // ≥ SR/lowest note at 96 kHz headroom
class BowedString {
  neck: Delay = new Delay(MAX_STRING_DELAY);
  bridge: Delay = new Delay(MAX_STRING_DELAY);
  loss: OnePole = new OnePole();                    // bridge losses (brightness)
  lossGain: f32 = 0.995;
  freq: f32 = 220; beta: f32 = 0.127;                // bow position (fraction from bridge)
  bowVel: f32 = 0;                                   // target set per sample by the player
  force: f32 = 0.5;                                  // 0..1 → friction slope
  pluck: f32 = 0;                                    // pluck energy to inject (pizzicato)
  out: f32 = 0;
  clear(): void { this.neck.clear(); this.bridge.clear(); this.loss.z = 0; this.out = 0; this.delayF = -1.0; }
  // The loss filter's phase delay is cached: it only moves noticeably when
  // the pitch moves by more than ~1 % or the brightness changes, so vibrato
  // doesn't pay for atan2/sin/cos every sample.
  lossFc: f32 = -1.0; lossDelay: f32 = 0.0; delayF: f32 = -1.0;
  setFreq(f: f32): void {
    this.freq = f;
    if (this.delayF <= 0.0 || Mathf.abs(f - this.delayF) > this.delayF * 0.01) {
      const w = TWO_PI * f * invSR;
      const c: f32 = 1.0 - this.loss.a;
      this.lossDelay = Mathf.atan2(c * Mathf.sin(w), 1.0 - c * Mathf.cos(w)) / w;
      this.delayF = f;
    }
    // loop = both delay lines + 1 sample latency each + the loss filter's
    // phase delay: subtract the last two so the loop is exactly one period
    const base = SR / f - 2.0 - this.lossDelay;
    this.bridge.setLen(base * this.beta);
    this.neck.setLen(base * (1.0 - this.beta));
  }
  setBrightness(fc: f32): void {
    if (Mathf.abs(fc - this.lossFc) < 1.0) return;
    this.loss.set(fc); this.lossFc = fc; this.delayF = -1.0;
  }
  tick(): f32 {
    const bridgeRefl = -this.loss.lp(this.bridge.last) * this.lossGain;
    const nutRefl = -this.neck.last;
    const stringVel = bridgeRefl + nutRefl;
    const dv = this.bowVel - stringVel;
    let nv: f32 = 0.0;
    if (this.bowVel != 0.0) nv = dv * bowTable(dv, 5.0 - 4.0 * this.force);
    let inj: f32 = 0.0;
    if (this.pluck != 0.0) { inj = this.pluck; this.pluck = 0.0; }
    this.neck.tick(bridgeRefl + nv + inj);
    this.bridge.tick(nutRefl + nv + inj);
    this.out = this.bridge.last;
    return this.out;
  }
}

// ---- instrument bodies: modal resonators on the bridge force ---------------
// Mode frequencies/Qs for each family, from published violin-family
// acoustics (air mode A0, main corpus modes, and the ~2–3 kHz bridge hill),
// scaled by body size for viola/cello/bass.
class Body {
  modes: StaticArray<Svf> = new StaticArray<Svf>(7);
  gains: StaticArray<f32> = new StaticArray<f32>(7);
  hp: OnePole = new OnePole();
  constructor() { for (let i = 0; i < 7; i++) this.modes[i] = new Svf(); }
  // kind: 0 violin, 1 viola, 2 cello, 3 bass
  configure(kind: i32): void {
    const f: StaticArray<f32> = [275.0, 460.0, 550.0, 700.0, 1100.0, 2400.0, 3300.0];
    const q: StaticArray<f32> = [12.0, 14.0, 12.0, 8.0, 5.0, 2.2, 3.0];
    const g: StaticArray<f32> = [0.9, 0.8, 1.0, 0.55, 0.45, 0.85, 0.35];
    const scale: f32 = kind == 0 ? 1.0 : (kind == 1 ? 0.83 : (kind == 2 ? 0.45 : 0.29));
    for (let i = 0; i < 7; i++) {
      // the bridge hill scales far less than the corpus modes
      const s: f32 = i >= 5 ? Mathf.sqrt(scale) : scale;
      unchecked(this.modes[i]).set(f[i] * s, q[i]);
      unchecked(this.modes[i]).reset();
      this.gains[i] = g[i];
    }
    this.hp.set(kind >= 2 ? 30.0 : 80.0);
  }
  tick(x: f32): f32 {
    let y: f32 = x * 0.35;
    for (let i = 0; i < 7; i++) { const m = unchecked(this.modes[i]); m.tick(x); y += m.bp * m.k * unchecked(this.gains[i]); }
    return this.hp.hp(y);
  }
}

// ---- a small stereo hall: early reflections + an 8-line FDN ----------------
const FDN_N: i32 = 8;
class Hall {
  lines: StaticArray<Delay> = new StaticArray<Delay>(FDN_N);
  lens: StaticArray<f32> = new StaticArray<f32>(FDN_N);
  damp: StaticArray<OnePole> = new StaticArray<OnePole>(FDN_N);
  pre: Delay = new Delay(9600);
  early: Delay = new Delay(4800);
  outL: f32 = 0; outR: f32 = 0; fb: f32 = 0.8;
  constructor() {
    const base: StaticArray<f32> = [1123.0, 1319.0, 1511.0, 1723.0, 1931.0, 2141.0, 2357.0, 2591.0];
    for (let i = 0; i < FDN_N; i++) { this.lines[i] = new Delay(4096); this.lens[i] = base[i]; this.damp[i] = new OnePole(); }
  }
  init(): void {
    for (let i = 0; i < FDN_N; i++) {
      const l = unchecked(this.lines[i]); l.clear(); l.setLen(this.lens[i] * SR / 48000.0);
      unchecked(this.damp[i]).z = 0;
    }
    this.pre.clear(); this.early.clear(); this.outL = 0; this.outR = 0;
  }
  // size 0..1 → decay time; tone 0..1 → damping; predelay seconds
  set(size: f32, tone: f32, predelay: f32): void {
    const rt60: f32 = 0.8 + 5.2 * size * size;
    const meanLen: f32 = 1800.0 * SR / 48000.0;
    this.fb = Mathf.pow(10.0, -3.0 * meanLen * invSR / rt60);
    for (let i = 0; i < FDN_N; i++) unchecked(this.damp[i]).set(2500.0 + 11000.0 * tone);
    this.pre.setLen(clampf(predelay, 0.0, 0.19) * SR + 1.0);
  }
  // Freeze: the Householder matrix is lossless, so with feedback at unity
  // and the damping opened right up the network holds its tail indefinitely.
  frozen: bool = false;
  freeze(on: bool): void {
    if (on == this.frozen) return;
    this.frozen = on;
    if (on) { this.fb = 0.99995; for (let i = 0; i < FDN_N; i++) unchecked(this.damp[i]).set(20000.0); }
  }
  tick(inL: f32, inR: f32): void {
    const x = this.pre.tick((inL + inR) * 0.5);
    // early reflections: a few taps off a short line
    this.early.tick(x);
    const er = this.early.read(0.011 * SR) * 0.5 + this.early.read(0.017 * SR) * 0.4 - this.early.read(0.023 * SR) * 0.35 + this.early.read(0.031 * SR) * 0.3;
    // FDN with a Householder feedback matrix (energy-preserving mixing)
    let sum: f32 = 0;
    for (let i = 0; i < FDN_N; i++) sum += unchecked(this.lines[i]).last;
    const hh = sum * (2.0 / f32(FDN_N));
    let l: f32 = 0; let r: f32 = 0;
    for (let i = 0; i < FDN_N; i++) {
      const line = unchecked(this.lines[i]);
      const v = line.last;
      const fbv = unchecked(this.damp[i]).lp((v - hh) * this.fb);
      line.tick(fbv + (x + er * 0.3) * 0.35);
      if ((i & 1) == 0) l += v; else r += v;
    }
    this.outL = er * 0.6 + l * 0.5;
    this.outR = -er * 0.45 + r * 0.5 + er * 0.2;
  }
}

// ---- controllers (CC arrive in steps: smooth them) --------------------------
class Smoothed {
  v: f32 = 0; target: f32 = 0; c: f32 = 0.01;
  setTau(t: f32): void { this.c = smoothCoef(t); }
  tick(): f32 { this.v += (this.target - this.v) * this.c; return this.v; }
}

// ---- host transport (for tempo-synced engines) ---------------------------------
let hostPlaying: bool = false; let hostPpq: f64 = 0.0; let hostBpm: f32 = 0.0; let hostSeen: bool = false;
export function transport(playing: i32, ppq: f64, bpm: f32): void { hostPlaying = playing != 0; hostPpq = ppq; hostBpm = bpm; hostSeen = true; }
@inline function hostTempo(): f32 { const t = params[63]; return t > 1.0 ? t : (hostBpm > 1.0 ? hostBpm : 120.0); }

function commonInit(sr: f32): void {
  SR = sr; invSR = 1.0 / sr; rng = 0x6d2b79f5;
  hostPlaying = false; hostPpq = 0.0; hostBpm = 0.0; hostSeen = false;
  for (let i = 0; i < 16; i++) display[i] = 0;
}

export function getInputPtr(): usize  { return changetype<usize>(inBuf); }
export function getOutputPtr(): usize { return changetype<usize>(outBuf); }
export function getParamsPtr(): usize { return changetype<usize>(params); }
export function getNumParams(): i32   { return NUM_PARAMS; }
export function getDisplayPtr(): usize { return changetype<usize>(display); }


// =====================================================================
//  strings/section.ts — a bowed string SECTION built from BowedString:
//  every note is played by several players, each with their own string,
//  intonation, vibrato, bow timing and seat on the stage, so a chord is a
//  section of desks rather than one oscillator with chorus.
//
//  Articulations are properties of the bow, not samples:
//    0 SUSTAIN    bow drawn, attack speed from velocity, held
//    1 TREMOLO    bow reverses ~12–16 Hz, each player out of step
//    2 PIZZICATO  no bow: the string is plucked and rings out
//    3 SPICCATO   a short bounced stroke, length independent of the key
//    4 MARCATO    a hard bite (force + speed spike) settling to sustain
//    5 HARMONICS  light bow over the fingerboard, sounding an octave up
//    6 SUL PONT.  bow at the bridge: glassy, upper partials, weak fundamental
//    7 COL LEGNO  struck with the stick: a woody, pitched tick
// =====================================================================

const MAXV: i32 = 12;                // notes
const MAXP: i32 = 6;                 // players per note
const NPLAY: i32 = MAXV * MAXP;

// Register families and their bodies. 0 violin, 1 viola, 2 cello, 3 bass.
const bodiesL = new StaticArray<Body>(4);
const bodiesR = new StaticArray<Body>(4);
const busL = new StaticArray<f32>(4);
const busR = new StaticArray<f32>(4);

class Player {
  s: BowedString = new BowedString();
  family: i32 = 0; ratio: f32 = 1.0;         // ratio 0.5 = octave-down doubling
  detune: f32 = 1.0;                         // multiplicative intonation offset
  vibPh: f32 = 0; vibRate: f32 = 5.6; vibDepth: f32 = 1.0; vibOn: f32 = 0;
  delay: i32 = 0;                            // samples before this player's bow lands
  tremPh: f32 = 0;
  gL: f32 = 0.7; gR: f32 = 0.7;
  drift: f32 = 0;                            // slow intonation wander
  used: bool = false; plucked: bool = false;
  hpz: f32 = 0;                              // sul ponticello thins the fundamental
  wander: f32 = 0;                           // slow bow-speed wander (humanize)
  // aleatoric director (all zero in a plain section)
  offC: f32 = 0; walkC: f32 = 0; walkT: f32 = 0; walkTimer: i32 = 0; scr: f32 = 0; gain: f32 = 1.0;
}

class Voice {
  note: i32 = -1; vel: f32 = 0; art: i32 = 0;
  target: f32 = 220; freq: f32 = 220; glideC: f32 = 1.0;
  gate: bool = false; bow: f32 = 0; age: i32 = 0; relAge: i32 = 0;
  active: bool = false; np: i32 = 0; accent: f32 = 0;
  hitDone: bool = false; accEnv: f32 = 0;   // amplitude accent (marcato / hard velocity)
}

const players = new StaticArray<Player>(NPLAY);
const voices = new StaticArray<Voice>(MAXV);

// Performance state the plugin sets each block (from params + controllers).
let sectionMode: i32 = 0;      // 0 auto, 1 violins, 2 violas, 3 celli, 4 basses, 5 full orchestra
let playersPerNote: i32 = 4;
let curArt: i32 = 0;
let dyn: f32 = 0.6;            // 0..1 dynamics (bow speed + force + brightness)
let vibAmt: f32 = 0.5; let vibRateScale: f32 = 1.0; let vibOnset: f32 = 0.35;
let attackScale: f32 = 1.0; let releaseTime: f32 = 0.35;
let forceBias: f32 = 0.5; let posBias: f32 = 0.5; let brightBias: f32 = 0.5;
let tightness: f32 = 0.6; let tremRate: f32 = 14.0; let humanize: f32 = 0.5;
let legato: bool = false; let portamento: f32 = 0.4;
let bodyAmt: f32 = 0.8; let octaveDouble: f32 = 0.0; let width: f32 = 0.7;
let bendSemis: f32 = 0.0;      // current pitch bend in semitones
let fineTune: f32 = 1.0;
let velToDyn: f32 = 0.4;
// Aleatoric controls (Aleatora). Zero = off, so a plain section pays nothing.
let clusterC: f32 = 0.0;       // half-width of the cluster, cents
let quarterTone: bool = false; // snap cluster offsets to a 50-cent grid
let swarmC: f32 = 0.0;         // how far each player wanders, cents
let swarmRate: f32 = 1.0;      // new wander targets per second
let swarmSlew: f32 = 0.001;    // glide coefficient toward the target
let riseC: f32 = 0.0;          // total glissando, cents (±)
let riseTime: f32 = 8.0;       // seconds to complete it
let scratchAmt: f32 = 0.0;     // overpressure bursts per second (per player)
let shimmer: f32 = 0.0;        // level of an octave-up flautando player
let pulseGain: f32 = 1.0;      // bow multiplier from the pulse engine (set per sample)
let aleaFirstVoice: i32 = -1;  // voice whose players the display shows

function sectionInit(): void {
  for (let i = 0; i < 4; i++) {
    const bl = new Body(); bl.configure(i); bodiesL[i] = bl;
    const br = new Body(); br.configure(i); bodiesR[i] = br;
  }
  for (let i = 0; i < NPLAY; i++) { const p = new Player(); p.s.clear(); players[i] = p; }
  for (let i = 0; i < MAXV; i++) voices[i] = new Voice();
  hpL.reset(); hpR.reset(); hpL.set(30.0, 0.7); hpR.set(30.0, 0.7); toneL.reset(); toneR.reset(); toneFc = -1.0;
}

function familyFor(note: i32): i32 {
  if (sectionMode == 1) return 0;
  if (sectionMode == 2) return 1;
  if (sectionMode == 3) return 2;
  if (sectionMode == 4) return 3;
  // auto / full: by register (basses below C2, celli below A2, violas below D4)
  if (note < 36) return 3;
  if (note < 45) return 2;
  if (note < 62) return 1;
  return 0;
}

// Seat on the stage for a family (classic American seating: violins left,
// violas centre-right, celli right, basses far right) with a spread per desk.
@inline function seatPan(family: i32, j: i32): f32 {
  const centre: f32 = family == 0 ? -0.55 : (family == 1 ? 0.15 : (family == 2 ? 0.45 : 0.7));
  return clampf(centre + (f32(j) - 2.5) * 0.09, -1.0, 1.0);
}

function allocVoice(note: i32): i32 {
  for (let i = 0; i < MAXV; i++) if (unchecked(voices[i]).note == note && unchecked(voices[i]).active) return i;
  for (let i = 0; i < MAXV; i++) if (!unchecked(voices[i]).active) return i;
  // steal the oldest releasing voice, else the oldest
  let best = 0; let bestAge = -1;
  for (let i = 0; i < MAXV; i++) { const v = unchecked(voices[i]); const a = v.age + (v.gate ? 0 : 1 << 24); if (a > bestAge) { bestAge = a; best = i; } }
  return best;
}

@inline function noteHz(note: i32): f32 { return 440.0 * Mathf.pow(2.0, (f32(note) - 69.0) / 12.0) * fineTune; }

function startVoice(vi: i32, note: i32, vel: f32, art: i32): void {
  const v = unchecked(voices[vi]);
  const fresh = !v.active;
  v.note = note; v.vel = vel; v.art = art; v.gate = true; v.active = true; v.age = 0; v.relAge = 0; v.hitDone = false;
  v.target = noteHz(note) * (art == 5 ? 2.0 : 1.0);
  v.freq = v.target; v.glideC = 1.0;
  v.accent = art == 4 ? 1.0 : (vel > 0.85 ? (vel - 0.85) * 4.0 : 0.0);
  v.accEnv = art == 4 ? 1.4 : v.accent * 0.6;
  const fam = familyFor(note);
  const np = art == 2 || art == 7 ? clampf(f32(playersPerNote), 1.0, 4.0) : f32(playersPerNote);
  v.np = i32(np);
  const spread: f32 = 1.0 - tightness;
  for (let j = 0; j < MAXP; j++) {
    const p = unchecked(players[vi * MAXP + j]);
    p.used = j < v.np;
    if (!p.used) continue;
    const dbl = sectionMode == 5 && octaveDouble > 0.01 && j == v.np - 1 && fam >= 1;
    p.family = dbl ? (fam == 1 ? 2 : 3) : fam;
    p.ratio = dbl ? 0.5 : 1.0;
    p.detune = Mathf.pow(2.0, (white() * (4.0 + 18.0 * spread)) / 1200.0);   // a few cents apart
    p.vibRate = (5.0 + 1.4 * rand01()) * vibRateScale;
    p.vibDepth = 0.6 + 0.8 * rand01();
    p.vibPh = rand01(); p.vibOn = 0;
    p.delay = i32((rand01() * (0.004 + 0.05 * spread) * (0.5 + humanize)) * SR);
    p.tremPh = rand01(); p.plucked = false;
    p.gain = 1.0; p.walkC = 0.0; p.walkT = 0.0; p.walkTimer = 0; p.scr = 0.0;
    if (clusterC > 0.0) {
      let o = white() * clusterC;
      if (quarterTone) o = Mathf.round(o / 50.0) * 50.0;
      p.offC = o;
    } else p.offC = 0.0;
    if (shimmer > 0.01 && v.np > 1 && j == v.np - 1) { p.ratio = 2.0; p.gain = shimmer * 1.3; }
    const pan = seatPan(p.family, j) * width;
    p.gL = Mathf.sqrt(0.5 * (1.0 - pan)); p.gR = Mathf.sqrt(0.5 * (1.0 + pan));
    if (fresh) p.s.clear();
    p.s.beta = clampf(0.127 + (posBias - 0.5) * 0.14 + (art == 6 ? -0.085 : 0.0) + (art == 5 ? 0.09 : 0.0), 0.03, 0.3);
  }
  if (fresh) v.bow = 0.0;
}

// Legato: glide the sounding voice to the new note instead of re-bowing.
// Slow velocity = expressive slide (portamento), fast velocity = bow change.
function legatoTo(vi: i32, note: i32, vel: f32): void {
  const v = unchecked(voices[vi]);
  v.note = note; v.target = noteHz(note) * (v.art == 5 ? 2.0 : 1.0);
  const slow = vel < 0.55;
  const t: f32 = slow ? (0.08 + 0.35 * portamento) * (1.1 - vel) : 0.012 + 0.02 * portamento;
  v.glideC = smoothCoef(t * 0.25);          // reaches the new pitch within the slide time
  v.gate = true; v.relAge = 0;
  if (!slow) v.bow *= 0.75;          // the dip of a bow change
}

// One sample of the whole section into the family buses.
function sectionTick(): void {
  for (let b = 0; b < 4; b++) { busL[b] = 0; busR[b] = 0; }
  const bend = Mathf.pow(2.0, bendSemis / 12.0);
  const dynV: f32 = 0.06 + 0.3 * dyn;                 // bow speed
  const accDecay: f32 = decayCoef(0.11);
  const dynF: f32 = clampf(forceBias * (0.25 + 1.0 * dyn), 0.02, 0.98);
  const bright: f32 = 2200.0 + 9500.0 * clampf(brightBias * 0.6 + dyn * 0.5, 0.0, 1.2);
  for (let vi = 0; vi < MAXV; vi++) {
    const v = unchecked(voices[vi]);
    if (!v.active) continue;
    v.freq += (v.target - v.freq) * v.glideC;
    const art = v.art;
    const tSec = f32(v.age) * invSR;
    // --- bow envelope per articulation ---
    let bowTarget: f32 = 0.0;
    if (art == 0 || art == 5 || art == 6) {
      bowTarget = v.gate ? 1.0 : 0.0;
      const atk: f32 = (0.02 + 0.45 * (1.0 - v.vel)) * attackScale;
      v.bow += (bowTarget - v.bow) * smoothCoef(v.gate ? atk : releaseTime * 0.5);
    } else if (art == 1) {
      bowTarget = v.gate ? 1.0 : 0.0;
      v.bow += (bowTarget - v.bow) * smoothCoef(v.gate ? 0.04 * attackScale : releaseTime * 0.4);
    } else if (art == 3) {                           // spiccato: ~90 ms bounced stroke
      v.bow = tSec < 0.012 ? tSec / 0.012 : Mathf.exp(-(tSec - 0.012) / 0.045);
    } else if (art == 4) {                           // marcato: bite then settle
      const settle: f32 = v.gate ? 0.55 : 0.0;
      v.bow = tSec < 0.03 ? 1.6 : settle + (1.6 - settle) * Mathf.exp(-(tSec - 0.03) / 0.12);
      if (!v.gate) v.bow *= Mathf.exp(-f32(v.relAge) * invSR / (releaseTime * 0.5));
    } else { v.bow = 0.0; }                          // pizz / col legno: no bow
    if (!v.gate) v.relAge++;
    const accGain: f32 = 1.0 + v.accEnv; v.accEnv *= accDecay;
    let alive = false;
    for (let j = 0; j < v.np; j++) {
      const p = unchecked(players[vi * MAXP + j]);
      if (!p.used) continue;
      if (p.delay > 0) { p.delay--; continue; }
      const s = p.s;
      // plucks happen on the first sample the player is "on"
      if ((art == 2 || art == 7) && !p.plucked) {
        s.pluck = (art == 2 ? 0.55 : 0.3) * (0.4 + 0.8 * v.vel) * (0.8 + 0.4 * rand01());
        p.plucked = true;
      }
      // vibrato: fades in after the onset delay, not on short notes
      const vibWanted: bool = (art == 0 || art == 4 || art == 5 || art == 6) && tSec > vibOnset;
      p.vibOn += ((vibWanted ? 1.0 : 0.0) - p.vibOn) * 0.0004;
      p.vibPh += p.vibRate * invSR; if (p.vibPh >= 1.0) p.vibPh -= 1.0;
      const vib = fastSin01(p.vibPh) * vibAmt * p.vibDepth * p.vibOn * 0.0035;   // up to ~±20 cents
      p.drift = p.drift * 0.9997 + white() * 0.000012 * (0.3 + humanize);
      let aleaRatio: f32 = 1.0;
      if (clusterC > 0.0 || swarmC > 0.0 || riseC != 0.0) {
        if (swarmC > 0.0) {
          if (--p.walkTimer <= 0) { p.walkT = white() * swarmC; p.walkTimer = i32(SR / (swarmRate * (0.4 + 1.2 * rand01()))); }
          p.walkC += (p.walkT - p.walkC) * swarmSlew;
        }
        const rp: f32 = riseTime > 0.01 ? clampf(tSec / riseTime, 0.0, 1.0) : 1.0;
        aleaRatio = fastExp2((p.offC + p.walkC + riseC * rp * rp) / 1200.0);
      }
      s.setFreq(v.freq * p.ratio * p.detune * bend * aleaRatio * (1.0 + vib + p.drift));
      s.setBrightness(art == 7 ? 3500.0 : (art == 2 ? bright * 0.7 : (art == 6 ? clampf(bright * 1.9, 4000.0, 19000.0) : bright)));
      // a released note is damped by the player's fingers; plucks ring longer
      const damp: f32 = v.gate ? 0.0 : clampf(f32(v.relAge) * invSR / releaseTime, 0.0, 1.0);
      s.lossGain = (art == 2 ? 0.998 : (art == 7 ? 0.985 : 0.996)) - (art == 2 ? 0.006 : 0.03) * damp;
      // bow speed and force for this player
      p.wander += (white() * 0.5 - p.wander) * 0.0006;            // a bow arm drifts, it doesn't jitter
      let bv = v.bow * (dynV + 0.12 * v.accent) * (1.0 + velToDyn * (v.vel - 0.5)) * (1.0 + p.wander * 0.25 * humanize);
      let bf = dynF + (art == 4 ? 0.25 * v.bow : 0.0);
      if (art == 1) {                                // tremolo: alternating strokes
        p.tremPh += tremRate * (0.9 + 0.2 * p.detune) * invSR; if (p.tremPh >= 1.0) p.tremPh -= 1.0;
        bv *= p.tremPh < 0.5 ? 1.0 : -1.0;
      }
      if (art == 5 || p.ratio == 2.0) { bf *= 0.35; bv *= 0.7; }
      if (scratchAmt > 0.0) {                          // overpressure: slow bow, heavy force = crunch
        if (rand01() < scratchAmt * invSR) p.scr = 1.0;
        if (p.scr > 0.001) { bf = clampf(bf + 0.7 * p.scr, 0.01, 0.99); bv *= 1.0 - 0.65 * p.scr; p.scr *= 0.99985; }
      }
      bv *= pulseGain;
      if (art == 6) { bf = clampf(bf * 1.25 + 0.1, 0.01, 0.99); }
      s.bowVel = bv; s.force = clampf(bf, 0.01, 0.99);
      let y = s.tick();
      if (art == 6) { p.hpz += 0.06 * (y - p.hpz); y = (y - p.hpz) * 1.6; }   // weak fundamental, glassy top
      y *= accGain * p.gain;
      busL[p.family] += y * p.gL; busR[p.family] += y * p.gR;
      if (Mathf.abs(y) > 0.00002 || v.bow > 0.001) alive = true;
    }
    v.age++;
    if (!alive && !v.gate && v.age > 2400) { v.active = false; v.note = -1; }
    if (!alive && (art == 2 || art == 7 || art == 3) && v.age > 4800) { v.active = false; v.note = -1; }
  }
}

// Sum the families through their bodies. Returns via outs.
let secL: f32 = 0; let secR: f32 = 0;
const toneL = new Svf(); const toneR = new Svf(); let toneFc: f32 = -1.0;
const hpL = new Svf(); const hpR = new Svf();      // 30 Hz: below the double bass's low E
function bodiesTick(): void {
  let l: f32 = 0; let r: f32 = 0;
  for (let b = 0; b < 4; b++) {
    const xl = busL[b]; const xr = busR[b];
    if (xl == 0.0 && xr == 0.0) continue;
    const bl = unchecked(bodiesL[b]).tick(xl); const br = unchecked(bodiesR[b]).tick(xr);
    l += xl * (1.0 - bodyAmt) * 0.6 + bl * bodyAmt; r += xr * (1.0 - bodyAmt) * 0.6 + br * bodyAmt;
  }
  // orchestral dynamics are timbre as much as level: pp dark, ff open
  const fc: f32 = 1400.0 + 15000.0 * dyn * dyn;
  if (Mathf.abs(fc - toneFc) > 20.0) { toneL.set(fc, 0.62); toneR.set(fc, 0.62); toneFc = fc; }
  toneL.tick(l); toneR.tick(r);
  hpL.tick(toneL.lp); hpR.tick(toneR.lp);
  secL = hpL.hp; secR = hpR.hp;
}

function releaseNote(note: i32): void {
  for (let i = 0; i < MAXV; i++) { const v = unchecked(voices[i]); if (v.active && v.note == note && v.gate) { v.gate = false; v.relAge = 0; } }
}
function activeCount(): i32 { let c = 0; for (let i = 0; i < MAXV; i++) if (unchecked(voices[i]).active) c++; return c; }


// ---- generated from defs.mjs -----------------------------------------

const P_SECTION: i32 = 0;
const P_PLAYERS: i32 = 1;
const P_ART: i32 = 2;
const P_DYN: i32 = 3;
const P_EXPR: i32 = 4;
const P_VIB: i32 = 5;
const P_VIB_RATE: i32 = 6;
const P_VIB_DELAY: i32 = 7;
const P_ATTACK: i32 = 8;
const P_RELEASE: i32 = 9;
const P_FORCE: i32 = 10;
const P_POSITION: i32 = 11;
const P_BRIGHT: i32 = 12;
const P_TIGHT: i32 = 13;
const P_TREM_RATE: i32 = 14;
const P_HUMAN: i32 = 15;
const P_LEGATO: i32 = 16;
const P_PORTA: i32 = 17;
const P_VEL_DYN: i32 = 18;
const P_BODY: i32 = 19;
const P_DOUBLE: i32 = 20;
const P_WIDTH: i32 = 21;
const P_MIC_CLOSE: i32 = 22;
const P_MIC_TREE: i32 = 23;
const P_MIC_AMB: i32 = 24;
const P_HALL_SIZE: i32 = 25;
const P_HALL_TONE: i32 = 26;
const P_PREDELAY: i32 = 27;
const P_TUNE: i32 = 28;
const P_BEND: i32 = 29;
const P_MASTER: i32 = 30;
const NUM_PARAMS: i32 = 31;
function setDefaults(): void {
  params[0] = 0.0;   // Section
  params[1] = 4.0;   // Players
  params[2] = 0.0;   // Articulation
  params[3] = 0.6;   // Dynamics
  params[4] = 0.85;   // Expression
  params[5] = 0.55;   // Vibrato
  params[6] = 0.5;   // Vibrato Rate
  params[7] = 0.35;   // Vibrato Delay
  params[8] = 0.4;   // Attack
  params[9] = 0.35;   // Release
  params[10] = 0.5;   // Bow Pressure
  params[11] = 0.5;   // Bow Position
  params[12] = 0.5;   // Brightness
  params[13] = 0.6;   // Ensemble Tightness
  params[14] = 0.5;   // Tremolo Speed
  params[15] = 0.5;   // Humanize
  params[16] = 0.0;   // Legato
  params[17] = 0.4;   // Portamento
  params[18] = 0.4;   // Velocity to Dynamics
  params[19] = 0.8;   // Body Resonance
  params[20] = 0.5;   // Octave Doubling
  params[21] = 0.75;   // Stage Width
  params[22] = 0.6;   // Close Mics
  params[23] = 0.8;   // Tree Mics
  params[24] = 0.45;   // Ambient Mics
  params[25] = 0.6;   // Hall Size
  params[26] = 0.5;   // Hall Tone
  params[27] = 0.3;   // Pre-delay
  params[28] = 0.0;   // Fine Tune
  params[29] = 2.0;   // Bend Range
  params[30] = 0.7;   // Master
}

// =====================================================================
//  TESSITURA — a physically modelled string section.
//
//  Every note is bowed by up to six players (bowed-waveguide strings on
//  violin, viola, cello or bass bodies), seated across the stage, each with
//  their own intonation, vibrato and bow timing. Eight articulations switch
//  on keyswitches C0–G0 (MIDI 24–31) or the Articulation control; the
//  orchestral controllers work as in sample libraries: CC1 dynamics (bow
//  speed, pressure and brightness together), CC11 expression, CC21 vibrato.
//  LEGATO makes it a monophonic line: overlapping notes slide (slow
//  velocity) or change bow (fast velocity) instead of re-attacking.
//  A stage with close, tree and ambient microphones feeds a hall.
// =====================================================================
const hall = new Hall();
let cc1: f32 = -1.0; let cc11: f32 = -1.0; let cc21: f32 = -1.0; let bend: f32 = 0.0;
const dynS = new Smoothed(); const exprS = new Smoothed(); const vibS = new Smoothed(); const bendS = new Smoothed();
let ksArt: i32 = -1;          // last keyswitch (overrides the Articulation control until it changes)
let lastArtParam: i32 = -1;
let held: i32 = 0;            // keys down (legato)
let legVoice: i32 = -1;
const heldNotes = new StaticArray<i32>(16); let heldN: i32 = 0;
let peak: f32 = 0;

// Knob vs controller: whichever moved last wins (turning the knob takes
// over from the mod wheel, and vice versa).
let lastDYN: f32 = -99.0;
let lastEXPR: f32 = -99.0;
let lastVIB: f32 = -99.0;

export function init(sr: f32, maxFrames: i32, numChannels: i32): void {
  commonInit(sr); sectionInit(); hall.init(); setDefaults();
  lastDYN = params[P_DYN]; lastEXPR = params[P_EXPR]; lastVIB = params[P_VIB];
  cc1 = -1; cc11 = -1; cc21 = -1; bend = 0; ksArt = -1; lastArtParam = -1; heldN = 0; legVoice = -1; peak = 0;
  dynS.setTau(0.03); exprS.setTau(0.03); vibS.setTau(0.05); bendS.setTau(0.008);
  dynS.v = params[P_DYN]; exprS.v = params[P_EXPR]; vibS.v = params[P_VIB];
}

function applyParams(): void {
  if (params[P_DYN] != lastDYN) { lastDYN = params[P_DYN]; cc1 = -1.0; }
  if (params[P_EXPR] != lastEXPR) { lastEXPR = params[P_EXPR]; cc11 = -1.0; }
  if (params[P_VIB] != lastVIB) { lastVIB = params[P_VIB]; cc21 = -1.0; }
  sectionMode = i32(params[P_SECTION] + 0.5);
  playersPerNote = i32(clampf(params[P_PLAYERS], 1.0, 6.0) + 0.5);
  const ap = i32(params[P_ART] + 0.5);
  if (ap != lastArtParam) { lastArtParam = ap; ksArt = -1; }      // moving the control takes over again
  curArt = ksArt >= 0 ? ksArt : ap;
  dynS.target = cc1 >= 0.0 ? cc1 : params[P_DYN];
  exprS.target = cc11 >= 0.0 ? cc11 : params[P_EXPR];
  vibS.target = cc21 >= 0.0 ? cc21 : params[P_VIB];
  vibRateScale = 0.75 + 0.5 * params[P_VIB_RATE];
  vibOnset = 0.05 + 0.9 * params[P_VIB_DELAY];
  attackScale = 0.3 + 2.4 * params[P_ATTACK];
  releaseTime = 0.08 + 1.6 * params[P_RELEASE];
  forceBias = 0.2 + 0.8 * params[P_FORCE]; posBias = params[P_POSITION]; brightBias = params[P_BRIGHT];
  tightness = params[P_TIGHT]; tremRate = 9.0 + 10.0 * params[P_TREM_RATE]; humanize = params[P_HUMAN];
  legato = params[P_LEGATO] > 0.5; portamento = params[P_PORTA]; velToDyn = params[P_VEL_DYN];
  bodyAmt = params[P_BODY]; octaveDouble = params[P_DOUBLE]; width = params[P_WIDTH];
  fineTune = Mathf.pow(2.0, params[P_TUNE] / 1200.0);
  hall.set(params[P_HALL_SIZE], params[P_HALL_TONE], 0.005 + 0.09 * params[P_PREDELAY]);
}

export function noteOn(id: i32, hz: f32, vel: f32): void {
  applyParams();
  if (id >= 24 && id <= 31) { ksArt = id - 24; curArt = ksArt; return; }   // keyswitch C0–G0
  if (legato) {
    if (heldN < 16) { heldNotes[heldN] = id; heldN++; }
    if (legVoice >= 0 && unchecked(voices[legVoice]).active && unchecked(voices[legVoice]).gate) { legatoTo(legVoice, id, vel); return; }
    legVoice = allocVoice(id);
    startVoice(legVoice, id, vel, curArt);
    return;
  }
  startVoice(allocVoice(id), id, vel, curArt);
}

export function noteOff(id: i32): void {
  if (id >= 24 && id <= 31) return;
  if (legato) {
    let k = -1; for (let i = 0; i < heldN; i++) if (heldNotes[i] == id) { k = i; break; }
    if (k >= 0) { for (let i = k; i < heldN - 1; i++) heldNotes[i] = heldNotes[i + 1]; heldN--; }
    if (legVoice >= 0 && unchecked(voices[legVoice]).note == id) {
      if (heldN > 0) legatoTo(legVoice, heldNotes[heldN - 1], 0.4);        // fall back to the held note
      else { releaseNote(id); legVoice = -1; }
    }
    return;
  }
  releaseNote(id);
}

export function controlChange(num: i32, value: f32): void {
  if (num == 1) cc1 = value;
  else if (num == 11) cc11 = value;
  else if (num == 21) cc21 = value;
  else if (num == 128) bend = value;
}

export function process(n: i32): void {
  applyParams();
  const range = params[P_BEND];
  const close = params[P_MIC_CLOSE], tree = params[P_MIC_TREE], amb = params[P_MIC_AMB];
  const master = params[P_MASTER] * params[P_MASTER] * 0.42;
  for (let f = 0; f < n; f++) {
    dyn = dynS.tick(); vibAmt = vibS.tick(); const expr = exprS.tick();
    bendS.target = bend * range; bendSemis = bendS.tick();
    sectionTick(); bodiesTick();
    const dl = secL * expr, dr = secR * expr;
    hall.tick(dl, dr);
    // close: dry, full width · tree: narrower with the early field · ambient: the hall
    const mid = (dl + dr) * 0.5;
    let l = dl * close * 1.1 + (mid * 0.55 + dl * 0.45) * tree * 0.9 + hall.outL * amb * 1.4;
    let r = dr * close * 1.1 + (mid * 0.55 + dr * 0.45) * tree * 0.9 + hall.outR * amb * 1.4;
    l = softclip(l * master); r = softclip(r * master);
    unchecked(outBuf[f] = l); unchecked(outBuf[MAX_FRAMES + f] = r);
    const a = Mathf.max(Mathf.abs(l), Mathf.abs(r)); if (a > peak) peak = a;
  }
  // display: [0] articulation, [1] active notes, [2] dynamics, [3] vibrato, [4] expression, [15] peak
  display[0] = f32(curArt); display[1] = f32(activeCount()); display[2] = dyn; display[3] = vibAmt; display[4] = exprS.v;
  display[15] = peak; peak *= Mathf.exp(-f32(n) * invSR / 0.25);
}
