#!/usr/bin/env node
// =====================================================================
//  kgrbdpa/build.mjs — assemble the KGrbdPa plugin.
//    node factory/kgrbdpa/build.mjs [--pack] [--no-gui]
//  → factory/plugins/kgrbdpa/{assembly.ts, gui.html, spec.json}
//    (a .vstai carries ONE source file and ONE gui.html, so sources are
//     pasted together: generated tables + dsp/core + osc + mods + keys + main)
// =====================================================================
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { P, SLOT_MAX, SRC, DST, CLOCK_DIVS, PPQN } from "./params.mjs";
import { L, assertFits, slotDefaults } from "./pack.mjs";
import { EXPLANATION } from "./explanation.mjs";
import { DEFAULT_SEQS } from "./seqs.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const out = join(root, "factory/plugins/kgrbdpa");
const rd = (p) => readFileSync(join(here, p), "utf8");
assertFits();

const f32 = (v) => { const s = String(Number(v)); return /[.e]/i.test(s) ? s : s + ".0"; };

// MIDI chart "CC 90" values for the 24 clock divisions
export const CC90 = [0, 5, 11, 16, 21, 27, 32, 37, 43, 48, 53, 59, 64, 69, 75, 80, 85, 91, 96, 101, 107, 112, 117, 123];

function generated() {
  const arr = (name, type, fn) => `const ${name}: StaticArray<${type}> = [${P.map(fn).join(", ")}];`;
  const defs = slotDefaults();
  const seqCode = [];
  DEFAULT_SEQS.forEach((seq, s) => {
    seqCode.push(`  seqLen[${s}] = ${seq.length};`);
    seq.forEach((st, i) => { seqCode.push(`  seqNote[${s * 256 + i}] = ${st.note}; seqFlag[${s * 256 + i}] = ${st.flag};`); });
  });
  return [
    `const NP: i32 = ${P.length};`,
    `const NUM_PARAMS: i32 = ${L.slots};`,
    ...P.map((p, i) => `const P_${p.key}: i32 = ${i};`),
    arr("PSLOT", "i32", (p) => p.slot),
    arr("PMULT", "i32", (p) => p.mult),
    arr("PSTEPS", "i32", (p) => p.steps),
    arr("PDIRECT", "i32", (p) => (p.direct ? 1 : 0)),
    arr("PMIN", "f32", (p) => f32(p.min)),
    arr("PMAX", "f32", (p) => f32(p.max)),
    `const NSRC: i32 = ${SRC.length};`,
    `const NDST: i32 = ${DST.length};`,
    ...SRC.map((s, i) => `const S_${s[0]}: i32 = ${i + 1};`),
    ...DST.map((d, i) => `const D_${d[0]}: i32 = ${i};`),
    `const CLOCK_DIV: StaticArray<f32> = [${CLOCK_DIVS.map((x) => f32(x[1])).join(", ")}];`,
    `const CC90_V: StaticArray<i32> = [${CC90.join(", ")}];`,
    `const PPQN_V: StaticArray<i32> = [${PPQN.join(", ")}];`,
    "function setDefaults(): void {",
    ...defs.map((v, s) => `  params[${s}] = ${f32(v)};`),
    "}",
    "function SEQ_DEFAULTS(): void {",
    ...seqCode,
    "}",
  ].join("\n");
}

function buildDsp() {
  const files = ["dsp/core.ts", "dsp/osc.ts", "dsp/mods.ts", "dsp/keys.ts", "dsp/main.ts"];
  const header = [
    "// =====================================================================",
    "//  KGrbdPa — GENERATED by factory/kgrbdpa/build.mjs. Edit the sources:",
    "//    factory/kgrbdpa/params.mjs   (parameter table, patch-bay jacks, packing)",
    "//    factory/kgrbdpa/seqs.mjs     (default sequences)",
    ...files.map((f) => `//    factory/kgrbdpa/${f}`),
    "// =====================================================================",
  ].join("\n");
  return [header, generated(), ...files.map(rd)].join("\n\n");
}

function buildSpec() {
  const slots = [];
  const dv = slotDefaults();
  for (let s = 0; s < L.slots; s++) {
    const d = P.find((p) => p.slot === s && p.direct);
    slots.push(d
      ? { name: d.name, index: s, min: d.min, max: d.max, default: d.def }
      : { name: `Pack ${String(s).padStart(2, "0")}`, index: s, min: 0, max: SLOT_MAX, default: dv[s] });
  }
  return {
    name: "KGrbdPa",
    isInstrument: true,
    explanation: EXPLANATION.replace("@N@", String(P.length)),
    assembly: "factory/plugins/kgrbdpa/assembly.ts",
    out: "factory/plugins/kgrbdpa/x.vstai",
    guiFile: "factory/plugins/kgrbdpa/gui.html",
    publishedAt: Date.now(),
    theme: { accent: "#ff7a1a", accent2: "#f4ead2" },
    params: slots,
  };
}

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "assembly.ts"), buildDsp());
writeFileSync(join(out, "spec.json"), JSON.stringify(buildSpec(), null, 2) + "\n");
console.log(`assembly.ts + spec.json written  (${P.length} controls in ${L.slots} host slots)`);

if (!process.argv.includes("--no-gui") && existsSync(join(here, "gui/build-gui.mjs"))) {
  const { buildGui } = await import("./gui/build-gui.mjs");
  writeFileSync(join(out, "gui.html"), buildGui());
  console.log("gui.html written");
}
if (process.argv.includes("--pack")) {
  execFileSync("node", [join(root, "factory/tools/pack-vstai.mjs"), join(out, "spec.json")], { stdio: "inherit" });
}
