// =====================================================================

//  Silverbox Hats — GENERATED by factory/drums/build.mjs. Edit the sources:

//    factory/drums/common.ts

//    factory/drums/tr606/voices.ts

//    factory/drums/tr606/hats.ts

// =====================================================================

// =====================================================================
//  drums/common.ts — shared DSP primitives for the analog drum machines
//  (808 / 909 / 606 families). Not a module on its own: build.mjs pastes
//  it, a machine's voices.ts and one plugin wrapper into a single
//  assembly.ts, because a .vstai carries exactly one source file.
//
//  Everything here is allocation-free after module init and all-f32.
// =====================================================================

const MAX_FRAMES: i32 = 8192;
const MAX_CHANNELS: i32 = 2;
const MAX_PARAMS: i32 = 64;
const PI: f32 = 3.14159265358979;
const TWO_PI: f32 = 6.28318530717959;

const inBuf  = new StaticArray<f32>(MAX_FRAMES * MAX_CHANNELS);
const outBuf = new StaticArray<f32>(MAX_FRAMES * MAX_CHANNELS);
const params = new StaticArray<f32>(MAX_PARAMS);
// Engine → GUI: step light, activity per voice, output peak (see WasmAbi.h).
const display = new StaticArray<f32>(16);

let SR: f32 = 48000.0;
let invSR: f32 = 1.0 / 48000.0;

@inline function clampf(x: f32, lo: f32, hi: f32): f32 { return x < lo ? lo : (x > hi ? hi : x); }
@inline function lerpf(a: f32, b: f32, t: f32): f32 { return a + (b - a) * t; }
@inline function msToSamples(ms: f32): i32 { return i32(ms * 0.001 * SR); }

// Per-sample multiplier that decays by 1/e in `tau` seconds.
function decayCoef(tau: f32): f32 {
  if (tau <= 0.00001) return 0.0;
  return Mathf.exp(-invSR / tau);
}

// A time printed in a service-manual chart ("decay 300 ms", read off a scope)
// is where the note has visibly died away — taken here as −20 dB — so the
// exponential time constant is t / ln(10).
@inline function chartTau(ms: f32): f32 { return ms * 0.001 / 2.302585; }

// Knob → audio-taper gain (the machines use B-taper pots into log-ish ears).
@inline function taper(x: f32): f32 { const c = clampf(x, 0.0, 1.0); return c * c; }

// ---- noise -----------------------------------------------------------
let rng: u32 = 0x9e3779b9;
@inline function white(): f32 {
  rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5;
  return f32(rng) * 4.656612873e-10 - 1.0;          // [-1, 1)
}

// Paul Kellet's economy pink filter.
class Pink {
  b0: f32 = 0; b1: f32 = 0; b2: f32 = 0;
  tick(w: f32): f32 {
    this.b0 = 0.99765 * this.b0 + w * 0.0990460;
    this.b1 = 0.96300 * this.b1 + w * 0.2965164;
    this.b2 = 0.57000 * this.b2 + w * 1.0526913;
    return (this.b0 + this.b1 + this.b2 + w * 0.1848) * 0.25;
  }
}

// ---- filters ---------------------------------------------------------
// Topology-preserving state-variable filter (Simper). Stable under per-sample
// coefficient changes, which the resonator voices rely on (pitch sweeps).
class Svf {
  ic1: f32 = 0; ic2: f32 = 0;
  a1: f32 = 0; a2: f32 = 0; a3: f32 = 0; k: f32 = 1;
  lp: f32 = 0; bp: f32 = 0; hp: f32 = 0;

  set(fc: f32, q: f32): void {
    const f = clampf(fc, 8.0, SR * 0.45);
    const g = Mathf.tan(PI * f * invSR);
    this.k = 1.0 / (q < 0.05 ? 0.05 : q);
    this.a1 = 1.0 / (1.0 + g * (g + this.k));
    this.a2 = g * this.a1;
    this.a3 = g * this.a2;
  }
  tick(x: f32): void {
    const v3 = x - this.ic2;
    const v1 = this.a1 * this.ic1 + this.a2 * v3;
    const v2 = this.ic2 + this.a2 * this.ic1 + this.a3 * v3;
    this.ic1 = 2.0 * v1 - this.ic1;
    this.ic2 = 2.0 * v2 - this.ic2;
    this.lp = v2; this.bp = v1; this.hp = x - this.k * v1 - v2;
  }
  reset(): void { this.ic1 = 0; this.ic2 = 0; this.lp = 0; this.bp = 0; this.hp = 0; }
}

class OnePole {
  z: f32 = 0; a: f32 = 1;
  set(fc: f32): void { this.a = 1.0 - Mathf.exp(-TWO_PI * clampf(fc, 1.0, SR * 0.45) * invSR); }
  lp(x: f32): f32 { this.z += this.a * (x - this.z); return this.z; }
  hp(x: f32): f32 { this.z += this.a * (x - this.z); return x - this.z; }
  reset(): void { this.z = 0; }
}

// ---- band-limited square (the machines' Schmitt-trigger oscillators) --
@inline function polyblep(t: f32, dt: f32): f32 {
  if (t < dt) { const u = t / dt; return u + u - u * u - 1.0; }
  if (t > 1.0 - dt) { const u = (t - 1.0) / dt; return u * u + u + u + 1.0; }
  return 0.0;
}
class Square {
  ph: f32 = 0; dt: f32 = 0;
  setHz(hz: f32): void { this.dt = hz * invSR; }
  tick(): f32 {
    const p = this.ph;
    let s: f32 = p < 0.5 ? 1.0 : -1.0;
    s += polyblep(p, this.dt);
    let q = p + 0.5; if (q >= 1.0) q -= 1.0;
    s -= polyblep(q, this.dt);
    this.ph = p + this.dt; if (this.ph >= 1.0) this.ph -= 1.0;
    return s;
  }
  // Advance without output (oscillators free-run even when nothing sounds).
  skip(n: i32): void { this.ph += this.dt * f32(n); this.ph -= Mathf.floor(this.ph); }
}

// ---- nonlinearities --------------------------------------------------
// Cheap tanh for output limiting (error < 0.3% on |x| < 3, saturates beyond).
@inline function softclip(x: f32): f32 {
  if (x > 3.0) return 1.0;
  if (x < -3.0) return -1.0;
  const x2 = x * x;
  return x * (27.0 + x2) / (27.0 + 9.0 * x2);
}

// The 808's "swing type" VCA: a transistor pair driven hard, so the product
// picks up odd harmonics and a little even-order lean (service notes p.5).
@inline function swingVca(x: f32, env: f32): f32 {
  const y = x * env * 1.6;
  return softclip(y + 0.12 * y * y) * 0.62;
}

// Diode clamp: passes positive, limits negative swing to about one diode drop.
@inline function diodeClamp(x: f32, drop: f32): f32 {
  return x >= 0.0 ? x : -drop * (1.0 - Mathf.exp(x / drop));
}

// Amplitude follower (instant attack, exponential release).
class Follower {
  v: f32 = 0; rel: f32 = 0.999;
  setRelease(tau: f32): void { this.rel = decayCoef(tau); }
  tick(x: f32): f32 {
    const a = Mathf.abs(x);
    this.v = a > this.v ? a : this.v * this.rel;
    return this.v;
  }
}

// ---- step clock -------------------------------------------------------
// Converts a musical position into step boundaries, sample by sample.
// Follows the DAW (transport(): ppq + play state) or free-runs at an internal
// tempo. `absStep` counts steps since the song/run start; a change of it is
// a trigger.
let hostPlaying: bool = false;
let hostPpq: f64 = 0.0;
let hostBpm: f32 = 0.0;
let hostSeen: bool = false;       // transport() has been called at least once

class StepClock {
  ppq: f64 = 0.0;                 // position in quarter notes
  lastStep: i64 = -1;
  running: bool = false;
  fired: bool = false;            // a new step began on this sample
  absStep: i64 = 0;

  // Start the internal clock from the downbeat.
  start(): void { this.ppq = 0.0; this.lastStep = -1; this.running = true; }
  stop(): void { this.running = false; this.lastStep = -1; }

  // Advance one sample. `spb` = steps per quarter note, `bpm` tempo.
  tick(spb: f32, bpm: f32): void {
    this.fired = false;
    if (!this.running) return;
    // Nudge by a hair so a step landing exactly on a quarter note (ppq = 1.0
    // computed as 0.99999…) still fires on the right sample.
    const s = i64(Math.floor(this.ppq * f64(spb) + 1e-9));
    if (s != this.lastStep) { this.lastStep = s; this.absStep = s; this.fired = s >= 0; }
    this.ppq += f64(bpm) / (60.0 * f64(SR));
  }
}

// Every plugin's init() starts here: sample rate, a fixed noise seed (renders
// are reproducible, and a re-init sounds the same), and no stale transport.
function commonInit(sr: f32): void {
  SR = sr; invSR = 1.0 / sr;
  rng = 0x9e3779b9;
  hostPlaying = false; hostPpq = 0.0; hostBpm = 0.0; hostSeen = false;
  for (let i = 0; i < 16; i++) display[i] = 0;
  for (let i = 0; i < 12; i++) flashes[i] = 0;
  dispPeak = 0;
}

// Called by every drum plugin's transport() export.
function setHostTransport(playing: i32, ppq: f64, bpm: f32): void {
  hostPlaying = playing != 0;
  hostPpq = ppq;
  hostBpm = bpm;
  hostSeen = true;
}

@inline function hostTempo(): f32 {
  const t = params[63];
  return t > 1.0 ? t : (hostBpm > 1.0 ? hostBpm : 120.0);
}

// A pattern row stored in one parameter as a 16-bit mask (bit n = step n+1).
@inline function stepOn(row: f32, step: i32): bool {
  const bits = i32(row + 0.5);
  return ((bits >> step) & 1) != 0;
}

// Output stage shared by every plugin: optional drive into a soft clipper,
// loudness-compensated so turning DRIVE up adds grit rather than volume.
@inline function driveStage(x: f32, drive: f32): f32 {
  const d = clampf(drive, 0.0, 1.0);
  return softclip(x * (1.0 + d * 5.0)) / (1.0 + d * 1.8);
}

// ---- display bookkeeping (engine → GUI) --------------------------------
// display[3 + i] = hit flash of voice/slot i, display[15] = output peak.
const flashes = new StaticArray<f32>(12);
let dispPeak: f32 = 0;
@inline function hitFlash(i: i32): void { flashes[i] = 1.0; }
@inline function trackPeak(a: f32): void { const b = Mathf.abs(a); if (b > dispPeak) dispPeak = b; }
function finishDisplay(n: i32): void {
  const fall = Mathf.exp(-f32(n) * invSR / 0.09);
  for (let i = 0; i < 12; i++) { display[3 + i] = flashes[i]; flashes[i] *= fall; }
  display[15] = dispPeak;
  dispPeak *= Mathf.exp(-f32(n) * invSR / 0.25);
}

// ---- ABI exports shared by every drum plugin ----------------------------
export function transport(playing: i32, ppq: f64, bpm: f32): void { setHostTransport(playing, ppq, bpm); }
export function getInputPtr(): usize  { return changetype<usize>(inBuf); }
export function getOutputPtr(): usize { return changetype<usize>(outBuf); }
export function getParamsPtr(): usize { return changetype<usize>(params); }
export function getNumParams(): i32   { return NUM_PARAMS; }
export function getDisplayPtr(): usize { return changetype<usize>(display); }


// =====================================================================
//  drums/tr606/voices.ts — the 1981 battery box: seven analog voices.
//
//  Sources:
//   · TR-606 Owner's Manual (read in full) — instrument mix per voice,
//     accent, scale, last step; the open hi-hat has no decay control.
//   · TR-606 Service Notes (Jan. 1982) — block diagram (twin-T oscillators,
//     noise, six-oscillator metal through band-passes, VCAs, high-passes),
//     output 2 Vp-p un-accented / 6 Vp-p fully accented.
//   · Baratatronix, "Roland 606 Cymbal and Hi-hat Synthesis" — the six
//     Schmitt oscillators (245, 309, 368, 417, 439, 625 Hz), band-passes at
//     3440 / 7100 Hz, the open hat's decay following the tempo, closed hat
//     cutting the open hat.
//   · Robin Whittle, "Modifications for the TR-606" — snare twin-T excited
//     by a +5 V trigger rising to ~+14 V on accents; the toms' low-passed
//     noise "rumble"; the classic snare/decay mods.
//  No per-voice frequency chart was published for BD/SD/toms; those are
//  set by ear against the architecture above and stated in the README.
// =====================================================================

const V606: f32 = 5.0 / 14.0;          // un-accented trigger (≈5 V of 14)
@inline function accent606(acc: f32): f32 { return (5.0 + 9.0 * clampf(acc, 0.0, 1.0)) / 14.0; }
@inline function stage606(h: f32): f32 { return h / (1.0 + 0.06 * h) * 1.0214; }

function velToHeight606(vel: f32, accKnob: f32, dynamic: bool): f32 {
  const acc = accent606(accKnob);
  if (!dynamic) return vel >= 0.787 ? acc : V606;
  if (vel < 0.8) return V606 * (0.3 + 0.7 * vel / 0.8);
  return lerpf(V606, acc, (vel - 0.8) / 0.2);
}

// Twin-T oscillator: a decaying sine from a trigger pulse, with a touch of
// amplitude-dependent pitch like its bigger sibling.
class TwinT {
  res: Svf = new Svf(); t: i32 = -1; h: f32 = 0; fol: Follower = new Follower();
  init(): void { this.res.reset(); this.fol.setRelease(0.04); this.fol.v = 0; this.t = -1; }
  fire(h: f32): void { this.t = 0; this.h = h; }
  tick(f: f32, q: f32, lift: f32): f32 {
    let x: f32 = 0;
    if (this.t >= 0) { x = this.t < msToSamples(0.8) ? this.h : 0.0; this.t++; if (this.t > msToSamples(3.0)) this.t = -1; }
    const rel = this.fol.v / 0.25;
    this.res.set(f * (1.0 + lift * rel / (1.0 + 0.5 * rel)), q);
    this.res.tick(x);
    this.fol.tick(this.res.bp);
    return this.res.bp;
  }
}

// BASS DRUM — short and punchy with a clicky edge. Mods: decay, tune.
class BD606 {
  level: f32 = 0.8; decay: f32 = -1.0; tune: f32 = 0.0;    // decay < 0 = stock
  tt: TwinT = new TwinT(); lp: OnePole = new OnePole(); dc: OnePole = new OnePole(); click: f32 = 0; active: bool = false; q: i32 = 0;
  init(): void { this.tt.init(); this.lp.reset(); this.lp.set(2600.0); this.dc.reset(); this.dc.set(20.0); this.active = false; this.click = 0; this.q = 0; }
  trigger(h: f32): void { h = stage606(h); this.tt.fire(h); this.click = h; this.active = true; this.q = 0; }
  tick(): f32 {
    if (!this.active) return 0.0;
    const f: f32 = 64.0 * Mathf.pow(2.0, this.tune / 12.0);
    const tau: f32 = this.decay < 0.0 ? 0.075 : 0.025 * Mathf.pow(12.0, this.decay);
    const body = this.tt.tick(f, PI * f * tau, 0.12) * 5.4;
    const c = this.lp.lp(this.click * white() * 0.25 + this.click * 0.5) * 0.7;
    this.click *= decayCoef(0.0025);
    const y = this.dc.hp(body + c) * taper(this.level);
    if (Mathf.abs(y) < 0.00003 && this.tt.t < 0) { if (++this.q > 1200) { this.active = false; this.tt.init(); } } else this.q = 0;
    return y;
  }
}

// SNARE — a twin-T and noise through a high-pass with its own envelope.
// Mods: tune (the classic mod lowers it), snappy.
class SD606 {
  level: f32 = 0.8; tune: f32 = 0.0; snappy: f32 = -1.0;
  tt: TwinT = new TwinT(); hp: Svf = new Svf(); n: f32 = 0; nc: f32 = 0.99; active: bool = false; q: i32 = 0;
  init(): void { this.tt.init(); this.hp.reset(); this.hp.set(2200.0, 0.8); this.nc = decayCoef(0.045); this.n = 0; this.active = false; this.q = 0; }
  trigger(h: f32): void { h = stage606(h); this.tt.fire(h); this.n = h; this.active = true; this.q = 0; }
  tick(): f32 {
    if (!this.active) return 0.0;
    const f: f32 = 285.0 * Mathf.pow(2.0, this.tune / 12.0);
    const drum = this.tt.tick(f, PI * f * 0.028, 0.06) * 1.25;
    this.hp.tick(white());
    const snap: f32 = this.snappy < 0.0 ? 0.62 : this.snappy;
    const y = (drum + this.hp.hp * this.n * 0.85 * snap) * 1.1 * taper(this.level);
    this.n *= this.nc;
    if (this.n < 0.0001 && Mathf.abs(y) < 0.00003 && this.tt.t < 0) { if (++this.q > 600) { this.active = false; this.tt.init(); } } else this.q = 0;
    return y;
  }
}

// TOMS — a twin-T each plus a short burst of low-passed noise "rumble".
class Tom606 {
  level: f32 = 0.8; base: f32 = 140.0; tune: f32 = 0.0; decay: f32 = -1.0;
  tt: TwinT = new TwinT(); lp: Svf = new Svf(); n: f32 = 0; active: bool = false; q: i32 = 0;
  init(): void { this.tt.init(); this.lp.reset(); this.lp.set(700.0, 0.6); this.n = 0; this.active = false; this.q = 0; }
  trigger(h: f32): void { h = stage606(h); this.tt.fire(h); this.n = h; this.active = true; this.q = 0; }
  tick(): f32 {
    if (!this.active) return 0.0;
    const f = this.base * Mathf.pow(2.0, this.tune / 12.0);
    const tau: f32 = this.decay < 0.0 ? 0.07 : 0.03 * Mathf.pow(10.0, this.decay);
    const body = this.tt.tick(f, PI * f * tau, 0.1) * (2.2 * 140.0 / this.base + 0.6);
    this.lp.tick(white());
    const y = (body + this.lp.lp * this.n * 0.35) * taper(this.level);
    this.n *= decayCoef(0.012);
    if (Mathf.abs(y) < 0.00003 && this.tt.t < 0) { if (++this.q > 1200) { this.active = false; this.tt.init(); } } else this.q = 0;
    return y;
  }
}

// The six Schmitt oscillators, band-passed at 3440 / 7100 Hz.
class Metal606 {
  o: StaticArray<Square> = new StaticArray<Square>(6);
  lo: Svf = new Svf(); hi: Svf = new Svf(); loOut: f32 = 0; hiOut: f32 = 0;
  init(): void {
    const hz: StaticArray<f32> = [245.1, 308.6, 367.6, 416.6, 438.5, 625.0];
    for (let i = 0; i < 6; i++) { const s = new Square(); s.setHz(hz[i]); s.ph = f32(i) * 0.173; this.o[i] = s; }
    this.lo.reset(); this.hi.reset(); this.lo.set(3440.0, 2.2); this.hi.set(7100.0, 2.2);
  }
  tick(): void {
    let m: f32 = 0;
    for (let i = 0; i < 6; i++) m += unchecked(this.o[i]).tick();
    m *= 0.1667;
    this.lo.tick(m); this.hi.tick(m);
    this.loOut = this.lo.bp * this.lo.k; this.hiOut = this.hi.bp * this.hi.k;
  }
  skip(n: i32): void { for (let i = 0; i < 6; i++) unchecked(this.o[i]).skip(n); }
}

// CYMBAL (both bands, two VCAs on one envelope, two high-passes) and the
// HATS (upper band, resonant high-pass up in the 10 kHz region). The open
// hat has no decay knob: its length follows the tempo. A closed hat cuts it.
class Metals606 {
  cyLevel: f32 = 0.8; hhLevel: f32 = 0.8; cyDecay: f32 = -1.0; ohDecay: f32 = -1.0; stepSec: f32 = 0.125;
  cyHpA: Svf = new Svf(); cyHpB: Svf = new Svf(); ohHp: Svf = new Svf(); chHp: Svf = new Svf();
  cy: f32 = 0; oh: f32 = 0; ch: f32 = 0; cyC: f32 = 0.999; ohC: f32 = 0.999; choke: bool = false;
  cyOut: f32 = 0; ohOut: f32 = 0; chOut: f32 = 0;
  init(): void {
    this.cyHpA.reset(); this.cyHpB.reset(); this.ohHp.reset(); this.chHp.reset();
    this.cyHpA.set(5200.0, 1.1); this.cyHpB.set(2400.0, 0.7); this.ohHp.set(9500.0, 1.4); this.chHp.set(10500.0, 1.4);
    this.cy = 0; this.oh = 0; this.ch = 0; this.choke = false; this.cyOut = 0; this.ohOut = 0; this.chOut = 0;
  }
  any(): bool { return this.cy > 0.00003 || this.oh > 0.00003 || this.ch > 0.00003; }
  cyTrigger(h: f32): void { this.cy = stage606(h); this.cyC = decayCoef(this.cyDecay < 0.0 ? 0.32 : 0.08 * Mathf.pow(12.0, this.cyDecay)); }
  ohTrigger(h: f32): void {
    this.oh = stage606(h); this.choke = false;
    // stock: the envelope length is tied to the step clock (≈ two steps)
    this.ohC = decayCoef(this.ohDecay < 0.0 ? clampf(this.stepSec * 0.85, 0.03, 0.5) : 0.03 * Mathf.pow(15.0, this.ohDecay));
  }
  chTrigger(h: f32): void { this.ch = stage606(h); if (this.oh > 0.00003) this.choke = true; }
  tick(m: Metal606): void {
    this.cyOut = 0; this.ohOut = 0; this.chOut = 0;
    if (this.cy > 0.00003) {
      this.cyHpA.tick(swingVca(m.hiOut, this.cy)); this.cyHpB.tick(swingVca(m.loOut, this.cy));
      this.cyOut = (this.cyHpA.hp * 1.1 + this.cyHpB.hp * 0.9) * 12.0 * taper(this.cyLevel);
      this.cy *= this.cyC;
    }
    if (this.oh > 0.00003) {
      this.ohHp.tick(swingVca(m.hiOut, this.oh));
      this.ohOut = this.ohHp.hp * 24.0 * taper(this.hhLevel);
      this.oh *= this.choke ? decayCoef(0.004) : this.ohC;
    }
    if (this.ch > 0.00003) {
      this.chHp.tick(swingVca(m.hiOut, this.ch));
      this.chOut = this.chHp.hp * 30.0 * taper(this.hhLevel);
      this.ch *= decayCoef(0.016);
    }
  }
}


// ---- generated from defs.mjs -----------------------------------------

const P_LEV: i32 = 0;
const P_OH_DEC: i32 = 1;
const P_TEMPO: i32 = 2;
const P_FOLLOW: i32 = 3;
const P_AC: i32 = 4;
const P_VELMODE: i32 = 5;
const P_DRIVE: i32 = 6;
const NUM_PARAMS: i32 = 7;
function setDefaults(): void {
  params[0] = 0.8;   // Level
  params[1] = -0.05;   // Mod OH Decay
  params[2] = 128.0;   // Tempo (OH decay)
  params[3] = 1.0;   // Follow DAW Tempo
  params[4] = 0.6;   // Accent
  params[5] = 0.0;   // Velocity Mode
  params[6] = 0.0;   // Drive
}

// SILVERBOX HATS — open and closed hat together (closed cuts open). The
// stock open hat has no decay knob: its length follows the tempo — the
// DAW's when FOLLOW is on, otherwise the Tempo knob. 42/44 closed, 46 open;
// other notes: C–F closed, F♯–B open.
const metal = new Metal606(); const mx = new Metals606();
function applyParams(): void {
  mx.hhLevel = params[P_LEV]; mx.ohDecay = params[P_OH_DEC];
  const bpm = params[P_FOLLOW] > 0.5 ? hostTempo() : clampf(params[P_TEMPO], 40.0, 300.0);
  mx.stepSec = 60.0 / (bpm * 4.0);
}
export function init(sr: f32, maxFrames: i32, numChannels: i32): void { commonInit(sr); metal.init(); mx.init(); setDefaults(); }
export function noteOn(id: i32, hz: f32, vel: f32): void {
  applyParams();
  const h = velToHeight606(vel, params[P_AC], params[P_VELMODE] > 0.5);
  let open = id == 46;
  if (id != 42 && id != 44 && id != 46) open = ((id % 12) + 12) % 12 >= 6;
  if (open) { mx.ohTrigger(h); hitFlash(1); } else { mx.chTrigger(h); hitFlash(0); }
}
export function noteOff(id: i32): void {}
export function process(n: i32): void {
  applyParams(); const drive = params[P_DRIVE];
  for (let f = 0; f < n; f++) {
    let y: f32 = 0;
    if (mx.any()) { metal.tick(); mx.tick(metal); y = mx.ohOut + mx.chOut; } else metal.skip(1);
    y = driveStage(y, drive); unchecked(outBuf[f] = y); unchecked(outBuf[MAX_FRAMES + f] = y); trackPeak(y);
  }
  finishDisplay(n);
}
