#!/usr/bin/env node
// =====================================================================
//  drums/build.mjs — assemble the drum-machine plugins.
//
//  A .vstai carries ONE AssemblyScript file and ONE gui.html, but the drum
//  plugins share their voices: the single "kick" plugin must be the very same
//  circuit model as the kick inside the full machine. So the sources live
//  here, split by concern, and this script pastes them together:
//
//    assembly.ts = drums/common.ts + <machine>/voices.ts
//                + generated P_* constants, NUM_PARAMS, setDefaults()
//                + the plugin's wrapper (<machine>/<wrapper>.ts)
//    gui.html    = the plugin's template with /*@KIT@*/ → ui/kit.js and
//                  /*@PARAMS@*/ → the parameter table
//    spec.json   = what factory/tools/pack-vstai.mjs reads
//
//  Parameter definitions (defs.mjs) are the single source of truth for
//  indices, ranges and defaults — DSP, GUI and spec can't drift apart.
//
//  Usage: node factory/drums/build.mjs [slug …] [--pack]
//         (no slugs = every registered plugin)
// =====================================================================
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { REGISTRY } from "./registry.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const rd = (p) => readFileSync(resolve(here, p), "utf8");

function generated(defs) {
  const lines = defs.map((d, i) => `const P_${d.key}: i32 = ${i};`);
  lines.push(`const NUM_PARAMS: i32 = ${defs.length};`);
  const fmt = (v) => (Number.isInteger(v) ? v.toFixed(1) : String(v));
  lines.push("function setDefaults(): void {");
  defs.forEach((d, i) => lines.push(`  params[${i}] = ${fmt(d.def)};   // ${d.name}`));
  lines.push("}");
  return lines.join("\n");
}

function buildOne(p) {
  if (p.defs.length > 63) throw new Error(`${p.slug}: ${p.defs.length} params — slot 63 is the host tempo`);
  const dir = join(root, "factory/plugins", p.slug);
  mkdirSync(dir, { recursive: true });

  // Sources: drum plugins are common + machine voices + wrapper; other
  // families list theirs explicitly (paths relative to factory/drums/). The
  // generated constants go in front of the last file (the plugin wrapper).
  const files = p.sources || ["common.ts", `${p.machine}/voices.ts`, `${p.machine}/${p.wrapper}`];
  const asm = [
    "// =====================================================================",
    `//  ${p.name} — GENERATED by factory/drums/build.mjs. Edit the sources:`,
    ...files.map((f) => `//    factory/drums/${f}`),
    "// =====================================================================",
    ...files.slice(0, -1).map(rd),
    "// ---- generated from defs.mjs -----------------------------------------",
    generated(p.defs),
    rd(files[files.length - 1]),
  ].join("\n\n");
  writeFileSync(join(dir, "assembly.ts"), asm);

  const table = p.defs.map((d, i) => ({ index: i, key: d.key, name: d.name, min: d.min, max: d.max, def: d.def, step: d.step || 0 }));
  const gui = rd(p.gui)
    .replace("/*@KIT@*/", () => rd("ui/kit.js"))
    .replace("/*@PATTERNS@*/", () => rd("ui/patterns.json"))
    .replace("/*@PARAMS@*/", () => JSON.stringify(table))
    .replace("/*@CONFIG@*/", () => JSON.stringify(p.guiConfig || {}));
  writeFileSync(join(dir, "gui.html"), gui);

  const spec = {
    name: p.name,
    isInstrument: true,
    explanation: p.explanation,
    assembly: `factory/plugins/${p.slug}/assembly.ts`,
    out: `factory/plugins/${p.slug}/x.vstai`,
    guiFile: `factory/plugins/${p.slug}/gui.html`,
    publishedAt: p.publishedAt || Date.now(),
    theme: p.theme,
    params: table.map((t) => ({ name: t.name, index: t.index, min: t.min, max: t.max, default: t.def, ...(t.step ? { step: t.step } : {}) })),
  };
  writeFileSync(join(dir, "spec.json"), JSON.stringify(spec, null, 2) + "\n");
  return dir;
}

const args = process.argv.slice(2);
const pack = args.includes("--pack");
const wanted = args.filter((a) => !a.startsWith("--"));
const list = wanted.length ? REGISTRY.filter((p) => wanted.includes(p.slug)) : REGISTRY;
if (wanted.length && list.length !== wanted.length)
  throw new Error("unknown slug(s): " + wanted.filter((w) => !REGISTRY.some((p) => p.slug === w)).join(", "));

for (const p of list) {
  const dir = buildOne(p);
  console.log(`built ${p.slug}  (${p.defs.length} params)`);
  if (pack) execFileSync("node", [join(root, "factory/tools/pack-vstai.mjs"), join(dir, "spec.json")], { stdio: "inherit" });
}
