#!/usr/bin/env node
// =====================================================================
//  kheverest/build.mjs — assemble the KHEVEREST plugin.
//    node factory/kheverest/build.mjs [--pack] [--no-gui]
//  → factory/plugins/kheverest/{assembly.ts, gui.html, spec.json}
//    (a .vstai carries ONE source file and ONE gui.html, so sources are
//     pasted together: generated tables + dsp/core + voice + fx + main)
// =====================================================================
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { P, SLOT_MAX, LFO_SYNC, ARP_SYNC, DELAY_SYNC, LR_RATIOS, MOD_SLOTS } from "./params.mjs";
import { L, assertFits, slotDefaults } from "./pack.mjs";
import { EXPLANATION } from "./explanation.mjs";
import { WT_B64, WT_COUNT, TUNINGS, ARP_PATTERNS } from "./tables.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const out = join(root, "factory/plugins/kheverest");
const rd = (p) => readFileSync(join(here, p), "utf8");
assertFits();

const f32 = (v) => { const s = String(Number(v)); return /[.e]/i.test(s) ? s : s + ".0"; };
const idx = (k) => { const i = P.findIndex((p) => p.key === k); if (i < 0) throw new Error("no key " + k); return i; };

function generated() {
  const arr = (name, type, fn) => `const ${name}: StaticArray<${type}> = [${P.map(fn).join(", ")}];`;
  const defs = slotDefaults();
  const patStart = [0]; const patData = [];
  const code = { "-": 0, x: 1, o: 2, X: 3, _: 4 };
  for (const pt of ARP_PATTERNS) { for (const c of pt) patData.push(code[c]); patStart.push(patData.length); }
  const frac = LR_RATIOS.map((r) => r.split("/").map(Number));
  return [
    `const NP: i32 = ${P.length};`,
    `const NUM_PARAMS: i32 = ${L.slots};`,
    ...P.map((p, i) => `const P_${p.key}: i32 = ${i};`),
    arr("PSLOT", "i32", (p) => p.slot),
    arr("PMULT", "i32", (p) => p.mult),
    arr("PSTEPS", "i32", (p) => p.steps),
    arr("PCURVE", "i32", (p) => (p.curve === "int" ? 2 : 0)),
    arr("PDIRECT", "i32", (p) => (p.direct ? 1 : 0)),
    arr("PMIN", "f32", (p) => f32(p.min)),
    arr("PMAX", "f32", (p) => f32(p.max)),
    `const ENV_P0: StaticArray<i32> = [P_EA_A, P_EM1_A, P_EM2_A];`,
    `const LFO_P0: StaticArray<i32> = [P_L1_TYPE, P_L2_TYPE];`,
    `const OSC_P0: StaticArray<i32> = [P_O1_RANGE, P_O2_RANGE, P_O3_RANGE];`,
    `const MM_P0: i32 = P_MM1_A;`,
    `const FM_P0: i32 = P_FM1_A;`,
    `const LFO_TICKS: StaticArray<f32> = [${LFO_SYNC.map((x) => f32(x[1])).join(", ")}];`,
    `const ARP_TICKS: StaticArray<f32> = [${ARP_SYNC.map((x) => f32(x[1])).join(", ")}];`,
    `const DLY_TICKS: StaticArray<f32> = [${DELAY_SYNC.map((x) => f32(x[1])).join(", ")}];`,
    `const LR_NUM: StaticArray<f32> = [${frac.map((x) => f32(x[0])).join(", ")}];`,
    `const LR_DEN: StaticArray<f32> = [${frac.map((x) => f32(x[1])).join(", ")}];`,
    `const TUNE: StaticArray<f32> = [${TUNINGS.flat().map(f32).join(", ")}];`,
    `const PAT_START: StaticArray<i32> = [${patStart.join(", ")}];`,
    `const PAT_DATA: StaticArray<i32> = [${patData.join(", ")}];`,
    `const WT_TABLES: i32 = ${WT_COUNT};`,
    `const WT_B64: string = "${WT_B64}";`,
    "function setDefaults(): void {",
    ...defs.map((v, s) => `  params[${s}] = ${f32(v)};`),
    "}",
  ].join("\n");
}

function buildDsp() {
  const files = ["dsp/core.ts", "dsp/voice.ts", "dsp/fx.ts", "dsp/main.ts"];
  const header = [
    "// =====================================================================",
    "//  KHEVEREST — GENERATED by factory/kheverest/build.mjs. Edit the sources:",
    "//    factory/kheverest/params.mjs   (parameter table + packing)",
    "//    factory/kheverest/tables.mjs   (wavetable recipes, tunings, arp patterns)",
    ...files.map((f) => `//    factory/kheverest/${f}`),
    "// =====================================================================",
  ].join("\n");
  return [header, generated(), ...files.map(rd)].join("\n\n");
}

function buildSpec() {
  const slots = [];
  const dv = slotDefaults();
  for (let s = 0; s < L.slots; s++) {
    const d = P.find((p) => p.slot === s && p.direct);
    slots.push(d
      ? { name: d.name, index: s, min: d.min, max: d.max, default: d.def }
      : { name: `Pack ${String(s).padStart(2, "0")}`, index: s, min: 0, max: SLOT_MAX, default: dv[s] });
  }
  return {
    name: "KHeverest",
    isInstrument: true,
    explanation: EXPLANATION.replace("@N@", String(P.length)),
    assembly: "factory/plugins/kheverest/assembly.ts",
    out: "factory/plugins/kheverest/x.vstai",
    guiFile: "factory/plugins/kheverest/gui.html",
    publishedAt: Date.now(),
    theme: { accent: "#4cc9ff", accent2: "#ffffff" },
    params: slots,
  };
}

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "assembly.ts"), buildDsp());
writeFileSync(join(out, "spec.json"), JSON.stringify(buildSpec(), null, 2) + "\n");
console.log(`assembly.ts + spec.json written  (${P.length} controls in ${L.slots} host slots)`);

if (!process.argv.includes("--no-gui") && existsSync(join(here, "gui/build-gui.mjs"))) {
  const { buildGui } = await import("./gui/build-gui.mjs");
  writeFileSync(join(out, "gui.html"), buildGui());
  console.log("gui.html written");
}
if (process.argv.includes("--pack")) {
  execFileSync("node", [join(root, "factory/tools/pack-vstai.mjs"), join(out, "spec.json")], { stdio: "inherit" });
}
