#!/usr/bin/env node
// =====================================================================
//  doob/build.mjs — assemble the Doob plugin.
//    node factory/doob/build.mjs [--pack] [--no-gui]
//  → factory/plugins/doob/{assembly.ts, gui.html, spec.json}
// =====================================================================
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { P, SLOT_MAX } from "./params.mjs";
import { L, assertFits, slotDefaults } from "./pack.mjs";
import { EXPLANATION } from "./explanation.mjs";
import { SCALE_DEV, PARTCH, KEYERR } from "./scales.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const out = join(root, "factory/plugins/doob");
const rd = (p) => readFileSync(join(here, p), "utf8");
assertFits();

const f32 = (v) => { const s = String(Number(v)); return /[.e]/i.test(s) ? s : s + ".0"; };

function generated() {
  const arr = (name, type, fn) => `const ${name}: StaticArray<${type}> = [${P.map(fn).join(", ")}];`;
  const defs = slotDefaults();
  return [
    `const NP: i32 = ${P.length};`,
    `const NUM_PARAMS: i32 = ${L.slots};`,
    ...P.map((p, i) => `const P_${p.key}: i32 = ${i};`),
    arr("PSLOT", "i32", (p) => p.slot),
    arr("PMULT", "i32", (p) => p.mult),
    arr("PSTEPS", "i32", (p) => p.steps),
    arr("PDIRECT", "i32", (p) => (p.direct ? 1 : 0)),
    arr("PMIN", "f32", (p) => f32(p.min)),
    arr("PMAX", "f32", (p) => f32(p.max)),
    `const SCALE_DEV: StaticArray<f32> = [${SCALE_DEV.map(f32).join(", ")}];`,
    `const PARTCH: StaticArray<f32> = [${PARTCH.map(f32).join(", ")}];`,
    `const KEYERR: StaticArray<f32> = [${KEYERR.map(f32).join(", ")}];`,
    "function setDefaults(): void {",
    ...defs.map((v, s) => `  params[${s}] = ${f32(v)};`),
    "}",
  ].join("\n");
}

function buildDsp() {
  const files = ["dsp/core.ts", "dsp/osc.ts", "dsp/mods.ts", "dsp/keys.ts", "dsp/main.ts"];
  const header = [
    "// =====================================================================",
    "//  Doob — GENERATED by factory/doob/build.mjs. Edit the sources:",
    "//    factory/doob/params.mjs   (parameter table + packing)",
    "//    factory/doob/scales.mjs   (scale / key-error tables)",
    ...files.map((f) => `//    factory/doob/${f}`),
    "// =====================================================================",
  ].join("\n");
  return [header, generated(), ...files.map(rd)].join("\n\n");
}

function buildSpec() {
  const slots = [];
  const dv = slotDefaults();
  for (let s = 0; s < L.slots; s++) {
    const d = P.find((p) => p.slot === s && p.direct);
    slots.push(d
      ? { name: d.name, index: s, min: d.min, max: d.max, default: d.def }
      : { name: `Pack ${String(s).padStart(2, "0")}`, index: s, min: 0, max: SLOT_MAX, default: dv[s] });
  }
  return {
    name: "Doob",
    isInstrument: true,
    explanation: EXPLANATION.replace("@N@", String(P.length)),
    assembly: "factory/plugins/doob/assembly.ts",
    out: "factory/plugins/doob/x.vstai",
    guiFile: "factory/plugins/doob/gui.html",
    publishedAt: Date.now(),
    theme: { accent: "#e8a33a", accent2: "#f4ead2" },
    params: slots,
  };
}

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "assembly.ts"), buildDsp());
writeFileSync(join(out, "spec.json"), JSON.stringify(buildSpec(), null, 2) + "\n");
console.log(`assembly.ts + spec.json written  (${P.length} controls in ${L.slots} host slots)`);

if (!process.argv.includes("--no-gui") && existsSync(join(here, "gui/build-gui.mjs"))) {
  const { buildGui } = await import("./gui/build-gui.mjs");
  writeFileSync(join(out, "gui.html"), buildGui());
  console.log("gui.html written");
}
if (process.argv.includes("--pack")) {
  execFileSync("node", [join(root, "factory/tools/pack-vstai.mjs"), join(out, "spec.json")], { stdio: "inherit" });
}
