// =====================================================================
//  STDROOM — Small natural room
//  A small-room reverb for putting drums, vocals and guitars in a believable space without washing them out. Eight short delay lines are coupled by a Householder feedback matrix (a lossless mixing matrix, so the tail stays smooth and metal-free), with per-line decay set from a real RT60 time, one-pole damping that makes highs die faster than lows, four input diffusers and a touch of delay-time modulation to stop ringing. Size scales the whole room from a closet to a studio.
//  (generated by factory/std/build.mjs from factory/std/fx-*.mjs — edit the definition, not this file)
// =====================================================================
// ---- Std prelude: shared helpers (pasted into every Std* effect by factory/std/build.mjs) ----
const MAX_FRAMES: i32 = 8192;
const MAX_CHANNELS: i32 = 2;
const MAX_PARAMS: i32 = 64;
const TWO_PI: f32 = 6.28318530717959;
const PI: f32 = 3.14159265358979;

const inBuf:  StaticArray<f32> = new StaticArray<f32>(MAX_FRAMES * MAX_CHANNELS);
const outBuf: StaticArray<f32> = new StaticArray<f32>(MAX_FRAMES * MAX_CHANNELS);
const params: StaticArray<f32> = new StaticArray<f32>(MAX_PARAMS);
const display: StaticArray<f32> = new StaticArray<f32>(16);

let sampleRate: f32 = 48000.0;
let hostPlaying: bool = false;
let hostBpm: f32 = 120.0;
let beatPos: f64 = 0.0;
let seed: u32 = 12345;

@inline function clampf(x: f32, lo: f32, hi: f32): f32 { return x < lo ? lo : (x > hi ? hi : x); }
@inline function minf(a: f32, b: f32): f32 { return a < b ? a : b; }
@inline function maxf(a: f32, b: f32): f32 { return a > b ? a : b; }
@inline function absf(x: f32): f32 { return x < 0.0 ? -x : x; }
@inline function rnd(): f32 { seed = seed * 1664525 + 1013904223; return f32(seed >> 8) * (1.0 / 8388608.0) - 1.0; }
// flush denormals out of feedback paths
@inline function fz(x: f32): f32 { return (x > -1.0e-18 && x < 1.0e-18) ? 0.0 : x; }
// exponential map: v in 0..1 -> lo..hi
@inline function expMap(v: f32, lo: f32, hi: f32): f32 { return lo * f32(Mathf.pow(hi / lo, v)); }
@inline function dbLin(db: f32): f32 { return f32(Mathf.pow(10.0, db * 0.05)); }
@inline function linDb(x: f32): f32 { return 20.0 * f32(Mathf.log10(x + 1.0e-9)); }
@inline function tanhf(x: f32): f32 { return f32(Mathf.tanh(x)); }
// one-pole smoothing coefficient for a cutoff in Hz
@inline function opK(hz: f32): f32 { return 1.0 - f32(Mathf.exp(-TWO_PI * clampf(hz, 1.0, sampleRate * 0.45) / sampleRate)); }
// smoothing coefficient for a time constant in seconds
@inline function tcK(sec: f32): f32 { return 1.0 - f32(Mathf.exp(-1.0 / (maxf(sec, 0.00002) * sampleRate))); }
// soft output limiter: transparent below 0.8, rounds smoothly to 1.0
@inline function softLim(x: f32): f32 {
  const a: f32 = absf(x);
  if (a < 0.8) return x;
  const y: f32 = 0.8 + 0.2 * f32(Mathf.tanh((a - 0.8) * 5.0));
  return x < 0.0 ? -y : y;
}

// power-of-two delay line with linear interpolation. base = start in buf, mask = len-1, wr = write index
@inline function dlr(buf: StaticArray<f32>, base: i32, mask: i32, wr: i32, d: f32): f32 {
  const p: f32 = f32(wr) - d;
  const fl: f32 = f32(Mathf.floor(p));
  const i0: i32 = i32(fl);
  const fr: f32 = p - fl;
  const a: f32 = buf[base + (i0 & mask)];
  const b: f32 = buf[base + ((i0 + 1) & mask)];
  return a + (b - a) * fr;
}

// RBJ biquad. coefficients stored normalised at cf[o..o+4] = b0 b1 b2 a1 a2
// t: 0 LP, 1 HP, 2 BP (0 dB peak), 3 notch, 4 peaking, 5 low shelf, 6 high shelf, 7 allpass
function bqSetSr(cf: StaticArray<f32>, o: i32, t: i32, f0: f32, q: f32, g: f32, sr: f32): void {
  const fc: f32 = clampf(f0, 5.0, sr * 0.45);
  const w0: f32 = TWO_PI * fc / sr;
  const c: f32 = f32(Mathf.cos(w0));
  const s: f32 = f32(Mathf.sin(w0));
  const al: f32 = s / (2.0 * maxf(q, 0.05));
  const A: f32 = f32(Mathf.pow(10.0, g / 40.0));
  let b0: f32 = 1.0; let b1: f32 = 0.0; let b2: f32 = 0.0;
  let a0: f32 = 1.0; let a1: f32 = 0.0; let a2: f32 = 0.0;
  if (t == 0) { b0 = (1.0 - c) * 0.5; b1 = 1.0 - c; b2 = b0; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  else if (t == 1) { b0 = (1.0 + c) * 0.5; b1 = -(1.0 + c); b2 = b0; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  else if (t == 2) { b0 = al; b1 = 0.0; b2 = -al; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  else if (t == 3) { b0 = 1.0; b1 = -2.0 * c; b2 = 1.0; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  else if (t == 4) { b0 = 1.0 + al * A; b1 = -2.0 * c; b2 = 1.0 - al * A; a0 = 1.0 + al / A; a1 = -2.0 * c; a2 = 1.0 - al / A; }
  else if (t == 5) {
    const sa: f32 = 2.0 * f32(Mathf.sqrt(A)) * al;
    b0 = A * ((A + 1.0) - (A - 1.0) * c + sa); b1 = 2.0 * A * ((A - 1.0) - (A + 1.0) * c); b2 = A * ((A + 1.0) - (A - 1.0) * c - sa);
    a0 = (A + 1.0) + (A - 1.0) * c + sa; a1 = -2.0 * ((A - 1.0) + (A + 1.0) * c); a2 = (A + 1.0) + (A - 1.0) * c - sa;
  } else if (t == 6) {
    const sb: f32 = 2.0 * f32(Mathf.sqrt(A)) * al;
    b0 = A * ((A + 1.0) + (A - 1.0) * c + sb); b1 = -2.0 * A * ((A - 1.0) + (A + 1.0) * c); b2 = A * ((A + 1.0) + (A - 1.0) * c - sb);
    a0 = (A + 1.0) - (A - 1.0) * c + sb; a1 = 2.0 * ((A - 1.0) - (A + 1.0) * c); a2 = (A + 1.0) - (A - 1.0) * c - sb;
  } else { b0 = 1.0 - al; b1 = -2.0 * c; b2 = 1.0 + al; a0 = 1.0 + al; a1 = -2.0 * c; a2 = 1.0 - al; }
  const ia: f32 = 1.0 / a0;
  cf[o] = b0 * ia; cf[o + 1] = b1 * ia; cf[o + 2] = b2 * ia; cf[o + 3] = a1 * ia; cf[o + 4] = a2 * ia;
}
@inline function bqSet(cf: StaticArray<f32>, o: i32, t: i32, f0: f32, q: f32, g: f32): void { bqSetSr(cf, o, t, f0, q, g, sampleRate); }
// transposed direct form II; state z[s], z[s+1]
@inline function bq(cf: StaticArray<f32>, o: i32, z: StaticArray<f32>, s: i32, x: f32): f32 {
  const y: f32 = cf[o] * x + z[s];
  z[s] = fz(cf[o + 1] * x - cf[o + 3] * y + z[s + 1]);
  z[s + 1] = fz(cf[o + 2] * x - cf[o + 4] * y);
  return y;
}

const NUM_PARAMS: i32 = 11;
const P_DECAY: i32 = 0;
const P_SIZE: i32 = 1;
const P_PREDELAY: i32 = 2;
const P_DAMPING: i32 = 3;
const P_DIFFUSION: i32 = 4;
const P_MOD: i32 = 5;
const P_LOWCUT: i32 = 6;
const P_HIGHCUT: i32 = 7;
const P_WIDTH: i32 = 8;
const P_MIX: i32 = 9;
const P_OUTPUT: i32 = 10;
function setDefaults(): void {
  params[0] = 0.28;   // Decay
  params[1] = 0.5;   // Size
  params[2] = 0.02;   // Pre-Delay
  params[3] = 0.55;   // Damping
  params[4] = 0.7;   // Diffusion
  params[5] = 0.15;   // Mod
  params[6] = 0.1;   // Low Cut
  params[7] = 0.9;   // High Cut
  params[8] = 1.0;   // Width
  params[9] = 0.25;   // Mix
  params[10] = 0.0;   // Output
}


const FL: i32 = 32768; const FM: i32 = 32767;
const fbuf: StaticArray<f32> = new StaticArray<f32>(8 * 32768);
const fW: StaticArray<i32> = new StaticArray<i32>(8);
const fLp: StaticArray<f32> = new StaticArray<f32>(8);
const fG: StaticArray<f32> = new StaticArray<f32>(8);
const fDs: StaticArray<f32> = new StaticArray<f32>(8);
const fLfo: StaticArray<f32> = new StaticArray<f32>(8);
const rdv: StaticArray<f32> = new StaticArray<f32>(8);
const vv: StaticArray<f32> = new StaticArray<f32>(8);
const BMS: StaticArray<f32> = [7.1, 9.3, 11.7, 13.9, 16.3, 18.9, 21.7, 24.3];
const SGN: StaticArray<f32> = [1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0];
const dBuf: StaticArray<f32> = new StaticArray<f32>(4 * 4096);
const dW: StaticArray<i32> = new StaticArray<i32>(4);
const dLen: StaticArray<i32> = new StaticArray<i32>(4);
const DMS: StaticArray<f32> = [3.1, 4.3, 5.9, 7.7];
const preBuf: StaticArray<f32> = new StaticArray<f32>(65536); let preW: i32 = 0;
const wf: StaticArray<f32> = new StaticArray<f32>(4);
let szS: f32 = 1.0;

export function getInputPtr(): usize  { return changetype<usize>(inBuf); }
export function getOutputPtr(): usize { return changetype<usize>(outBuf); }
export function getParamsPtr(): usize { return changetype<usize>(params); }
export function getNumParams(): i32   { return NUM_PARAMS; }
export function getDisplayPtr(): usize { return changetype<usize>(display); }
export function transport(playing: i32, ppq: f64, bpm: f32): void {
  hostPlaying = playing != 0; if (bpm > 20.0) hostBpm = bpm;
  if (hostPlaying) beatPos = ppq;
}

export function init(sr: f32, maxFrames: i32, numChannels: i32): void {
  sampleRate = sr > 0.0 ? sr : 48000.0;
  hostPlaying = false; hostBpm = 120.0; beatPos = 0.0; seed = 12345;
  setDefaults();
  for (let i = 0; i < 16; i++) display[i] = 0.0;
  
  for (let i = 0; i < 8 * 32768; i++) fbuf[i] = 0.0;
  for (let i = 0; i < 8; i++) { fW[i] = 0; fLp[i] = 0.0; fG[i] = 0.0; fDs[i] = 0.0; fLfo[i] = f32(i) * 0.125; rdv[i] = 0.0; vv[i] = 0.0; }
  for (let i = 0; i < 4 * 4096; i++) dBuf[i] = 0.0;
  for (let i = 0; i < 4; i++) { dW[i] = 0; dLen[i] = min(4090, i32(DMS[i] * 0.001 * sampleRate + 0.5)); wf[i] = 0.0; }
  for (let i = 0; i < 65536; i++) preBuf[i] = 0.0;
  preW = 0; szS = expMap(params[P_SIZE], 0.5, 2.0);
}

export function process(n: i32): void {
  const sr: f32 = sampleRate;
  let pkIn: f32 = 0.0; let pkOut: f32 = 0.0;
  
  const rt: f32 = expMap(params[P_DECAY], 0.2, 20.0); const szT: f32 = expMap(params[P_SIZE], 0.5, 2.0);
  const pdN: i32 = i32(params[P_PREDELAY] * 0.25 * sr);
  const dK: f32 = opK(expMap(1.0 - params[P_DAMPING], 1500.0, 20000.0));
  const dg: f32 = 0.15 + params[P_DIFFUSION] * 0.6;
  const modD: f32 = params[P_MOD] * 0.0004 * sr;
  const wid: f32 = params[P_WIDTH];
  const hpK: f32 = opK(expMap(params[P_LOWCUT], 20.0, 800.0)); const lpK: f32 = opK(expMap(params[P_HIGHCUT], 1000.0, 20000.0));
  const mix: f32 = params[P_MIX]; const outG: f32 = dbLin(params[P_OUTPUT]);
  for (let i: i32 = 0; i < 8; i++) {
    const ds: f32 = clampf(BMS[i] * 0.001 * sr * szS, 4.0, f32(FL - 64));
    fG[i] = f32(Mathf.pow(10.0, -3.0 * ds / (rt * sr)));
  }
  const lfoInc0: f32 = 0.1 / sr;
  for (let f = 0; f < n; f++) {
    const xl: f32 = inBuf[f]; const xr: f32 = inBuf[MAX_FRAMES + f];
    let yl: f32 = xl; let yr: f32 = xr;
    
    
  szS += (szT - szS) * 0.0004;
  preBuf[preW] = (xl + xr) * 0.5; preW = (preW + 1) & 65535;
  let s: f32 = preBuf[(preW - 1 - pdN) & 65535];
  for (let j: i32 = 0; j < 4; j++) {
    const o: i32 = j * 4096; const z: f32 = dBuf[o + dW[j]];
    const w: f32 = s + dg * z; dBuf[o + dW[j]] = fz(w); s = z - dg * w;
    let nw: i32 = dW[j] + 1; if (nw >= dLen[j]) nw = 0; dW[j] = nw;
  }
  s *= 0.65;
  let sum: f32 = 0.0;
  for (let i: i32 = 0; i < 8; i++) {
    fLfo[i] += lfoInc0 * (1.0 + f32(i) * 0.37); if (fLfo[i] >= 1.0) fLfo[i] -= 1.0;
    const dd: f32 = clampf(BMS[i] * 0.001 * sr * szS + modD * f32(Mathf.sin(fLfo[i] * TWO_PI)), 2.0, f32(FL - 8));
    const r: f32 = dlr(fbuf, i * FL, FM, fW[i], dd);
    rdv[i] = r;
    fLp[i] = fz(fLp[i] + dK * (r - fLp[i]));
    const v: f32 = fLp[i] * fG[i]; vv[i] = v; sum += v;
  }
  const hh: f32 = sum * 0.25;
  for (let i: i32 = 0; i < 8; i++) {
    fbuf[i * FL + fW[i]] = fz(vv[i] - hh + s * SGN[i]);
    fW[i] = (fW[i] + 1) & FM;
  }
  let wl: f32 = (rdv[0] - rdv[2] + rdv[4] - rdv[6]) * 0.5; let wr: f32 = (rdv[1] - rdv[3] + rdv[5] - rdv[7]) * 0.5;
  const md: f32 = (wl + wr) * 0.5; const sd: f32 = (wl - wr) * 0.5 * wid; wl = md + sd; wr = md - sd;
  wf[0] += hpK * (wl - wf[0]); wl -= wf[0]; wf[1] += hpK * (wr - wf[1]); wr -= wf[1];
  wf[2] += lpK * (wl - wf[2]); wl = wf[2]; wf[3] += lpK * (wr - wf[3]); wr = wf[3];
  yl = softLim((xl * (1.0 - mix) + wl * mix) * outG); yr = softLim((xr * (1.0 - mix) + wr * mix) * outG);
    if (!(yl == yl)) yl = 0.0; if (!(yr == yr)) yr = 0.0;
    outBuf[f] = yl; outBuf[MAX_FRAMES + f] = yr;
    pkIn = maxf(pkIn, maxf(absf(xl), absf(xr))); pkOut = maxf(pkOut, maxf(absf(yl), absf(yr)));
    
  }
  display[0] = maxf(display[0] * 0.8, clampf(pkOut, 0.0, 1.0));
  display[1] = maxf(display[1] * 0.8, clampf(pkIn, 0.0, 1.0));
  
}
